<?php

return [
    // ── Public Navbar ──
    'nav.inicio' => 'Home',
    'nav.produtos' => 'Products',
    'nav.infraestrutura' => 'Infrastructure',
    'nav.recursos' => 'Resources',
    'nav.planos' => 'Plans',
    'nav.status' => 'Status',
    'nav.contato' => 'Contact',
    'nav.entrar' => 'Sign In',
    'nav.contratar' => 'Get Started',
    'nav.changelog' => 'Changelog',
    'nav.termos' => 'Terms of Use',
    'nav.privacidade' => 'Privacy',
    'nav.licenca' => 'License',

    // Mega: Products
    'mega.prod_infra' => 'Infrastructure',
    'mega.prod_vps' => 'Managed VPS',
    'mega.prod_vps_desc' => 'Virtual servers with full control panel',
    'mega.prod_enterprise' => 'Enterprise VPS',
    'mega.prod_enterprise_desc' => 'High performance for critical projects',
    'mega.prod_dedicado' => 'Dedicated Servers',
    'mega.prod_dedicado_desc' => 'Exclusive hardware on demand',
    'mega.prod_apps' => 'Applications',
    'mega.prod_wordpress' => 'Managed WordPress',
    'mega.prod_wordpress_desc' => 'Optimized WordPress deployment',
    'mega.prod_nodejs' => 'Node.js APIs',
    'mega.prod_nodejs_desc' => 'Ready-to-use Node environments',
    'mega.prod_php' => 'PHP Systems',
    'mega.prod_php_desc' => 'Laravel, Symfony and more',
    'mega.prod_python' => 'Python Apps',
    'mega.prod_python_desc' => 'Django, Flask and automations',
    'mega.prod_deploy' => 'Auto Deploy',
    'mega.prod_deploy_desc' => 'Integrated CI/CD via Git',
    'mega.prod_devops' => 'Dev & Ops',
    'mega.prod_terminal' => 'Web Terminal (SSH)',
    'mega.prod_terminal_desc' => 'Direct access from the browser',
    'mega.prod_monitor' => 'Monitoring',
    'mega.prod_monitor_desc' => 'CPU, RAM, disk in real time',
    'mega.prod_backups' => 'Automatic Backups',
    'mega.prod_backups_desc' => 'Scheduled and on demand',
    'mega.prod_logs' => 'Logs & Metrics',
    'mega.prod_logs_desc' => 'Complete operation history',
    'mega.prod_comm' => 'Communication',
    'mega.prod_email' => 'Professional Email',
    'mega.prod_email_desc' => 'Custom domain with Mailcow',
    'mega.prod_chat' => 'Real-time Chat',
    'mega.prod_chat_desc' => 'Direct support from the panel',
    'mega.prod_tickets' => 'Technical Support',
    'mega.prod_tickets_desc' => 'Tickets and help center',
    'mega.prod_ver_todos' => 'See all products',

    // Mega: Infrastructure
    'mega.infra_como' => 'How it works',
    'mega.infra_como_desc' => 'Architecture and technology',
    'mega.infra_seguranca' => 'Security',
    'mega.infra_seguranca_desc' => '2FA, RBAC, AES-256 encryption',
    'mega.infra_sla' => 'SLA / Uptime',
    'mega.infra_sla_desc' => '99.9% guaranteed availability',
    'mega.infra_dc' => 'Data Centers',
    'mega.infra_dc_desc' => 'Tier III+ infrastructure',

    // Mega: Resources
    'mega.rec_perf' => 'Performance',
    'mega.rec_alta_disp' => 'High availability',
    'mega.rec_balanceamento' => 'Load balancing',
    'mega.rec_seg' => 'Security',
    'mega.rec_isolamento' => 'Container isolation',
    'mega.rec_ddos' => 'DDoS Protection',
    'mega.rec_backups' => 'Automatic backups',
    'mega.rec_monit' => 'Monitoring',
    'mega.rec_status' => 'Real-time status',
    'mega.rec_metricas' => 'CPU/RAM/Disk metrics',
    'mega.rec_alertas' => 'Alerts',
    'mega.rec_exp' => 'Experience',
    'mega.rec_painel' => 'Intuitive panel',
    'mega.rec_deploy' => 'Easy deploy',
    'mega.rec_cli' => 'Web Terminal',

    // ── Solution pages (landing pages) ──
    // Shared
    'sol.section_beneficios' => 'Why choose LRV?',
    'sol.section_como_funciona' => 'A structured process designed for stability',
    'sol.section_faq' => 'Frequently asked questions',
    'sol.section_prova' => 'Companies that already trust LRV',
    'sol.passo1' => 'Create your account',
    'sol.passo1_desc' => 'A straightforward registration process, with no bureaucracy. Your account is ready in under a minute.',
    'sol.passo2' => 'We prepare your environment',
    'sol.passo2_desc' => 'Our team configures the infrastructure according to your business needs, ensuring stability from day one.',
    'sol.passo3' => 'Focus on your business',
    'sol.passo3_desc' => 'While we take care of the infrastructure, your team can concentrate on what truly drives growth.',
    'sol.cta_planos' => 'See plans',
    'sol.cta_contato' => 'Talk to a specialist',
    'sol.cta_final_titulo' => 'Bring more stability and predictability to your operation',
    'sol.cta_final_desc' => 'Choose the plan that fits your needs or talk to our team. No commitment required.',
    'sol.depoimento1_nome' => 'Ricardo Mendes',
    'sol.depoimento1_cargo' => 'CEO, TechStart',
    'sol.depoimento1_texto' => 'We migrated our entire operation to LRV and the impact was immediate. Response times dropped, availability increased, and our team stopped worrying about infrastructure.',
    'sol.depoimento2_nome' => 'Camila Ferreira',
    'sol.depoimento2_cargo' => 'IT Director, Pixel Agency',
    'sol.depoimento2_texto' => 'What sets LRV apart is the quality of support. Issues are resolved in minutes, with clear communication and no runaround. It makes a real difference in our daily operations.',
    'sol.depoimento3_nome' => 'Andre Oliveira',
    'sol.depoimento3_cargo' => 'CTO, SaaS Express',
    'sol.depoimento3_texto' => 'We needed infrastructure that could keep up with our growth without adding complexity. LRV delivered exactly that, with predictability and reliability.',

    // VPS
    'sol.vps_titulo' => 'Stable, managed infrastructure for businesses that cannot afford downtime',
    'sol.vps_subtitulo' => 'Dedicated servers configured, monitored, and protected around the clock so your team can focus on what matters.',
    'sol.vps_cta' => 'Get started',
    'sol.vps_problema_titulo' => 'Infrastructure issues that directly impact your operation',
    'sol.vps_problema_desc' => 'Many businesses still face instability, slow performance, and inadequate support. These are problems that directly affect operations, customer experience, and ultimately revenue. If your current provider cannot guarantee availability and fast response times, the cost of inaction grows every day.',
    'sol.vps_solucao_titulo' => 'Complete management so you can focus on growth',
    'sol.vps_solucao_desc' => 'At LRV, we handle the entire technical layer. From initial setup to ongoing monitoring, your servers are configured, protected, and optimized by our team. You get the performance and stability your business needs, without the operational burden.',
    'sol.vps_b1_titulo' => 'High performance',
    'sol.vps_b1_desc' => 'Optimized infrastructure to keep your systems fast even during peak demand.',
    'sol.vps_b2_titulo' => 'Continuous availability',
    'sol.vps_b2_desc' => 'An environment built to keep your operation online with maximum stability and 99.9% uptime.',
    'sol.vps_b3_titulo' => 'Specialized support',
    'sol.vps_b3_desc' => 'A dedicated team that understands your environment and resolves issues with speed and precision.',
    'sol.vps_b4_titulo' => 'Automated backups',
    'sol.vps_b4_desc' => 'Daily backups with one-click restore, ensuring your data is always protected and recoverable.',
    'sol.vps_b5_titulo' => 'Proactive monitoring',
    'sol.vps_b5_desc' => 'We identify and address potential issues before they impact your operation.',
    'sol.vps_b6_titulo' => 'Seamless scalability',
    'sol.vps_b6_desc' => 'Increase resources as your business grows, with no downtime and no complex migrations.',
    'sol.vps_faq1_p' => 'Do I need technical knowledge to manage the server?',
    'sol.vps_faq1_r' => 'No. Our team handles all configuration, maintenance, and monitoring. You interact through an intuitive panel designed for simplicity.',
    'sol.vps_faq2_p' => 'Do you assist with migration from another provider?',
    'sol.vps_faq2_r' => 'Yes. We handle the complete migration of your sites and systems at no additional cost, ensuring a smooth transition with minimal downtime.',
    'sol.vps_faq3_p' => 'What happens if my business grows significantly?',
    'sol.vps_faq3_r' => 'You can scale resources at any time directly from the panel, with no downtime. Our infrastructure is designed to grow alongside your business.',
    'sol.vps_faq4_p' => 'Is there a minimum contract period?',
    'sol.vps_faq4_r' => 'No. There are no penalties or lock-in periods. You can cancel at any time with full flexibility.',

    // Applications
    'sol.apps_titulo' => 'Launch your project in minutes, not days',
    'sol.apps_subtitulo' => 'From WordPress to custom web applications. Deploy with a single click and start operating immediately.',
    'sol.apps_cta' => 'See available applications',
    'sol.apps_problema_titulo' => 'Deploying an application should not require a dedicated team',
    'sol.apps_problema_desc' => 'Server configuration, dependency management, environment setup. These tasks consume valuable time and require specialized knowledge that diverts focus from your core business. For many companies, the technical barrier between an idea and a live product is still too high.',
    'sol.apps_solucao_titulo' => 'Simplified deployment with enterprise-grade reliability',
    'sol.apps_solucao_desc' => 'Our application catalog allows you to deploy WordPress, web systems, and custom projects with a single click. The environment is pre-configured, optimized, and ready for production, with no manual setup required.',
    'sol.apps_b1_titulo' => 'One-click deployment',
    'sol.apps_b1_desc' => 'Select your application and it is deployed automatically with the correct configuration.',
    'sol.apps_b2_titulo' => 'Automatic updates',
    'sol.apps_b2_desc' => 'Your applications stay current and secure without manual intervention.',
    'sol.apps_b3_titulo' => 'Continuous delivery',
    'sol.apps_b3_desc' => 'Push your code and it goes live automatically through integrated CI/CD.',
    'sol.apps_b4_titulo' => 'Broad compatibility',
    'sol.apps_b4_desc' => 'WordPress, e-commerce, APIs, internal systems, and more. All on a single platform.',
    'sol.apps_b5_titulo' => 'No technical expertise required',
    'sol.apps_b5_desc' => 'Designed for business teams that need results without operational complexity.',
    'sol.apps_b6_titulo' => 'Included support',
    'sol.apps_b6_desc' => 'Our team is available to assist with deployment, configuration, and troubleshooting.',
    'sol.apps_faq1_p' => 'Do I need programming knowledge?',
    'sol.apps_faq1_r' => 'No. Catalog applications are installed automatically. For custom projects, our team can assist with the initial setup.',
    'sol.apps_faq2_p' => 'Can I deploy my own custom application?',
    'sol.apps_faq2_r' => 'Yes. In addition to the catalog, you can deploy any project using Git integration with automated builds.',
    'sol.apps_faq3_p' => 'What kind of support is available?',
    'sol.apps_faq3_r' => 'We offer support via live chat, tickets, and email. Our team is trained to help with both platform and application-level issues.',
    'sol.apps_faq4_p' => 'Is there a limit on the number of applications?',
    'sol.apps_faq4_r' => 'It depends on your plan, but all plans support multiple applications running simultaneously.',

    // Dev & Ops
    'sol.devops_titulo' => 'Complete operational control without unnecessary complexity',
    'sol.devops_subtitulo' => 'Manage, monitor, and automate your infrastructure from a single, intuitive panel.',
    'sol.devops_cta' => 'Explore the tools',
    'sol.devops_problema_titulo' => 'Infrastructure management should not consume your team\'s time',
    'sol.devops_problema_desc' => 'Accessing servers via command line, reviewing logs manually, discovering issues only after they impact users. These operational patterns consume time, increase risk, and prevent your team from focusing on strategic work.',
    'sol.devops_solucao_titulo' => 'Everything accessible from your browser, everything under control',
    'sol.devops_solucao_desc' => 'With LRV, you access terminals, monitor resources in real time, and receive intelligent alerts directly from the panel. No software to install, no complex configurations. A structured approach to ensure security and stability from the start.',
    'sol.devops_b1_titulo' => 'Browser-based access',
    'sol.devops_b1_desc' => 'Manage your servers from anywhere, with no software installation required.',
    'sol.devops_b2_titulo' => 'Real-time monitoring',
    'sol.devops_b2_desc' => 'Full visibility into CPU, memory, and disk usage across all your servers.',
    'sol.devops_b3_titulo' => 'Automated backups',
    'sol.devops_b3_desc' => 'Scheduled and on-demand backups with one-click restore capability.',
    'sol.devops_b4_titulo' => 'Intelligent alerts',
    'sol.devops_b4_desc' => 'Proactive notifications that warn you before issues affect your operation.',
    'sol.devops_b5_titulo' => 'Complete audit trail',
    'sol.devops_b5_desc' => 'Full history of every action taken, when it occurred, and by whom.',
    'sol.devops_b6_titulo' => 'Automated deployment',
    'sol.devops_b6_desc' => 'Update your systems with a simple code push through integrated CI/CD.',
    'sol.devops_faq1_p' => 'Do I need to install any software?',
    'sol.devops_faq1_r' => 'No. The entire platform runs in your browser. You can manage your infrastructure from any device with internet access.',
    'sol.devops_faq2_p' => 'Can I monitor my servers in real time?',
    'sol.devops_faq2_r' => 'Yes. The panel displays resource usage, service status, and live alerts, giving you complete visibility into your environment.',
    'sol.devops_faq3_p' => 'What happens if something goes wrong?',
    'sol.devops_faq3_r' => 'You receive automatic alerts and can restore backups with a single click. Our team is also available to assist with incident resolution.',
    'sol.devops_faq4_p' => 'Can my team members have their own access?',
    'sol.devops_faq4_r' => 'Yes. You can create individual accounts with granular permissions, ensuring each team member has access only to what they need.',

    // Email
    'sol.email_titulo' => 'Professional email that reinforces your brand in every message',
    'sol.email_subtitulo' => 'Email @yourcompany.com ready to use. Convey credibility and professionalism in every interaction.',
    'sol.email_cta' => 'Create my professional email',
    'sol.email_problema_titulo' => 'Free email addresses undermine your business credibility',
    'sol.email_problema_desc' => 'Emails sent from @gmail or @hotmail addresses project an amateur image that your clients and partners notice. In a competitive market, perception matters. Your competitors already communicate with their own domain, reinforcing trust and authority in every message.',
    'sol.email_solucao_titulo' => 'Professional communication that builds trust',
    'sol.email_solucao_desc' => 'With email @yourcompany.com, every message reinforces your brand identity. Setup is straightforward, management is simple, and the result is a more professional image that inspires confidence in your clients.',
    'sol.email_b1_titulo' => 'Your domain, your identity',
    'sol.email_b1_desc' => 'Every email sent carries your company name, reinforcing brand recognition.',
    'sol.email_b2_titulo' => 'Access from any device',
    'sol.email_b2_desc' => 'Works seamlessly on browsers, smartphones, and desktop email clients.',
    'sol.email_b3_titulo' => 'Advanced spam filtering',
    'sol.email_b3_desc' => 'Intelligent filters keep your inbox clean and productive.',
    'sol.email_b4_titulo' => 'Universal compatibility',
    'sol.email_b4_desc' => 'Full compatibility with Outlook, Gmail, Apple Mail, and any standard email client.',
    'sol.email_b5_titulo' => 'Simple management',
    'sol.email_b5_desc' => 'Create, modify, and remove accounts directly from the panel without technical knowledge.',
    'sol.email_b6_titulo' => 'Secure and reliable',
    'sol.email_b6_desc' => 'Your communications protected with encryption and automated backups.',
    'sol.email_faq1_p' => 'Do I need to already have a domain?',
    'sol.email_faq1_r' => 'Yes, a domain is required. If you do not have one yet, our team can guide you through the registration process.',
    'sol.email_faq2_p' => 'Can I access my email on mobile devices?',
    'sol.email_faq2_r' => 'Yes. It works with any email application on smartphones and tablets, as well as through webmail in any browser.',
    'sol.email_faq3_p' => 'How many email accounts can I create?',
    'sol.email_faq3_r' => 'The number of accounts depends on your plan. All plans support multiple accounts to accommodate your team.',
    'sol.email_faq4_p' => 'Do you handle the initial setup?',
    'sol.email_faq4_r' => 'Yes. Our team assists with the complete configuration, including DNS records and client setup.',

    // Security
    'sol.seg_titulo' => 'Comprehensive protection for your business, around the clock',
    'sol.seg_subtitulo' => 'Enterprise-grade security built into every layer of your infrastructure. Protection that works automatically so you can operate with confidence.',
    'sol.seg_cta' => 'Protect my business',
    'sol.seg_problema_titulo' => 'A security incident can cost far more than prevention',
    'sol.seg_problema_desc' => 'Data breaches, service outages, lost customers. A single security incident can cause significant financial losses and destroy the trust that took years to build. For businesses that depend on their digital presence, security is not optional.',
    'sol.seg_solucao_titulo' => 'Professional-grade protection without requiring specialized expertise',
    'sol.seg_solucao_desc' => 'At LRV, security is built in from the start. Your data is isolated, encrypted, and continuously monitored. Every layer of protection is configured and maintained by our team, so you benefit from enterprise-level security without the complexity.',
    'sol.seg_b1_titulo' => 'Isolated environments',
    'sol.seg_b1_desc' => 'Your data and applications run in isolated containers, completely separated from other clients.',
    'sol.seg_b2_titulo' => 'Two-factor authentication',
    'sol.seg_b2_desc' => 'An additional layer of verification that protects your account even if credentials are compromised.',
    'sol.seg_b3_titulo' => 'Granular access control',
    'sol.seg_b3_desc' => 'Define precisely what each team member can view and modify within your account.',
    'sol.seg_b4_titulo' => 'Data encryption',
    'sol.seg_b4_desc' => 'Sensitive information protected with bank-grade AES-256 encryption at rest and in transit.',
    'sol.seg_b5_titulo' => 'Complete audit trail',
    'sol.seg_b5_desc' => 'Detailed logs of every action taken in your account, providing full traceability and accountability.',
    'sol.seg_b6_titulo' => 'Automated threat protection',
    'sol.seg_b6_desc' => 'Active defenses that detect and block the most common attack vectors automatically.',
    'sol.seg_faq1_p' => 'Do I need to configure security settings manually?',
    'sol.seg_faq1_r' => 'No. All security measures are configured and active from day one. Our team continuously monitors and updates protections as new threats emerge.',
    'sol.seg_faq2_p' => 'How is my data protected?',
    'sol.seg_faq2_r' => 'We use AES-256 encryption, container isolation, and automated backups. Your data is protected at every layer of the infrastructure.',
    'sol.seg_faq3_p' => 'What happens if someone attempts to breach my account?',
    'sol.seg_faq3_r' => 'Our automated defense systems detect and block intrusion attempts in real time. You are notified of any suspicious activity, and our team is available to assist with incident response.',
    'sol.seg_faq4_p' => 'Can I control who has access to my account?',
    'sol.seg_faq4_r' => 'Yes. You can create individual accounts with granular role-based permissions, ensuring each team member has access only to the resources they need.',

    // ── Public Footer ──
    'footer.desc' => 'Managed cloud infrastructure. VPS, deploy, email, backups and support in a single panel.',
    'footer.produto' => 'Product',
    'footer.funcionalidades' => 'Features',
    'footer.planos' => 'Plans',
    'footer.changelog' => 'Changelog',
    'footer.status' => 'Status',
    'footer.suporte' => 'Support',
    'footer.contato' => 'Contact',
    'footer.central_ajuda' => 'Help Center',
    'footer.tickets' => 'Tickets',
    'footer.legal' => 'Legal',
    'footer.termos' => 'Terms of Use',
    'footer.privacidade' => 'Privacy',
    'footer.licenca' => 'License',
    'footer.sistemas_op' => 'All systems operational',
    'footer.cookies' => 'Cookies',

    // ── Cookies / Consent ──
    'cookies.titulo' => 'We use cookies',
    'cookies.descricao' => 'This site uses cookies to improve your browsing experience. You can accept all, reject optional cookies, or configure your preferences.',
    'cookies.saiba_mais' => 'Learn more',
    'cookies.aceitar_todos' => 'Accept all',
    'cookies.rejeitar_opcionais' => 'Reject optional',
    'cookies.configurar' => 'Configure',
    'cookies.config_titulo' => 'Cookie preferences',
    'cookies.config_desc' => 'Choose which cookie categories you want to allow. Necessary cookies are always active to ensure the system works properly.',
    'cookies.cat_necessarios' => 'Necessary',
    'cookies.cat_necessarios_desc' => 'Essential for authentication, session, and security. Cannot be disabled.',
    'cookies.cat_analytics' => 'Analytics',
    'cookies.cat_analytics_desc' => 'Help us understand how the site is used to improve the experience.',
    'cookies.cat_marketing' => 'Marketing',
    'cookies.cat_marketing_desc' => 'Used to display relevant content and measure campaigns.',
    'cookies.cat_preferencias' => 'Preferences',
    'cookies.cat_preferencias_desc' => 'Store settings such as language and chosen theme.',
    'cookies.salvar_prefs' => 'Save preferences',
    'cookies.privacidade_texto' => 'We use cookies to ensure the system works properly, improve the browsing experience, and, when authorized, analyze site usage. You can manage your preferences at any time.',

    // ── Public Status ──
    'status.todos_operacionais' => 'All systems operational',
    'status.degradacao' => 'Partial degradation detected',
    'status.indisponivel' => 'Outage in progress',
    'status.desconhecido' => 'Status unknown',

    // ── General ──
    'geral.erro_interno' => 'Internal error.',
    'geral.rota_nao_encontrada' => 'Route not found.',
    'geral.salvar' => 'Save',
    'geral.cancelar' => 'Cancel',
    'geral.voltar' => 'Back',
    'geral.excluir' => 'Delete',
    'geral.editar' => 'Edit',
    'geral.novo' => 'New',
    'geral.ver' => 'View',
    'geral.fechar' => 'Close',
    'geral.enviar' => 'Send',
    'geral.confirmar' => 'Confirm',
    'geral.sim' => 'Yes',
    'geral.nao' => 'No',
    'geral.ativo' => 'Active',
    'geral.inativo' => 'Inactive',
    'geral.status' => 'Status',
    'geral.acoes' => 'Actions',
    'geral.carregando' => 'Loading...',
    'geral.nenhum_resultado' => 'No results found.',
    'geral.area_cliente' => 'Client area',
    'geral.area_equipe' => 'Admin panel',
    'geral.sair' => 'Sign out',
    'geral.minha_conta' => 'My Account',
    'geral.configuracoes_salvas' => 'Settings saved.',
    'geral.erro_formulario' => 'Please fix the errors below.',
    'geral.processando' => 'Processing...',
    'geral.copyright' => '© %s LRV Web',
    'geral.recolher_menu' => 'Collapse menu',
    'geral.expandir_menu' => 'Expand menu',
    'geral.menu' => 'Menu',

    // ── Auth ──
    'auth.entrar' => 'Sign in',
    'auth.email' => 'Email',
    'auth.senha' => 'Password',
    'auth.esqueci_senha' => 'Forgot password?',
    'auth.criar_conta' => 'Create account',
    'auth.ja_tem_conta' => 'Already have an account?',
    'auth.nao_tem_conta' => "Don't have an account?",
    'auth.nome' => 'Full name',
    'auth.credenciais_invalidas' => 'Invalid email or password.',
    'auth.conta_criada' => 'Account created successfully.',
    'auth.logout_sucesso' => 'You have been signed out.',

    // ── Password reset ──
    'reset.titulo' => 'Reset password',
    'reset.instrucao' => 'Enter your email to receive a reset link.',
    'reset.email_enviado' => 'If the email exists, you will receive a reset link.',
    'reset.nova_senha' => 'New password',
    'reset.confirmar_senha' => 'Confirm new password',
    'reset.senha_alterada' => 'Password changed successfully.',
    'reset.token_invalido' => 'Invalid or expired link.',
    'reset.solicitar' => 'Send link',

    // ── 2FA ──
    '2fa.titulo' => 'Two-factor authentication',
    '2fa.configurar' => 'Set up 2FA',
    '2fa.ativar' => 'Enable',
    '2fa.desativar' => 'Disable',
    '2fa.verificar' => 'Verify',
    '2fa.codigo' => 'Verification code',
    '2fa.instrucao_qr' => 'Scan the QR code with your authenticator app (Google Authenticator, Authy, etc.)',
    '2fa.instrucao_manual' => 'Or enter the key manually:',
    '2fa.ativado' => '2FA enabled successfully.',
    '2fa.desativado' => '2FA disabled.',
    '2fa.codigo_invalido' => 'Invalid code.',
    '2fa.confirme_senha' => 'Confirm your password to disable.',
    '2fa.ja_ativo' => 'Two-factor authentication is already enabled.',
    '2fa.seguranca' => 'Security',

    // ── Client sidebar ──
    'sidebar.painel' => 'Dashboard',
    'sidebar.vps' => 'VPS',
    'sidebar.monitoramento' => 'Monitoring',
    'sidebar.tickets' => 'Tickets',
    'sidebar.chat' => 'Chat',
    'sidebar.emails' => 'Emails',
    'sidebar.aplicacoes' => 'Applications',
    'sidebar.catalogo' => 'Catalog',
    'sidebar.assinaturas' => 'Subscriptions',
    'sidebar.ajuda' => 'Help',
    'sidebar.seguranca' => 'Security',
    'sidebar.planos' => 'Plans',

    // ── Client dashboard ──
    'painel.titulo' => 'Dashboard',
    'painel.bem_vindo' => 'Welcome, %s',
    'painel.total_vps' => 'Total VPS',
    'painel.vps_rodando' => 'VPS running',
    'painel.tickets_abertos' => 'Open tickets',
    'painel.plano_ativo' => 'Active plan',
    'painel.nenhum_plano' => 'No active plan',
    'painel.notificacoes' => 'Notifications',
    'painel.sem_notificacoes' => 'No notifications.',

    // ── VPS ──
    'vps.titulo' => 'My VPS',
    'vps.subtitulo' => 'Virtual servers linked to your account',
    'vps.nenhuma' => 'You have no VPS yet.',
    'vps.terminal' => 'Terminal',
    'vps.status_running' => 'Running',
    'vps.status_stopped' => 'Stopped',
    'vps.status_provisioning' => 'Provisioning',
    'vps.status_suspended' => 'Suspended',
    'vps.status_error' => 'Error',

    // ── Monitoring ──
    'monitoramento.titulo' => 'Monitoring',
    'monitoramento.subtitulo' => 'CPU, RAM and disk metrics for your VPS',
    'monitoramento.cpu' => 'CPU',
    'monitoramento.ram' => 'RAM',
    'monitoramento.disco' => 'Disk',
    'monitoramento.ultima_coleta' => 'Last collection',
    'monitoramento.sem_dados' => 'No monitoring data.',

    // ── Tickets ──
    'tickets.titulo' => 'Support Tickets',
    'tickets.novo' => 'New Ticket',
    'tickets.assunto' => 'Subject',
    'tickets.mensagem' => 'Message',
    'tickets.prioridade' => 'Priority',
    'tickets.departamento' => 'Department',
    'tickets.status' => 'Status',
    'tickets.aberto' => 'Open',
    'tickets.em_andamento' => 'In progress',
    'tickets.aguardando_cliente' => 'Waiting for client',
    'tickets.fechado' => 'Closed',
    'tickets.resolvido' => 'Resolved',
    'tickets.responder' => 'Reply',
    'tickets.nenhum' => 'You have no tickets yet.',
    'tickets.criado' => 'Ticket created successfully.',
    'tickets.prioridade_baixa' => 'Low',
    'tickets.prioridade_media' => 'Medium',
    'tickets.prioridade_alta' => 'High',

    // ── Chat ──
    'chat.titulo' => 'Live Chat',
    'chat.subtitulo' => 'Chat in real time with our team',
    'chat.enviar' => 'Send',
    'chat.digite_mensagem' => 'Type your message...',
    'chat.conectando' => 'Connecting...',
    'chat.conectado' => 'Connected',
    'chat.desconectado' => 'Disconnected',
    'chat.reconectando' => 'Reconnecting...',
    'chat.encerrar' => 'End chat',
    'chat.encerrado' => 'Chat ended.',
    'chat.emoji' => 'Emojis',
    'chat.anexar' => 'Attach file',
    'chat.arquivo_enviado' => 'File sent.',
    'chat.arquivo_grande' => 'File too large (max 5 MB).',
    'chat.widget_titulo' => 'Need help?',
    'chat.widget_abrir' => 'Open chat',

    // ── Emails ──
    'emails.titulo' => 'My Emails',
    'emails.subtitulo' => 'Manage your email accounts',
    'emails.criar' => 'Create email',
    'emails.usuario' => 'Username',
    'emails.dominio' => 'Domain',
    'emails.webmail' => 'Webmail',
    'emails.alterar_senha' => 'Change password',
    'emails.remover' => 'Remove',
    'emails.nenhum' => 'You have no emails yet.',
    'emails.dominios' => 'Email Domains',
    'emails.adicionar_dominio' => 'Add domain',
    'emails.verificar_dns' => 'Verify DNS',
    'emails.instrucoes_dns' => 'DNS Instructions',
    'emails.tutoriais_titulo' => 'Set up in other apps',
    'emails.tutoriais_desc' => 'Use your professional email in Outlook, Gmail, Apple Mail or any email app.',
    'emails.dados_config' => 'Configuration details',
    'emails.porta' => 'Port',
    'emails.usuario_config' => 'Username',
    'emails.seu_email_completo' => 'Your full email address (e.g. contact@yourdomain.com)',
    'emails.senha_definida' => 'The password you set when creating the email',
    'emails.pc_celular' => 'Desktop & Mobile',
    'emails.outlook_1' => 'Open Outlook and go to File > Add Account',
    'emails.outlook_2' => 'Select "Manual setup" and choose IMAP',
    'emails.outlook_3' => 'Fill in the server details from the table above',
    'emails.outlook_4' => 'IMAP: port <code>993</code> with SSL/TLS — SMTP: port <code>587</code> with STARTTLS',
    'emails.outlook_5' => 'Click Connect and wait for verification',
    'emails.outlook_mobile' => 'On mobile: download the Outlook app, tap Add Account and use the same details.',
    'emails.gmail_1' => 'In Gmail, click the gear icon > See all settings',
    'emails.gmail_2' => 'Go to "Accounts and Import" > "Add a mail account"',
    'emails.gmail_3' => 'Enter your professional email and select "Import via POP3" or "IMAP"',
    'emails.gmail_4' => 'IMAP server: port <code>993</code> SSL — SMTP server: port <code>587</code> TLS',
    'emails.gmail_5' => 'Confirm and Gmail will sync your emails',
    'emails.gmail_mobile' => 'On mobile: open Gmail app > Add account > Other > use the same IMAP/SMTP details.',
    'emails.apple_1' => 'Go to Settings > Mail > Accounts > Add Account > Other',
    'emails.apple_2' => 'Tap "Add Mail Account"',
    'emails.apple_3' => 'Fill in name, email and password',
    'emails.apple_4' => 'Incoming server: port <code>993</code> SSL — Outgoing server: port <code>587</code> TLS',
    'emails.apple_5' => 'Save and wait for verification',
    'emails.thunder_1' => 'Open Thunderbird and go to Account Settings > Actions > Add Mail Account',
    'emails.thunder_2' => 'Enter your name, email and password',
    'emails.thunder_3' => 'Thunderbird may auto-detect settings. If not, click "Manual config" and use the details from the table above',
    'emails.thunder_4' => 'Click Done',
    'emails.cota' => 'Storage quota',
    'emails.cota_usada' => 'Used',
    'emails.cota_total' => 'Total',
    'emails.cota_disponivel' => 'Available',
    'emails.cota_hint' => 'Storage reserved for this mailbox. Select GB for larger values.',
    'emails.ativar_webmail' => 'Enable custom webmail',
    'emails.verificar_webmail' => 'Verify webmail',
    'emails.webmail_ativado' => 'Custom webmail enabled successfully!',
    'emails.webmail_personalizado_hint' => 'Access webmail via webmail.yourdomain.com',

    // ── Applications ──
    'apps.titulo' => 'My Applications',
    'apps.subtitulo' => 'Apps installed on your VPS',
    'apps.catalogo' => 'Application Catalog',
    'apps.catalogo_subtitulo' => 'Install ready-to-use apps with 1 click on your VPS',
    'apps.instalar' => 'Install',
    'apps.instalando' => 'Installing...',
    'apps.instalacao_iniciada' => 'Installation started!',
    'apps.nenhuma' => 'You have no applications yet.',
    'apps.vps_necessaria' => 'You need an active VPS to install applications.',
    'apps.voltar_painel' => 'Back to dashboard',
    'apps.minhas_apps' => '← My applications',
    'apps.roundcube_aviso' => 'Roundcube will be installed on your VPS and will consume resources (CPU, RAM, disk). Once installed, the default webmail will be replaced by Roundcube for your domains.',
    'apps.catalogo_btn' => '📦 Catalog — Install new',
    'apps.selecione_vps' => 'VPS',
    'apps.dominio' => 'Domain',
    'apps.repositorio' => 'Git Repository',
    'apps.variaveis_env' => 'Environment variables (JSON)',
    'apps.status_installing' => 'Installing',
    'apps.status_running' => 'Running',
    'apps.status_stopped' => 'Stopped',
    'apps.status_error' => 'Error',
    'apps.status_inactive' => 'Inactive',
    'apps.status_deploying' => 'Deploying',
    'apps.tipo' => 'Type',
    'apps.porta' => 'Port',
    'apps.aplicacao' => 'Application',

    // ── Subscriptions ──
    'assinaturas.titulo' => 'My Subscriptions',
    'assinaturas.subtitulo' => 'Billing and payment history',
    'assinaturas.nenhuma' => 'No subscriptions found.',
    'assinaturas.solicitar_reembolso' => 'Request refund',
    'assinaturas.plano' => 'Plan',
    'assinaturas.valor' => 'Amount',
    'assinaturas.vencimento' => 'Due date',

    // ── Plans ──
    'planos.titulo' => 'Available Plans',
    'planos.subtitulo' => 'Choose the right plan for you',
    'planos.assinar' => 'Subscribe',
    'planos.atual' => 'Current plan',
    'planos.mensal' => '/month',

    // ── My Account ──
    'conta.titulo' => 'My Account',
    'conta.subtitulo' => 'Manage your personal data and password',
    'conta.dados_pessoais' => 'Personal information',
    'conta.alterar_senha' => 'Change password',
    'conta.senha_atual' => 'Current password',
    'conta.nova_senha' => 'New password',
    'conta.confirmar_senha' => 'Confirm new password',
    'conta.endereco' => 'Address',
    'conta.rua' => 'Street',
    'conta.numero' => 'Number',
    'conta.complemento' => 'Complement',
    'conta.cidade' => 'City',
    'conta.estado' => 'State',
    'conta.cep' => 'ZIP code',
    'conta.pais' => 'Country',
    'conta.salvo' => 'Data saved successfully.',

    // ── Status ──
    'status.titulo' => 'Service Status',
    'status.operacional' => 'Operational',
    'status.degradado' => 'Degraded',
    'status.fora' => 'Down',
    'status.incidentes' => 'Incidents',

    // ── Help ──
    'ajuda.titulo' => 'Help Center',
    'ajuda.subtitulo' => 'Frequently asked questions',
    'ajuda.nao_encontrou' => "Didn't find what you were looking for?",
    'ajuda.chat_vivo' => 'Live chat',
    'ajuda.abrir_ticket' => 'Open ticket',
    'ajuda.fale_conosco' => 'Contact us',

    // ── Rating ──
    'avaliacao.titulo' => 'Rating',
    'avaliacao.como_foi' => 'How was your experience?',
    'avaliacao.comentario' => 'Comment (optional)',
    'avaliacao.enviar' => 'Submit rating',
    'avaliacao.obrigado' => 'Thank you for your feedback!',

    // ── Onboarding ──
    'onboarding.titulo' => 'Welcome to the system!',
    'onboarding.passo1' => 'Explore your dashboard',
    'onboarding.passo2' => 'Set up your VPS',
    'onboarding.passo3' => 'Install applications',
    'onboarding.passo4' => 'Need help?',
    'onboarding.concluir' => 'Done',

    // ── Public pages ──
    'pub.termos' => 'Terms of Service',
    'pub.privacidade' => 'Privacy Policy',
    'pub.licenca' => 'License',
    'pub.changelog' => 'Changelog',
    'pub.contato' => 'Contact',
    'pub.status' => 'Status',

    // ── Home / Landing ──
    'home.titulo' => 'Cloud Infrastructure',
    'home.subtitulo' => 'High-performance VPS servers with full management.',
    'home.comecar' => 'Get started',
    'home.ver_planos' => 'View plans',
    'home.trial_cta' => 'Try for free',
    'home.nav_sobre' => 'About',
    'home.nav_planos' => 'Plans',
    'home.nav_condicoes' => 'Terms',
    'home.nav_devs' => 'For devs',
    'home.nav_entrar' => 'Sign in',
    'home.nav_contratar' => 'Get Started',
    'home.ver_planos_precos' => 'View Plans & Pricing',
    'home.saiba_mais' => 'Learn more',
    'home.footer_produto' => 'Product',
    'home.footer_suporte' => 'Support',
    'home.footer_legal' => 'Legal',
    'home.footer_todos_operacionais' => 'All systems operational',

    // ── App categories ──
    'cat.cms' => 'CMS',
    'cat.backend' => 'Backend',
    'cat.database' => 'Database',
    'cat.webserver' => 'Web Server',
    'cat.dev' => 'Development',
    'cat.email' => 'Email',
    'cat.other' => 'Other',

    // ── Team ──
    'equipe.painel' => 'Dashboard',
    'equipe.clientes' => 'Clients',
    'equipe.usuarios' => 'Users',
    'equipe.servidores' => 'Servers',
    'equipe.vps' => 'VPS',
    'equipe.aplicacoes' => 'Applications',
    'equipe.tickets' => 'Tickets',
    'equipe.chat' => 'Chat — Support',
    'equipe.chat_flows' => 'Chat Flows',
    'equipe.emails' => 'Emails',
    'equipe.monitoramento' => 'Monitoring',
    'equipe.status' => 'Status',
    'equipe.planos' => 'Plans',
    'equipe.assinaturas' => 'Subscriptions',
    'equipe.backups' => 'Backups',
    'equipe.jobs' => 'Jobs',
    'equipe.terminal' => 'Terminal',
    'equipe.erros' => 'Errors',
    'equipe.configuracoes' => 'Settings',
    'equipe.permissoes' => 'Permissions',
    'equipe.satisfacao' => 'Satisfaction',
    'equipe.ajuda' => 'Help',
    'equipe.inicializacao' => 'Setup',
    'equipe.notificacoes' => 'Notifications',
    'equipe.operacoes' => 'Operations',

    // ── 2FA verify ──
    '2fa.titulo_verificacao' => 'Two-factor verification',
    '2fa.desc_verificacao' => 'Your account is protected with two-factor authentication. Enter the code generated by your authenticator app to continue.',
    '2fa.validade_30s' => 'Code valid for 30 seconds',
    '2fa.use_app' => 'Use Google Authenticator, Authy or similar',
    '2fa.nao_compartilhe' => 'Never share your code with anyone',
    '2fa.codigo_autenticador' => 'Authenticator code',
    '2fa.abra_app' => 'Open your authenticator app and enter the 6-digit code displayed for this account.',
    '2fa.verificar_entrar' => 'Verify and sign in',
    '2fa.voltar_login' => '← Back to login',

    // ── VPS Terminal ──
    'terminal.titulo' => 'Terminal VPS #%s',
    'terminal.subtitulo' => 'Isolated session inside the container',
    'terminal.abrir_sessao' => 'Open session',
    'terminal.auditado' => 'Everything is audited. Access is restricted to your VPS container.',
    'terminal.conectar' => 'Connect',
    'terminal.vps_nao_rodando' => 'VPS is not running (status=%s). The terminal will be available when it is running.',
    'terminal.upload' => '↑ Upload',
    'terminal.download' => '↓ Download',
    'terminal.desconectado' => 'Disconnected',
    'terminal.enviar_arquivo' => 'Send file to VPS',
    'terminal.arquivo' => 'File',
    'terminal.caminho_remoto' => 'Remote path',
    'terminal.baixar_arquivo' => 'Download file from VPS',
    'terminal.baixar' => 'Download',
    'terminal.conexao_proxy' => 'Connection via reverse proxy: /ws/terminal (WSS).',

    // ── Monitoring detail ──
    'monitoramento.titulo_vps' => 'Monitoring — VPS #%s',
    'monitoramento.servidor' => 'Server',
    'monitoramento.ip' => 'IP',
    'monitoramento.coletas' => 'Collections',
    'monitoramento.cpu_agora' => 'CPU now',
    'monitoramento.ram_agora' => 'RAM now',
    'monitoramento.disco_agora' => 'Disk now',
    'monitoramento.atualizacao_auto' => 'Auto-refresh every 30s. Last:',
    'monitoramento.agora' => 'now',
    'monitoramento.historico' => 'History',
    'monitoramento.data_hora' => 'Date/Time',
    'monitoramento.sem_metricas' => 'No metrics yet.',
    'monitoramento.sem_node' => 'This VPS does not have an associated node for monitoring yet.',

    // ── Client status ──
    'status.suas_vps' => 'Your VPS',
    'status.disponibilidade' => 'Availability of your VPS',
    'status.uptime_24h' => 'Uptime (24h)',
    'status.historico' => 'History',
    'status.ultima_checagem' => 'Last check',
    'status.sem_dados' => 'No data yet.',
    'status.desconhecido' => 'Unknown',
    'status.indisponivel' => 'Unavailable',
    'status.monitorando' => 'Monitoring',
    'status.identificado' => 'Identified',
    'status.investigando' => 'Investigating',
    'status.critico' => 'Critical',
    'status.alto' => 'High',
    'status.baixo' => 'Low',
    'status.inicio' => 'Started',
    'status.resolvido_em' => 'Resolved',
    'status.servicos_afetados' => 'Affected services',
    'status.atualizacoes' => 'Updates',
    'status.nenhum_incidente' => 'No recent incidents.',

    // ── Subscriptions ──
    'assinaturas.cobrancas' => 'Charges / Invoices',
    'assinaturas.id' => 'ID',
    'assinaturas.tipo' => 'Type',
    'assinaturas.link' => 'Link',
    'assinaturas.ver_fatura' => 'View invoice',
    'assinaturas.nenhuma_ainda' => 'No subscriptions yet',
    'assinaturas.escolha_plano' => 'Choose a plan to get started.',
    'assinaturas.ver_planos' => 'View available plans',
    'assinaturas.prox_vencimento' => 'Next due date',
    'assinaturas.motivo' => 'Reason',
    'assinaturas.motivo_placeholder' => 'Describe the reason for your request...',
    'assinaturas.enviar_solicitacao' => 'Submit request',
    'assinaturas.planos_cobrancas' => 'Plans, charges and refunds',
    'assinaturas.mes' => 'mo',

    // ── Help (FAQ) ──
    'ajuda.perguntas_frequentes' => 'Frequently asked questions',
    'ajuda.versao' => 'FAQ — v%s',
    'ajuda.secao_vps' => '🖥️ VPS',
    'ajuda.secao_email' => '📧 Email',
    'ajuda.secao_chat' => '💬 Chat & Support',
    'ajuda.secao_apps' => '📦 Applications',
    'ajuda.secao_conta' => '🔐 Account',

    // ── Team header ──
    'header.buscar' => 'Search...',
    'header.notificacoes' => 'Notifications',
    'header.seguranca_2fa' => 'Security / 2FA',

    // ── Chat widget ──
    'widget.suporte' => 'Support',
    'widget.como_ajudar' => 'How can we help?',
    'widget.fechar' => 'Close',
    'widget.abrir_suporte' => 'Open support',
    'widget.voltar' => '← Back',
    'widget.ola' => 'Hello! I am the virtual assistant. How can I help you today?',
    'widget.tirar_duvida' => '💬 Ask a question',
    'widget.falar_atendente' => '🧑‍💻 Talk to an agent',
    'widget.abrir_ticket' => '🎫 Open a ticket',
    'widget.enviar_email' => '📧 Send an email',
    'widget.conectando' => 'Connecting...',
    'widget.online' => '● Online',
    'widget.chat_encerrado' => '● Chat ended',

    // ── Team — Dashboard ──
    'eq_painel.titulo' => 'Dashboard',
    'eq_painel.subtitulo' => 'Welcome back, %s.',
    'eq_painel.vps_ativas' => 'Active VPS',
    'eq_painel.de_total' => 'of %s total',
    'eq_painel.clientes' => 'Clients',
    'eq_painel.cadastrados' => 'registered',
    'eq_painel.tickets_abertos' => 'Open Tickets',
    'eq_painel.aguardando_resposta' => 'awaiting reply',
    'eq_painel.jobs_pendentes' => 'Pending Jobs',
    'eq_painel.na_fila' => 'in queue',
    'eq_painel.nodes_online' => 'Nodes Online',
    'eq_painel.servidores_ativos' => 'active servers',
    'eq_painel.receita_mensal' => 'Monthly Revenue',
    'eq_painel.assinaturas_ativas' => 'active subscriptions',
    'eq_painel.acoes_rapidas' => 'Quick actions',
    'eq_painel.gerenciar_vps' => 'Manage VPS',
    'eq_painel.ver_tickets' => 'View tickets',
    'eq_painel.seu_acesso' => 'Your access',
    'eq_painel.seguranca' => 'Security',
    'eq_painel.permissoes' => 'Permissions',
    'eq_painel.chat_vivo' => 'Live chat',
    'eq_painel.inicializacao' => 'Setup',

    // ── Team — Sign in ──
    'eq_entrar.titulo_painel' => 'Team admin panel',
    'eq_entrar.desc_painel' => 'Restricted access. Use your team member credentials to sign in to the control panel.',
    'eq_entrar.2fa_disponivel' => 'Two-factor authentication (2FA) available',
    'eq_entrar.controle_acesso' => 'Role-based access control and permissions',
    'eq_entrar.auditoria' => 'Full action audit trail',
    'eq_entrar.sessao_expira' => 'Session with automatic expiration',
    'eq_entrar.area_cliente' => 'Client area →',
    'eq_entrar.acesso_equipe' => 'Team access',
    'eq_entrar.desc_acesso' => 'Use your email and password to access the admin panel.',
    'eq_entrar.sessao_expirada' => 'Your session expired due to inactivity. Please sign in again.',
    'eq_entrar.entrar_painel' => 'Sign in to panel',
    'eq_entrar.voltar_inicio' => '← Back to home',

    // ── Team — Tickets ──
    'eq_tickets.titulo' => 'Tickets',
    'eq_tickets.subtitulo' => 'Support and history',
    'eq_tickets.buscar' => 'Search subject or client...',
    'eq_tickets.todos_status' => 'All statuses',
    'eq_tickets.todas_prioridades' => 'All priorities',
    'eq_tickets.todos_departamentos' => 'All departments',
    'eq_tickets.filtrar' => 'Filter',
    'eq_tickets.limpar' => 'Clear',
    'eq_tickets.cliente' => 'Client',
    'eq_tickets.assunto' => 'Subject',
    'eq_tickets.dept' => 'Dept.',
    'eq_tickets.prioridade' => 'Priority',
    'eq_tickets.atribuido' => 'Assigned',
    'eq_tickets.atualizado' => 'Updated',
    'eq_tickets.abrir' => 'Open',
    'eq_tickets.nenhum' => 'No tickets found.',
    'eq_tickets.aberto' => 'Open',
    'eq_tickets.em_andamento' => 'In progress',
    'eq_tickets.aguard_cliente' => 'Waiting client',
    'eq_tickets.fechado' => 'Closed',
    'eq_tickets.alta' => 'High',
    'eq_tickets.media' => 'Medium',
    'eq_tickets.baixa' => 'Low',

    // ── Team — Servers ──
    'eq_servidores.titulo' => 'Servers',
    'eq_servidores.subtitulo' => 'Cluster nodes and available capacity',
    'eq_servidores.cadastre' => 'Register your nodes and total capacity.',
    'eq_servidores.novo' => 'New server',
    'eq_servidores.hostname' => 'Hostname',
    'eq_servidores.cpu' => 'CPU',
    'eq_servidores.memoria' => 'Memory',
    'eq_servidores.armazenamento' => 'Storage',
    'eq_servidores.setup' => 'Setup',
    'eq_servidores.ativo' => 'Active',
    'eq_servidores.manutencao' => 'Maintenance',
    'eq_servidores.inativo' => 'Inactive',
    'eq_servidores.online' => 'Online',
    'eq_servidores.offline' => 'Offline',
    'eq_servidores.pronto' => 'Ready',
    'eq_servidores.inicializando' => 'Initializing…',
    'eq_servidores.erro' => 'Error',
    'eq_servidores.pendente' => 'Pending',
    'eq_servidores.editar' => 'Edit',
    'eq_servidores.continuar_setup' => 'Continue setup',
    'eq_servidores.reiniciar' => 'Restart',
    'eq_servidores.inicializar' => 'Initialize',
    'eq_servidores.re_inicializar' => 'Re-initialize',
    'eq_servidores.nenhum' => 'No servers registered yet.',
    'eq_servidores.modal_titulo' => 'Initialize server',
    'eq_servidores.modal_desc' => 'Connects via SSH and prepares the server automatically: Docker, lrv-net network and terminal user.',
    'eq_servidores.aguardando_inicio' => 'Waiting to start…',
    'eq_servidores.inicializar_agora' => 'Initialize now',
    'eq_servidores.modo_continuar' => 'Mode: continue from where it stopped.',
    'eq_servidores.clique_retomar' => 'Click the button to resume.',
    'eq_servidores.clique_iniciar' => 'Click "Initialize now" to begin.',
    'eq_servidores.servidor_pronto' => 'Server ready. Status updated to Active/Online.',
    'eq_servidores.setup_erros' => 'Setup completed with errors. Fix and use "Continue from where it stopped".',
    'eq_servidores.erro_comunicacao' => 'Communication error',
    'eq_servidores.etapas' => 'steps',
    'eq_servidores.retomando' => 'Resuming',
    'eq_servidores.iniciando' => 'Starting',

    // ── Team — My Account ──
    'eq_conta.titulo' => 'My Account',
    'eq_conta.subtitulo' => 'Manage your personal information and password',
    'eq_conta.info_pessoais' => 'Personal information',
    'eq_conta.foto_perfil' => 'Profile photo',
    'eq_conta.escolher_foto' => 'Choose photo',
    'eq_conta.nenhum_arquivo' => 'No file selected',
    'eq_conta.nome' => 'Name',
    'eq_conta.alterar_senha' => 'Change password',
    'eq_conta.hint_senha' => '(leave blank to keep current)',
    'eq_conta.senha_atual' => 'Current password',
    'eq_conta.nova_senha' => 'New password',
    'eq_conta.salvar' => 'Save changes',
    'eq_conta.hint_avatar' => 'PNG, JPG, WEBP · max 2 MB',

    // ── Team — Satisfaction ──
    'eq_satisfacao.titulo' => 'Support Satisfaction',
    'eq_satisfacao.subtitulo' => 'Ratings from closed tickets and chats',
    'eq_satisfacao.media_geral' => 'Overall average',
    'eq_satisfacao.total_avaliacoes' => 'Total ratings',
    'eq_satisfacao.distribuicao' => 'Rating distribution',
    'eq_satisfacao.por_agente' => 'By agent',
    'eq_satisfacao.agente' => 'Agent',
    'eq_satisfacao.avaliacoes' => 'Ratings',
    'eq_satisfacao.media' => 'Average',
    'eq_satisfacao.positivas' => 'Positive (≥4)',
    'eq_satisfacao.ultimas' => 'Latest ratings',
    'eq_satisfacao.nenhuma' => 'No ratings recorded yet.',
    'eq_satisfacao.data' => 'Date',
    'eq_satisfacao.tipo' => 'Type',
    'eq_satisfacao.cliente' => 'Client',
    'eq_satisfacao.nota' => 'Rating',
    'eq_satisfacao.comentario' => 'Comment',
    'eq_satisfacao.muito_ruim' => 'Very bad',
    'eq_satisfacao.ruim' => 'Bad',
    'eq_satisfacao.regular' => 'Average',
    'eq_satisfacao.bom' => 'Good',
    'eq_satisfacao.excelente' => 'Excellent',

    // ── Team — Jobs ──
    'eq_jobs.titulo' => 'Jobs',
    'eq_jobs.subtitulo' => 'Queue and logs (last 200)',
    'eq_jobs.id' => 'ID',
    'eq_jobs.tipo' => 'Type',
    'eq_jobs.criado' => 'Created',
    'eq_jobs.atualizado' => 'Updated',
    'eq_jobs.concluido' => 'Completed',
    'eq_jobs.falhou' => 'Failed',
    'eq_jobs.rodando' => 'Running',
    'eq_jobs.pendente' => 'Pending',
    'eq_jobs.nenhum' => 'No jobs found.',
    'eq_jobs.dica' => 'Tip: run <strong>php worker.php</strong> to process the queue.',

    // ── Team — Errors ──
    'eq_erros.titulo' => 'System Errors',
    'eq_erros.subtitulo' => 'HTTP errors, exceptions and captured failures log',
    'eq_erros.total' => 'total',
    'eq_erros.pendentes' => 'pending',
    'eq_erros.codigo_http' => 'HTTP Code',
    'eq_erros.todos' => 'All',
    'eq_erros.tipo' => 'Type',
    'eq_erros.filtrar' => 'Filter',
    'eq_erros.limpar' => 'Clear',
    'eq_erros.limpar_resolvidos' => 'Clear resolved',
    'eq_erros.nenhum' => 'No errors found.',
    'eq_erros.codigo' => 'Code',
    'eq_erros.url' => 'URL',
    'eq_erros.mensagem' => 'Message',
    'eq_erros.ip' => 'IP',
    'eq_erros.data' => 'Date',
    'eq_erros.resolvido' => 'Resolved',
    'eq_erros.pendente' => 'Pending',
    'eq_erros.encontrados' => '%s error(s) found',
    'eq_erros.confirmar_limpar' => 'Delete all errors marked as resolved?',

    // ── Team — VPS ──
    'eq_vps.titulo' => 'VPS',
    'eq_vps.subtitulo' => 'Provisioning, status and actions',
    'eq_vps.cliente' => 'Client',
    'eq_vps.cpu_ram_disco' => 'CPU / RAM / Disk',
    'eq_vps.status' => 'Status',
    'eq_vps.acoes' => 'Actions',
    'eq_vps.node' => 'Node',
    'eq_vps.provisionar' => 'Provision',
    'eq_vps.reativar' => 'Reactivate',
    'eq_vps.reiniciar' => 'Restart',
    'eq_vps.suspender' => 'Suspend',
    'eq_vps.remover' => 'Remove',
    'eq_vps.confirmar_remover' => 'Remove VPS #%s?',
    'eq_vps.nenhuma' => 'No VPS found.',
    'eq_vps.em_execucao' => 'Running',
    'eq_vps.suspensa' => 'Suspended',
    'eq_vps.aguard_pagamento' => 'Awaiting payment',
    'eq_vps.aguard_node' => 'Awaiting node',
    'eq_vps.prov_pendente' => 'Prov. pending',
    'eq_vps.provisionando' => 'Provisioning',
    'eq_vps.erro' => 'Error',
    'eq_vps.removida' => 'Removed',

    // ── Team — Applications ──
    'eq_apps.titulo' => 'Applications',
    'eq_apps.subtitulo' => 'Apps linked to VPS and reserved ports',
    'eq_apps.desc' => 'Create applications and reserve unique ports to expose services.',
    'eq_apps.nova' => 'New application',
    'eq_apps.cliente' => 'Client',
    'eq_apps.tipo' => 'Type',
    'eq_apps.dominio' => 'Domain',
    'eq_apps.porta' => 'Port',
    'eq_apps.status' => 'Status',
    'eq_apps.acoes' => 'Actions',
    'eq_apps.nenhuma' => 'No applications found.',
    'eq_apps.confirmar_deploy' => 'Start deploy now?',
    'eq_apps.ativa' => 'Active',
    'eq_apps.inativa' => 'Inactive',
    'eq_apps.deploy' => 'Deploy',
    'eq_apps.erro' => 'Error',
    'eq_apps.catalogo' => 'Template catalog',
    'eq_apps.catalogo_desc' => 'Templates available for one-click install by clients.',
    'eq_apps.requer_dominio' => 'Domain',
    'eq_apps.requer_repo' => 'Repository',

    // ── Team — Plans ──
    'eq_planos.backup_slots' => 'Included backups',
    'eq_planos.sem_backup' => 'No backup',

    // ── Team — Emails ──
    'eq_emails.titulo' => 'Emails',
    'eq_emails.subtitulo' => 'Email accounts and domains registered by clients',
    'eq_emails.abrir_webmail' => '🌐 Open Webmail',
    'eq_emails.buscar' => 'Search email or client...',
    'eq_emails.contas' => 'Email accounts',
    'eq_emails.nenhuma_conta' => 'No accounts found.',
    'eq_emails.quota' => 'Quota',
    'eq_emails.criado_em' => 'Created at',
    'eq_emails.remover' => 'Remove',
    'eq_emails.confirmar_remover_email' => 'Remove this email account?',
    'eq_emails.dominios_custom' => 'Custom domains',
    'eq_emails.nenhum_dominio' => 'No domains registered.',
    'eq_emails.dominio' => 'Domain',
    'eq_emails.cadastrado_em' => 'Registered at',
    'eq_emails.confirmar_remover_dominio' => 'Remove this domain?',
    'eq_emails.operacao_sucesso' => 'Operation completed successfully.',
    'eq_emails.aguard_dns' => 'Awaiting DNS',

    // ── Team — Status ──
    'eq_status.titulo' => 'Status',
    'eq_status.subtitulo' => 'Dashboard and incidents',
    'eq_status.servicos_coletados' => 'Collected services',
    'eq_status.key' => 'Key',
    'eq_status.nome' => 'Name',
    'eq_status.scope' => 'Scope',
    'eq_status.cliente' => 'Client',
    'eq_status.node' => 'Node',
    'eq_status.ultima_checagem' => 'Last check',
    'eq_status.sem_dados' => 'No data yet. Start collection in Setup.',
    'eq_status.criar_incidente' => 'Create incident',
    'eq_status.titulo_incidente' => 'Title',
    'eq_status.impacto' => 'Impact',
    'eq_status.servicos_ids' => 'Services (IDs)',
    'eq_status.mensagem' => 'Message',
    'eq_status.descreva' => 'Describe the incident...',
    'eq_status.criar' => 'Create incident',
    'eq_status.incidentes' => 'Incidents',
    'eq_status.nenhum_incidente' => 'No incidents.',
    'eq_status.inicio' => 'Started',
    'eq_status.resolvido' => 'Resolved',
    'eq_status.servicos_afetados' => 'Affected services',
    'eq_status.salvar_servicos' => 'Save services',
    'eq_status.adicionar_update' => 'Add update',
    'eq_status.atualizacao_incidente' => 'Incident update...',
    'eq_status.ultimas_atualizacoes' => 'Latest updates',
    'eq_status.publico' => 'Public',
    'eq_status.interno' => 'Internal',
    'eq_status.operacional' => 'Operational',
    'eq_status.degradado' => 'Degraded',
    'eq_status.indisponivel' => 'Unavailable',
    'eq_status.desconhecido' => 'Unknown',
    'eq_status.investigando' => 'Investigating',
    'eq_status.identificado' => 'Identified',
    'eq_status.monitorando' => 'Monitoring',
    'eq_status.critico' => 'Critical',
    'eq_status.alto' => 'High',
    'eq_status.baixo' => 'Low',

    // ── Team — 2FA Setup ──
    'eq_2fa.titulo' => 'Two-factor authentication',
    'eq_2fa.subtitulo' => 'Protect your account with TOTP (Google Authenticator, Authy, etc.)',
    'eq_2fa.ativado' => '2FA enabled',
    'eq_2fa.conta_protegida' => 'Your account is protected with two-factor authentication.',
    'eq_2fa.desativar' => 'Disable 2FA',
    'eq_2fa.desc_desativar' => 'To disable, confirm with your authenticator code.',
    'eq_2fa.codigo_autenticador' => 'Authenticator code',
    'eq_2fa.configurar' => 'Set up authenticator',
    'eq_2fa.desc_configurar' => 'Scan the QR code with your authenticator app or enter the key manually.',
    'eq_2fa.chave_secreta' => 'Secret key (manual)',
    'eq_2fa.desc_app' => 'Use Google Authenticator, Authy, Bitwarden or any TOTP-compatible app.',
    'eq_2fa.codigo_confirmar' => 'Authenticator code to confirm',
    'eq_2fa.ativar' => 'Enable 2FA',

    // ── Team — 2FA Verify ──
    'eq_2fa_verificar.titulo' => 'Two-factor verification',
    'eq_2fa_verificar.desc' => 'Your account is protected with two-factor authentication. Enter the code generated by your authenticator app to continue.',
    'eq_2fa_verificar.codigo_verificacao' => 'Verification code',
    'eq_2fa_verificar.desc_codigo' => 'Open your authenticator app and enter the 6-digit code displayed for this account.',
    'eq_2fa_verificar.verificar_entrar' => 'Verify and sign in',
    'eq_2fa_verificar.voltar_login' => '← Back to login',
    'eq_2fa_verificar.validade_30s' => 'Code valid for 30 seconds',
    'eq_2fa_verificar.use_app' => 'Use Google Authenticator, Authy or similar',
    'eq_2fa_verificar.nao_compartilhe' => 'Never share your code with anyone',

    // ── Team — Settings ──
    'eq_config.titulo' => 'Settings',
    'eq_config.subtitulo' => 'Payments, webhooks, alerts and branding',
    'eq_config.desc_banco' => 'Everything here is saved in the database (<strong>settings</strong> table). We do not use <strong>.env</strong> files.',
    'eq_config.salvas' => 'Settings saved.',
    'eq_config.geral' => 'General',
    'eq_config.url_base' => 'Public application base URL',
    'eq_config.email_admin' => 'Admin email for alerts',
    'eq_config.secret_key' => 'Application secret key (app.secret_key)',
    'eq_config.gerar_chave' => 'Generate',
    'eq_config.hint_secret_key' => 'Used to encrypt SSH passwords in the database. Required to save servers with password authentication. Do not change after setup.',
    'eq_config.identidade_visual' => 'Branding',
    'eq_config.nome_sistema' => 'System name',
    'eq_config.nome_empresa' => 'Company name',
    'eq_config.url_logo' => 'Logo URL',
    'eq_config.url_favicon' => 'Favicon URL',
    'eq_config.copyright_footer' => 'Copyright text (footer)',
    'eq_config.paginas_legais' => 'Legal Pages',
    'eq_config.desc_legais' => 'HTML allowed. Accessible at',
    'eq_config.trial' => 'Free Trial',
    'eq_config.trial_desc' => 'When active, new clients receive a test server upon account creation.',
    'eq_config.trial_ativo' => 'Trial active',
    'eq_config.duracao_dias' => 'Duration (days)',
    'eq_config.label_cta' => 'CTA button label',
    'eq_config.desc_trial' => 'Trial description (shown on home page)',
    'eq_config.seo' => 'SEO & Indexing',
    'eq_config.seo_desc' => 'Settings for Google and other search engines to properly index the public site.',
    'eq_config.salvar' => 'Save',

    // ── Team chat ──
    'chat_equipe.titulo' => 'Chat — Support',
    'chat_equipe.subtitulo' => 'Manage support conversations',
    'chat_equipe.abertos' => 'Open chats',
    'chat_equipe.encerrados' => 'Closed chats',
    'chat_equipe.atender' => 'Attend',
    'chat_equipe.nenhum_aberto' => 'No open chats at the moment.',
    'chat_equipe.nenhum_encerrado' => 'No closed chats.',
    'chat_equipe.cliente' => 'Client',
    'chat_equipe.agente' => 'Agent',
    'chat_equipe.iniciado_em' => 'Started at',
    'chat_equipe.encerrado_em' => 'Closed at',
    'chat_equipe.sem_agente' => 'No agent',
    'chat_equipe.msgs' => 'Msgs',
    'chat_equipe.aberto_em' => 'Opened at',
    'chat_equipe.ultima_ativ' => 'Last activity',

    // ── Team — Ticket detail ──
    'eq_ticket.mensagens' => 'Messages',
    'eq_ticket.nenhuma_msg' => 'No messages yet.',
    'eq_ticket.responder' => 'Reply',
    'eq_ticket.sua_resposta' => 'Your reply...',
    'eq_ticket.anexo' => 'Attachment (optional, max 5 MB)',
    'eq_ticket.enviar_resposta' => 'Send reply',
    'eq_ticket.acoes' => 'Actions',
    'eq_ticket.alterar_status' => 'Change status',
    'eq_ticket.atribuir_para' => 'Assign to',
    'eq_ticket.ninguem' => 'Nobody',
    'eq_ticket.atribuir' => 'Assign',
    'eq_ticket.ticket_fechado' => 'Ticket closed.',
    'eq_ticket.nenhuma_acao' => 'No actions available.',
    'eq_ticket.equipe' => 'Team',
    'eq_ticket.atualizado' => 'Updated',
    'eq_ticket.atribuido_a' => 'Assigned to',
    'eq_ticket.anexo_label' => 'Attachment',

    // ── Home — Body ──
    'home.badge_trial' => 'Free trial for %s days available',
    'home.badge_servidores' => 'Servers available now',
    'home.hero_titulo' => 'VPS Infrastructure to',
    'home.hero_titulo_em' => 'scale your business',
    'home.hero_subtitulo' => 'VPS servers with dedicated resources, native DDoS protection, 99.9%% uptime and technical support — activation within 6 business days.',
    'home.servidor_destaque' => 'Featured server',
    'home.processamento' => 'Processing',
    'home.infra_dedicada' => 'Dedicated',
    'home.total_mensal' => 'Monthly total (server + backup)',
    'home.ddos_protection' => 'DDoS Protection',
    'home.ddos_ativada' => 'Enabled by default',
    'home.uptime_sla' => 'Guaranteed SLA',
    'home.empresas_confiam' => 'Companies that trust %s',
    'home.stats_experiencia' => 'Experience in the infrastructure market',
    'home.stats_clientes' => 'Active clients across Brazil',
    'home.stats_sla' => 'Contractual uptime SLA guaranteed',
    'home.stats_ativacao' => 'Fast server activation',
    'home.porque' => 'Why %s?',
    'home.melhor_infra' => 'The best infrastructure in Brazil',
    'home.sobre_desc' => '%s specializes in dedicated servers, web hosting and digital infrastructure. Cutting-edge technology with humanized support, transparent costs and real scalability.',
    'home.sobre_desc2' => 'Our infrastructure supports enterprise systems, databases, file storage and business continuity solutions across Brazil.',
    'home.sobre_desc3' => 'Predictable adjustment based on IGPM · Activation within 6 business days · Unlimited traffic included',
    'home.feat_desempenho' => 'Superior Performance',
    'home.feat_desempenho_desc' => 'Latest generation Intel Xeon processors for maximum throughput and minimum latency.',
    'home.feat_ddos' => 'Native DDoS Protection',
    'home.feat_ddos_desc' => 'Infrastructure shielded against volumetric attacks. Included in all plans.',
    'home.feat_conectividade' => 'Hyperconnectivity',
    'home.feat_conectividade_desc' => '1 to 10 Gbps ports with unlimited traffic. Inside the DC connectivity hub.',
    'home.feat_upgrades' => 'Hassle-free Upgrades',
    'home.feat_upgrades_desc' => 'Scale resources quickly. Adjust CPU, RAM and storage on demand.',
    'home.feat_hardware' => 'Exclusive Hardware',
    'home.feat_hardware_desc' => 'Full control of the dedicated server. No sharing, no noisy neighbors.',
    'home.feat_custos' => 'Transparent Costs',
    'home.feat_custos_desc' => 'Clear pricing, no hidden fees. Annual adjustment by IGPM, always predictable.',

    // ── Home — Differentials ──
    'home.diff_titulo' => 'Dedicated Server Differentials %s',
    'home.diff_conectividade' => 'Connectivity',
    'home.diff_conectividade_desc' => 'Direct connection with major networks like Akamai, CloudFlare, Microsoft, Google, AWS and UPX. Reach through the largest national peerings at IX.br. Transit through multiple carriers operating in Brazil and worldwide.',
    'home.diff_kvm' => 'Console/KVM',
    'home.diff_kvm_desc' => 'Intuitive panel providing external server access (display, keyboard and mouse), ISO mounting on virtual drive, power on/off and restart, among other options.',
    'home.diff_resiliencia' => 'Resilience',
    'home.diff_resiliencia_desc' => 'Servers with abundant resources for sustained high-demand usage or unexpected peaks, with no changes in response speed.',
    'home.diff_io' => 'I/O Performance',
    'home.diff_io_desc' => 'Ultra-low latency in read and write operations, even during peak loads such as complex databases or high-volume email servers.',
    'home.diff_rede' => 'Network-level Security',
    'home.diff_rede_desc' => 'Private VLAN for internal traffic, VPN for secure office integration, dedicated firewall for proper security rules and point-to-point link to connect offices (additional services).',
    'home.diff_backup' => 'Daily Backup',
    'home.diff_backup_desc' => 'Your data stored in an external, failure-proof environment. Full security against improper deletion, database corruption, ransomware, and more (additional service).',

    // ── Home — Plans ──
    'home.plans_titulo' => 'Choose the ideal plan for your project',
    'home.plans_sub' => 'VPS servers with dedicated and scalable resources. All plans include DDoS protection and free SSL.',
    'home.plans_comparar' => 'Compare all plans',
    'home.plans_moeda' => '$',
    'home.plans_por_mes' => 'per month',
    'home.plans_ddos' => 'DDoS Protection',
    'home.plans_ssl' => 'Free SSL',
    'home.plans_suporte' => 'Specialized support',
    'home.plans_addons' => 'Additional services',
    'home.plans_total' => 'Total amount',
    'home.plans_empty' => 'Plans coming soon.',
    'home.plans_empty_contato' => 'Contact us',
    'home.plans_empty_saber' => 'to learn more.',
    'home.plans_help_titulo' => 'Need help deciding or more resources?',
    'home.plans_help_sub' => 'Talk to us for a custom plan',
    'home.plans_help_btn' => 'Talk to a Specialist',

    // ── Home — Conditions ──
    'home.cond_eyebrow' => 'Full transparency',
    'home.cond_titulo' => 'General Service Conditions',
    'home.cond_sub' => 'Everything you need to know before hiring. No fine print, no invoice surprises.',
    'home.cond_01' => 'All prices include applicable <strong>taxes as required by law</strong>.',
    'home.cond_02' => '<strong>Prepaid</strong> services. Billing starts after activation. First prorated invoice due in <strong>5 days</strong>.',
    'home.cond_03' => 'Monthly invoices sent <strong>15 days in advance</strong>, payment exclusively by bank slip.',
    'home.cond_04' => 'Annual adjustment based on <strong>IGPM</strong> at the end of each 12-month period.',
    'home.cond_05' => '<strong>Automatic renewal</strong> for equal periods if not contested <strong>60 days</strong> in advance.',
    'home.cond_06' => 'Early termination: penalty of <strong>50%% of monthly value × remaining months</strong> agreed in the proposal.',
    'home.cond_07' => '<strong>SP1 activation time</strong>: 1 server = 6 business days. PR1/CE1 regions: +5 additional business days.',
    'home.cond_08' => '<strong>BaaS Backup</strong> activated within 4 additional business days after server provisioning.',
    'home.cond_09' => 'Cancellation or downgrade must be <strong>communicated 60 days</strong> before suspension.',
    'home.cond_10' => 'Game hosting is <strong>strictly prohibited</strong> to ensure connectivity performance.',

    // ── Home — Testimonials ──
    'home.dep_eyebrow' => 'Testimonials',
    'home.dep_titulo' => 'What our clients say',
    'home.dep_1' => '%s gave us full support when we faced a critical incident. At the time we had all our data center on-premise, and now our entire infrastructure is with them. Our partnership is over 2 years and we plan to continue for a long time. We are very happy with the service provided.',
    'home.dep_2' => '%s is the main technology provider for Akahosting. We built a partnership and in less than a year we saw extreme success in our operation. Thanks to them our company was able to greatly boost business. We are grateful for the support on all occasions.',
    'home.dep_3' => 'We used to work with server providers outside Brazil, we met %s and brought all our infrastructure here. We have been with them for a few years and our joint evolution is constant. We are very satisfied and plan to extend this partnership more and more.',
    'home.dep_4' => 'The migration to %s was decisive for our operation. The process was transparent, the technical team always available and performance exceeded our expectations. With the dedicated server we reduced latency and increased capacity without increasing costs.',

    // ── Home — CTA Final ──
    'home.cta_pronto' => 'Ready to get started?',
    'home.cta_trial_titulo' => 'Start your free trial',
    'home.cta_trial_titulo_em' => 'right now',
    'home.cta_trial_sub' => 'Create your account and try the platform for free for %s days, no credit card required.',
    'home.cta_falar_equipe' => 'Talk to the team',
    'home.cta_ative_titulo' => 'Activate your server in',
    'home.cta_ative_titulo_em' => 'up to 6 business days',
    'home.cta_ative_sub' => 'Contact us now and receive a custom proposal. Our technical team is ready to assist you.',
    'home.cta_proposta' => 'Request Proposal by Email',
    'home.cta_consultor' => 'Talk to a Consultant',

    // ── Home — Footer ──
    'home.footer_desc' => 'High-performance cloud infrastructure with DDoS protection, automatic backups and specialized support.',
    'home.footer_sobre' => 'About',
    'home.footer_planos' => 'Plans',
    'home.footer_condicoes' => 'Terms',
    'home.footer_devs' => 'For devs',
    'home.footer_contato' => 'Contact',
    'home.footer_status' => 'System status',
    'home.footer_tickets' => 'Tickets',
    'home.footer_ajuda' => 'Help center',
    'home.footer_termos' => 'Terms of use',
    'home.footer_privacidade' => 'Privacy',
    'home.footer_sistema_op' => 'All systems operational',
    'home.hero_preco_mes' => '/mo',
    'home.stats_num_exp' => '+5 years',
    'home.stats_num_clientes' => '+200',
    'home.stats_num_sla' => '99.9%',
    'home.stats_num_ativacao' => '6 days',
    'home.clients_logos' => 'Startups,E-commerce,SaaS,Agencies,Developers',

    // ── Team — Chat detail ──
    'eq_chat_ver.aberto' => 'Open',
    'eq_chat_ver.encerrado' => 'Closed',
    'eq_chat_ver.encerrar' => 'End chat',
    'eq_chat_ver.confirmar_encerrar' => 'End this chat?',
    'eq_chat_ver.chat_encerrado' => 'This chat has been closed.',
    'eq_chat_ver.enviar' => 'Send',
    'eq_chat_ver.placeholder' => 'Type your message...',
    'eq_chat_ver.carregando' => 'Loading messages...',
    'eq_chat_ver.cancelar_arquivo' => 'Cancel file',
    'eq_chat_ver.emojis' => 'Emojis',
    'eq_chat_ver.enviar_arquivo' => 'Send file',
    'eq_chat_ver.cliente_label' => 'Client',
    'eq_chat_ver.nome' => 'Name',
    'eq_chat_ver.email' => 'Email',
    'eq_chat_ver.cadastro' => 'Registered',
    'eq_chat_ver.ver_perfil' => 'View full profile',
    'eq_chat_ver.nao_encontrado' => 'Client not found.',
    'eq_chat_ver.assinaturas' => 'Subscriptions',
    'eq_chat_ver.plano' => 'Plan',
    'eq_chat_ver.nenhuma_assinatura' => 'No subscriptions.',
    'eq_chat_ver.vps' => 'VPS',
    'eq_chat_ver.nenhuma_vps' => 'No VPS.',
    'eq_chat_ver.tickets_recentes' => 'Recent tickets',
    'eq_chat_ver.nenhum_ticket' => 'No tickets.',

    // ── Team — Server edit ──
    'eq_srv_edit.titulo_novo' => 'New server',
    'eq_srv_edit.titulo_editar' => 'Edit server',
    'eq_srv_edit.conectividade' => 'Connectivity',
    'eq_srv_edit.acoes' => 'Actions',
    'eq_srv_edit.testar_ssh' => 'Test SSH connection',
    'eq_srv_edit.continuar_setup' => 'Continue setup',
    'eq_srv_edit.re_inicializar' => 'Re-initialize',
    'eq_srv_edit.inicializar' => 'Initialize server',
    'eq_srv_edit.hostname' => 'Hostname',
    'eq_srv_edit.status' => 'Status',
    'eq_srv_edit.ativo' => 'Active',
    'eq_srv_edit.manutencao' => 'Maintenance',
    'eq_srv_edit.inativo' => 'Inactive',
    'eq_srv_edit.ip' => 'IP Address',
    'eq_srv_edit.porta_ssh' => 'SSH Port',
    'eq_srv_edit.auth_ssh' => 'SSH Authentication',
    'eq_srv_edit.usuario_senha' => 'Username and password',
    'eq_srv_edit.chave_ssh' => 'SSH Key',
    'eq_srv_edit.usuario_ssh' => 'SSH User',
    'eq_srv_edit.senha_ssh' => 'SSH Password',
    'eq_srv_edit.manter_branco' => '(leave blank to keep current)',
    'eq_srv_edit.id_chave' => 'SSH key identifier',
    'eq_srv_edit.hint_chave' => 'File name inside the directory configured in',
    'eq_srv_edit.upload_chave' => 'SSH private key (upload)',
    'eq_srv_edit.hint_upload_chave' => 'Upload the private key file (.pem, id_rsa, etc). The file will be saved in the system key directory.',
    'eq_srv_edit.hint_substituir_chave' => 'Upload a new file to replace the current key.',
    'eq_srv_edit.chave_configurada' => 'Key configured',
    'eq_srv_edit.upload_chave_terminal' => 'Terminal private key (upload)',
    'eq_srv_edit.hint_upload_terminal' => 'Upload the secure terminal private key. Leave blank to disable.',
    'eq_srv_edit.usar_sudo' => 'Use sudo',
    'eq_srv_edit.hint_sudo' => 'Check if the SSH user is not root and needs sudo to install packages.',
    'eq_srv_edit.senha_sudo' => 'Sudo password',
    'eq_srv_edit.hint_sudo_branco' => '(leave blank to use the same SSH password)',
    'eq_srv_edit.hint_nopasswd' => 'If sudo does not require a password (NOPASSWD), leave blank as well.',
    'eq_srv_edit.terminal_seguro' => 'Secure terminal (clients)',
    'eq_srv_edit.terminal_desc' => 'Client terminal sessions via',
    'eq_srv_edit.usuario_terminal' => 'Terminal SSH user',
    'eq_srv_edit.chave_terminal' => 'Terminal key identifier',
    'eq_srv_edit.hint_terminal' => 'Leave blank to disable secure terminal on this node.',
    'eq_srv_edit.passo_a_passo' => 'Step-by-step on node',
    'eq_srv_edit.cpu_total' => 'Total CPU (vCPUs)',
    'eq_srv_edit.ram_total' => 'Total memory (MB)',
    'eq_srv_edit.storage_total' => 'Total storage (MB)',
    'eq_srv_edit.salvar' => 'Save server',

    // ── Team — Terminal ──
    'eq_terminal.titulo' => 'Terminal (Admin)',
    'eq_terminal.subtitulo' => 'SSH access to node via WebSocket',
    'eq_terminal.subtitulo_http' => 'SSH access to node via HTTP — no WebSocket required',
    'eq_terminal.escolha_node' => 'Choose a node and connect. Everything is audited.',
    'eq_terminal.node' => 'Node',
    'eq_terminal.selecione' => 'Select...',
    'eq_terminal.conectar' => 'Connect',
    'eq_terminal.desconectado' => 'Disconnected',
    'eq_terminal.conectado_http' => 'Connected (HTTP)',
    'eq_terminal.executando' => 'Running...',
    'eq_terminal.sessao_iniciada' => 'Session started. Each command is executed via SSH.',
    'eq_terminal.dica_http' => 'Tip: use "cd /path && command" to run in another directory.',
    'eq_terminal.selecione_node' => 'Select a node first.',
    'eq_terminal.nao_conectado' => 'Not connected.',
    'eq_terminal.inativo' => 'inactive',
    'eq_terminal.preencha_upload' => 'Select a file and enter the path.',
    'eq_terminal.enviando' => 'Sending...',
    'eq_terminal.http_hint' => 'Each command is executed individually via SSH. For interactive commands, configure WebSocket.',
    'eq_terminal.upload' => 'Upload',
    'eq_terminal.download' => 'Download',
    'eq_terminal.enviar_arquivo' => 'Send file to server',
    'eq_terminal.arquivo' => 'File',
    'eq_terminal.caminho_remoto' => 'Remote path',
    'eq_terminal.enviar' => 'Send',
    'eq_terminal.cancelar' => 'Cancel',
    'eq_terminal.baixar_arquivo' => 'Download file from server',
    'eq_terminal.baixar' => 'Download',
    'eq_terminal.placeholder' => 'Type a command and press Enter',
    'eq_terminal.proxy_hint' => 'Connection via reverse proxy:',

    // ── Team — Client detail ──
    'eq_cliente.clientes' => 'Clients',
    'eq_cliente.editar_dados' => 'Edit data',
    'eq_cliente.dados_cadastrais' => 'Registration data',
    'eq_cliente.telefone' => 'Phone',
    'eq_cliente.celular' => 'Mobile',
    'eq_cliente.cpf_cnpj' => 'Tax ID',
    'eq_cliente.cadastro' => 'Registered',
    'eq_cliente.endereco' => 'Address',
    'eq_cliente.assinar_plano' => 'Assign plan manually',
    'eq_cliente.plano' => 'Plan',
    'eq_cliente.assinar' => 'Assign plan',
    'eq_cliente.vps' => 'VPS',
    'eq_cliente.container' => 'Container',
    'eq_cliente.cpu_ram_disco' => 'CPU / RAM / Disk',
    'eq_cliente.nenhum_vps' => 'No VPS registered.',
    'eq_cliente.assinaturas' => 'Subscriptions',
    'eq_cliente.valor_mes' => 'Amount/month',
    'eq_cliente.prox_vencimento' => 'Next due date',
    'eq_cliente.criada' => 'Created',
    'eq_cliente.nenhuma_assinatura' => 'No subscriptions.',
    'eq_cliente.assinatura_criada' => 'Subscription created successfully.',
    'eq_cliente.ativa' => 'Active',
    'eq_cliente.suspensa' => 'Suspended',
    'eq_cliente.cancelada' => 'Cancelled',
    'eq_cliente.ativo' => 'Active',
    'eq_cliente.parado' => 'Stopped',
    'eq_cliente.suspenso' => 'Suspended',
    'eq_cliente.assinaturas_ativas' => 'active subscription(s)',

    // ── Team — Setup ──
    'eq_init.titulo' => 'Setup wizard',
    'eq_init.subtitulo' => 'Checks and actions to get the server ready',
    'eq_init.erro' => 'Error',
    'eq_init.acao_executada' => 'Action executed.',
    'eq_init.status' => 'Status',
    'eq_init.item' => 'Item',
    'eq_init.detalhe' => 'Detail',
    'eq_init.ok' => 'OK',
    'eq_init.pendente' => 'Pending',
    'eq_init.migrations_pendentes' => 'Pending migrations:',
    'eq_init.acoes' => 'Actions',
    'eq_init.aplicar_schema' => 'Apply schema.sql',
    'eq_init.aplicar_migrations' => 'Apply migrations',
    'eq_init.criar_diretorios' => 'Create directories',
    'eq_init.gerar_tokens' => 'Generate tokens/defaults',
    'eq_init.processar_job' => 'Process 1 job',
    'eq_init.coletar_status' => 'Collect status (1x)',
    'eq_init.enfileirar' => 'Enqueue',
    'eq_init.coleta_continua' => 'Start continuous collection',
    'eq_init.iniciar' => 'Start',
    'eq_init.testar_nodes' => 'Test node connectivity',
    'eq_init.executar' => 'Execute',
    'eq_init.terminal_ws' => 'Terminal WS (Admin)',
    'eq_init.instalar_deps' => 'Install dependencies (composer)',
    'eq_init.iniciar_daemon' => 'Start daemon',
    'eq_init.parar_daemon' => 'Stop daemon',
    'eq_init.nodes_cadastrados' => 'Registered nodes',
    'eq_init.nodes_desc' => 'This list shows the status and last connectivity result (SSH + docker version).',
    'eq_init.host' => 'Host',
    'eq_init.ultima_checagem' => 'Last check',
    'eq_init.ultimo_erro' => 'Last error',
    'eq_init.nenhum_node' => 'No nodes registered yet.',
    'eq_init.worker_http' => 'Worker via HTTP (no CLI)',
    'eq_init.worker_desc' => 'Endpoint to run 1 job (ideal for external cron). Authentication via header',
    'eq_init.testar_worker' => 'Test (run 1 job via HTTP)',
    'eq_init.logs' => 'Logs',
    'eq_init.obs_deploy' => 'Note: for Deploy/Backups the server needs ssh and scp available and PHP with shell_exec enabled.',

    // ── Team — Help ──
    'eq_ajuda.subtitulo' => 'Configuration and operation',

    // ── Infrastructure (public page) ──
    'infra.nav_funcionalidades' => 'Features',
    'infra.nav_planos' => 'Plans',
    'infra.nav_tecnologia' => 'Technology',
    'infra.nav_status' => 'Status',
    'infra.nav_contato' => 'Contact',
    'infra.nav_entrar' => 'Sign in',
    'infra.nav_criar_conta' => 'Create account',
    'infra.hero_eyebrow' => 'Cloud SaaS Platform',
    'infra.hero_titulo' => 'Cloud infrastructure',
    'infra.hero_titulo_grad' => 'simple and powerful',
    'infra.hero_sub' => 'Provision VPS, deploy applications, manage emails, backups and support in a single panel. Fully automated, secure and ready to scale.',
    'infra.hero_criar_conta' => 'Create free account',
    'infra.hero_ver_planos' => 'View plans →',
    'infra.badge_deploy' => 'Automated deploy',
    'infra.badge_backups' => 'Automatic backups',
    'infra.badge_suporte' => 'Support via chat and tickets',
    'infra.badge_monitoramento' => '24/7 monitoring',
    'infra.badge_terminal' => 'Integrated web terminal',
    'infra.stat_uptime' => 'Guaranteed uptime',
    'infra.stat_provisioning' => 'Provisioning',
    'infra.stat_monitoring' => 'Monitoring',
    'infra.stat_encryption' => 'Encryption',
    'infra.feat_label' => 'Features',
    'infra.feat_titulo' => 'Everything you need in one place',
    'infra.feat_sub' => 'From provisioning to support, every feature is designed to simplify your operations.',
    'infra.feat_vps' => 'Managed VPS',
    'infra.feat_vps_desc' => 'Provision, suspend, restart and monitor your VPS with a few clicks.',
    'infra.feat_terminal' => 'Web Terminal',
    'infra.feat_terminal_desc' => 'Access the SSH terminal directly from your browser. Full command auditing.',
    'infra.feat_deploy' => 'Application Deploy',
    'infra.feat_deploy_desc' => 'Deploy Docker applications with one click. Real-time logs and easy rollback.',
    'infra.feat_backups' => 'Automatic Backups',
    'infra.feat_backups_desc' => 'Scheduled backups with direct download. Configurable retention and one-click restore.',
    'infra.feat_monitor' => 'Monitoring',
    'infra.feat_monitor_desc' => 'CPU, memory and disk in real time. Automatic alerts via email and WhatsApp.',
    'infra.feat_email' => 'Professional Emails',
    'infra.feat_email_desc' => 'Create accounts on your own domain. Mailcow integration and webmail included.',
    'infra.feat_suporte' => 'Integrated Support',
    'infra.feat_suporte_desc' => 'Live chat and ticket system with complete support history.',
    'infra.feat_planos' => 'Flexible Plans',
    'infra.feat_planos_desc' => 'Choose the ideal plan for your project. Upgrade or downgrade at any time.',
    'infra.feat_2fa' => '2FA & Security',
    'infra.feat_2fa_desc' => 'Two-factor authentication, role-based RBAC, full auditing and CSRF protection.',
    'infra.steps_label' => 'How it works',
    'infra.steps_titulo' => 'From zero to live in minutes',
    'infra.steps_sub' => 'No complex configurations. Your infrastructure ready for production in 4 steps.',
    'infra.step1_titulo' => 'Create your account',
    'infra.step1_desc' => 'Quick signup, no credit card required to start.',
    'infra.step2_titulo' => 'Choose a plan',
    'infra.step2_desc' => 'Select the resources your project needs.',
    'infra.step3_titulo' => 'VPS provisioned',
    'infra.step3_desc' => 'Your server is created automatically in less than 60 seconds.',
    'infra.step4_titulo' => 'Manage everything',
    'infra.step4_desc' => 'Terminal, deploy, backups, emails and support in a single panel.',
    'infra.plans_label' => 'Plans',
    'infra.plans_titulo' => 'Transparent pricing, no surprises',
    'infra.plans_sub' => 'Choose the ideal plan for your project. All include support, backups and monitoring.',
    'infra.plans_mensal' => 'Billed monthly',
    'infra.plans_anual' => 'Billed annually',
    'infra.plans_backups' => 'Automatic backups',
    'infra.plans_monitor' => '24/7 monitoring',
    'infra.plans_suporte' => 'Support via chat and tickets',
    'infra.plans_comecar' => 'Get started',
    'infra.plans_empty' => 'Plans coming soon.',
    'infra.plans_contato' => 'Contact us',
    'infra.plans_saber_mais' => 'to learn more.',
    'infra.plans_custom' => 'Need something custom?',
    'infra.plans_fale' => 'Talk to the team',
    'infra.plans_popular' => 'Most popular',
    'infra.plans_mes' => '/mo',
    'infra.plans_ano' => '/yr',
    'infra.plans_moeda' => '$',
    'infra.tech_label' => 'Technology',
    'infra.tech_titulo' => 'Modern and reliable stack',
    'infra.tech_sub' => 'Built with the best technologies to ensure performance, security and scalability.',
    'infra.tech_php' => 'PHP 8.3 + Custom MVC',
    'infra.tech_php_desc' => 'Custom MVC framework, no external dependency overhead. Fast and predictable.',
    'infra.tech_mysql' => 'MySQL with prepared statements',
    'infra.tech_mysql_desc' => 'All queries use prepared statements. Zero ORM, full control over the database.',
    'infra.tech_docker' => 'Docker & Remote SSH',
    'infra.tech_docker_desc' => 'Provisioning and deploy via SSH. Docker containers managed directly from the panel.',
    'infra.tech_ws' => 'Real-time WebSocket',
    'infra.tech_ws_desc' => 'Web terminal and live chat via WebSocket. Minimal latency, smooth experience.',
    'infra.tech_sec' => 'Layered Security',
    'infra.tech_sec_desc' => 'CSRF, RBAC, 2FA TOTP, rate limiting, replay attack protection and full auditing.',
    'infra.tech_mail' => 'Integrated Mailcow',
    'infra.tech_mail_desc' => 'Email management via Mailcow API. Custom domains, webmail and automatic DNS.',
    'infra.sec_label' => 'Security',
    'infra.sec_titulo' => 'Your infrastructure protected',
    'infra.sec_sub' => 'Multiple layers of security to protect your data and operations.',
    'infra.sec_2fa' => '2FA Authentication (TOTP)',
    'infra.sec_2fa_desc' => 'Extra protection with two-factor authentication via Google Authenticator or similar.',
    'infra.sec_rbac' => 'Role-based RBAC',
    'infra.sec_rbac_desc' => 'Granular permission control by role: superadmin, admin, devops, dev and support.',
    'infra.sec_csrf' => 'CSRF & Rate Limit Protection',
    'infra.sec_csrf_desc' => 'CSRF tokens on all forms and IP rate limiting to prevent abuse.',
    'infra.sec_audit' => 'Full Auditing',
    'infra.sec_audit_desc' => 'Log of all team and client actions. Full traceability for compliance.',
    'infra.faq_label' => 'FAQ',
    'infra.faq_titulo' => 'Frequently asked questions',
    'infra.faq_sub' => 'Get your questions about the platform answered.',
    'infra.faq1_q' => 'Do I need a credit card to get started?',
    'infra.faq1_a' => 'No. You can create your account and explore the panel for free. A card is only required when subscribing to a paid plan.',
    'infra.faq2_q' => 'How long until my VPS is ready?',
    'infra.faq2_a' => 'Provisioning is automatic and takes less than 60 seconds after payment confirmation.',
    'infra.faq3_q' => 'Can I upgrade or downgrade my plan?',
    'infra.faq3_a' => 'Yes. You can change your plan at any time from the panel. The change is applied immediately.',
    'infra.faq4_q' => 'Are backups automatic?',
    'infra.faq4_a' => 'Yes. Backups are automatically scheduled according to your plan. You can also create manual backups and download them at any time.',
    'infra.faq5_q' => 'How does support work?',
    'infra.faq5_a' => 'Support is provided via live chat and ticket system directly in the panel. Our team responds during business hours.',
    'infra.access_label' => 'Access',
    'infra.access_titulo' => 'Choose your profile',
    'infra.access_sub' => 'Client area or admin panel — each with its own space.',
    'infra.access_cliente' => 'Client area',
    'infra.access_cliente_desc' => 'Access your VPS, applications, emails, backups, monitoring and support.',
    'infra.access_admin' => 'Admin panel',
    'infra.access_admin_desc' => 'Manage clients, servers, billing, tickets and the entire infrastructure.',
    'infra.access_entrar_equipe' => 'Sign in as team',
    'infra.cta_trial' => 'Start your free trial now',
    'infra.cta_pronto' => 'Ready to get started?',
    'infra.cta_sub' => 'Create your account now and have your infrastructure running in minutes.',
    'infra.cta_falar' => 'Talk to the team',
    'infra.footer_desc' => 'Cloud SaaS platform for VPS, application, email and support management.',
    'infra.footer_col_produto' => 'Product',
    'infra.footer_col_suporte' => 'Support',
    'infra.footer_col_legal' => 'Legal',
    'infra.footer_funcionalidades' => 'Features',
    'infra.footer_planos' => 'Plans',
    'infra.footer_tecnologia' => 'Technology',
    'infra.footer_contato' => 'Contact',
    'infra.footer_status' => 'System status',
    'infra.footer_tickets' => 'Tickets',
    'infra.footer_termos' => 'Terms of use',
    'infra.footer_privacidade' => 'Privacy',
    'infra.footer_sistema_op' => 'All systems operational',
    'infra.cta_criar_conta' => 'Create free account',
    'infra.access_entrar' => 'Sign in',

    // ── License (public page) ──
    'licenca.label' => 'Legal',
    'licenca.titulo' => 'Proprietary License',
    'licenca.subtitulo' => 'This document establishes the terms and conditions of use for the LRV Cloud Manager software.',
    'licenca.nav_termos' => 'Terms',
    'licenca.nav_privacidade' => 'Privacy',
    'licenca.nav_contato' => 'Contact',

    // ── Changelog ──
    'changelog.label' => 'Version history',
    'changelog.titulo' => 'Changelog',
    'changelog.sub' => 'Follow all the news, improvements and fixes of the system.',

    // ── Contact ──
    'contato.label' => 'Get in touch',
    'contato.titulo' => 'Contact',
    'contato.sub' => 'Have a question or need help? Send us a message and we will get back to you shortly.',
    'contato.nome' => 'Name',
    'contato.email' => 'Email',
    'contato.assunto' => 'Subject',
    'contato.mensagem' => 'Message',
    'contato.enviar' => 'Send message',
    'contato.ph_nome' => 'Your name',
    'contato.ph_email' => 'you@email.com',
    'contato.ph_assunto' => 'How can we help?',
    'contato.ph_mensagem' => 'Describe your question or request...',

    // ── Status ──
    'status_page.label' => 'Operational transparency',
    'status_page.titulo' => 'System status',
    'status_page.servicos' => 'Services',
    'status_page.auto_refresh' => 'Auto-refresh every 30s',
    'status_page.th_servico' => 'Service',
    'status_page.th_status' => 'Status',
    'status_page.th_uptime' => 'Uptime 24h',
    'status_page.th_historico' => 'History',
    'status_page.th_checagem' => 'Last check',
    'status_page.nenhum_servico' => 'No services configured yet.',
    'status_page.incidentes' => 'Recent incidents',
    'status_page.nenhum_incidente' => 'No recent incidents. Everything is running normally.',
    'status_page.inicio' => 'Started:',
    'status_page.resolvido' => 'Resolved:',
    'status_page.operacional' => 'Operational',
    'status_page.degradado' => 'Degraded',
    'status_page.indisponivel' => 'Unavailable',
    'status_page.desconhecido' => 'Unknown',
    'status_page.resolvido_badge' => 'Resolved',
    'status_page.monitorando' => 'Monitoring',
    'status_page.identificado' => 'Identified',
    'status_page.investigando' => 'Investigating',
    'status_page.critico' => 'Critical',
    'status_page.alto' => 'Major',
    'status_page.baixo' => 'Minor',

    // ── Status Incidentes ──
    'status_inc.nenhum' => 'No incidents recorded.',
    'status_inc.anterior' => '← Previous',
    'status_inc.proxima' => 'Next →',
    'status_inc.pagina' => 'Page %d of %d',
    'status_inc.titulo' => 'Incident history',
    'status_inc.sub' => 'View the complete history of incidents and maintenance.',

    // ── Terms ──
    'termos.label' => 'Legal',
    'termos.titulo' => 'Terms of Use',
    'termos.sub' => 'Please read carefully the terms governing the use of the platform.',
    'termos.vazio' => 'The terms of use have not been configured yet. Please contact the administrator.',

    // ── Privacy ──
    'privacidade.label' => 'Legal',
    'privacidade.titulo' => 'Privacy Policy',
    'privacidade.sub' => 'Learn how we collect, use and protect your data.',
    'privacidade.vazio' => 'The privacy policy has not been configured yet. Please contact the administrator.',

    // ── Stripe Checkout ──
    'stripe.sucesso_titulo' => 'Payment confirmed',
    'stripe.sucesso_sub' => 'Your subscription has been activated successfully.',
    'stripe.erro_tentar' => 'Try again',
    'stripe.detalhes' => 'Subscription details',
    'stripe.plano' => 'Plan',
    'stripe.valor' => 'Amount',
    'stripe.prox_cobranca' => 'Next billing',
    'stripe.status' => 'Status',
    'stripe.ativa' => 'Active',
    'stripe.vps_vinculada' => 'Linked VPS',
    'stripe.proximos_passos' => 'Next steps:',
    'stripe.passo_1' => 'Your VPS will be provisioned automatically in a few minutes.',
    'stripe.passo_2' => 'You will receive access credentials in the dashboard.',
    'stripe.passo_3' => 'If you have questions, open a support ticket.',
    'stripe.ver_vps' => 'View my VPS',
    'stripe.ver_assinaturas' => 'View subscriptions',
    'stripe.cancelado_titulo' => 'Checkout cancelled',
    'stripe.cancelado_sub' => 'You cancelled the checkout. No charges were made.',
    'stripe.escolher_plano' => 'Choose another plan',
    'stripe.voltar_planos' => 'View plans',

    // ── Checkout ──
    'checkout.forma_pagamento' => 'Payment method',
    'checkout.cartao' => 'Card',
    'checkout.cpf_cnpj' => 'Tax ID (CPF/CNPJ)',
    'checkout.cpf_obrigatorio' => 'Required for billing.',

    // ── Payment ──
    'pagamento.titulo' => 'Payment',
    'pagamento.confirmado_titulo' => 'Payment confirmed',
    'pagamento.confirmado_sub' => 'Your VPS will be provisioned automatically.',
    'pagamento.ver_assinaturas' => 'View subscriptions',
    'pagamento.aguardando_pix' => 'Waiting for PIX payment',
    'pagamento.pix_copia_cola' => 'PIX Copy & Paste',
    'pagamento.copiar' => 'Copy',
    'pagamento.copiado' => 'Copied!',
    'pagamento.pix_expira' => 'Expires at',
    'pagamento.pix_instrucao' => 'Scan the QR Code or copy the code above and paste it in your bank app. Payment will be confirmed automatically.',
    'pagamento.boleto_titulo' => 'Boleto generated',
    'pagamento.boleto_aviso' => 'Boleto may take up to 3 business days to clear.',
    'pagamento.boleto_linha' => 'Barcode number',
    'pagamento.boleto_baixar' => 'Download boleto',
    'pagamento.boleto_instrucao' => 'After payment, confirmation will be automatic. You can track it in Subscriptions.',
    'pagamento.cartao_titulo' => 'Card payment',
    'pagamento.dados_cartao' => 'Card details',
    'pagamento.nome_cartao' => 'Name on card',
    'pagamento.numero_cartao' => 'Card number',
    'pagamento.dados_titular' => 'Cardholder details',
    'pagamento.telefone' => 'Phone',
    'pagamento.numero_endereco' => 'Address number',
    'pagamento.pagar' => 'Pay',
    'pagamento.processando' => 'Processing...',
    'pagamento.cartao_sucesso' => 'Payment approved! Redirecting...',
    'pagamento.cartao_analise' => 'Payment under review. Please wait for confirmation.',
    'pagamento.erro_generico' => 'Error processing payment. Please try again.',
    'pagamento.erro_tipo' => 'Payment type not identified.',
    'pagamento.voltar_planos' => 'Back to plans',

    // ── Chat Flows ──
    'chat_flows.titulo' => 'Chat Flows',
    'chat_flows.subtitulo' => 'Manage automated message sequences',
    'chat_flows.novo_fluxo' => 'New Flow',
    'chat_flows.editar_fluxo' => 'Edit Flow',
    'chat_flows.dados_fluxo' => 'Flow Details',
    'chat_flows.nome' => 'Name',
    'chat_flows.descricao' => 'Description',
    'chat_flows.gatilho' => 'Trigger',
    'chat_flows.trigger_inatividade' => 'Client inactivity',
    'chat_flows.trigger_encerramento' => 'Chat closure',
    'chat_flows.trigger_manual' => 'Manual',
    'chat_flows.passos' => 'Steps',
    'chat_flows.tipo' => 'Type',
    'chat_flows.conteudo' => 'Content',
    'chat_flows.tipo_mensagem' => 'Message',
    'chat_flows.tipo_atraso' => 'Delay',
    'chat_flows.tipo_acao' => 'Action',
    'chat_flows.segundos' => 'Seconds',
    'chat_flows.acao_fechar_chat' => 'Close chat',
    'chat_flows.acao_enviar_satisfacao' => 'Send satisfaction link',
    'chat_flows.adicionar_passo' => 'Add Step',
    'chat_flows.adicionar' => 'Add',
    'chat_flows.confirmar_excluir' => 'Are you sure you want to delete this flow?',
    'chat_flows.confirmar_remover_passo' => 'Are you sure you want to remove this step?',
    'chat_flows.nenhum_passo' => 'No steps configured.',
    'chat_flows.historico_execucoes' => 'Execution History',
    'chat_flows.nenhuma_execucao' => 'No executions recorded.',
    'chat_flows.sala' => 'Room',
    'chat_flows.origem' => 'Source',
    'chat_flows.iniciado_em' => 'Started at',
    'chat_flows.concluido_em' => 'Completed at',
    'chat_flows.timeout_inatividade' => 'Inactivity timeout',
    'chat_flows.minutos' => 'minutes',
    'chat_flows.fluxos' => 'Flows',
    'chat_flows.disparar_fluxo' => 'Dispatch manual flow',
    'chat_flows.sistema' => 'System',
];
