<?php

return [
    // ── Navbar pública ──
    'nav.inicio' => 'Inicio',
    'nav.produtos' => 'Productos',
    'nav.infraestrutura' => 'Infraestructura',
    'nav.planos' => 'Planes',
    'nav.status' => 'Estado',
    'nav.recursos' => 'Recursos',
    'nav.changelog' => 'Changelog',
    'nav.contato' => 'Contacto',
    'nav.termos' => 'Términos de uso',
    'nav.privacidade' => 'Privacidad',
    'nav.licenca' => 'Licencia',
    'nav.entrar' => 'Ingresar',
    'nav.contratar' => 'Contratar Ahora',

    // Mega: Productos
    'mega.prod_infra' => 'Infraestructura',
    'mega.prod_vps' => 'VPS Gestionada',
    'mega.prod_vps_desc' => 'Servidores virtuales con panel completo',
    'mega.prod_enterprise' => 'VPS Enterprise',
    'mega.prod_enterprise_desc' => 'Alto rendimiento para proyectos criticos',
    'mega.prod_dedicado' => 'Servidores Dedicados',
    'mega.prod_dedicado_desc' => 'Hardware exclusivo bajo demanda',
    'mega.prod_apps' => 'Aplicaciones',
    'mega.prod_wordpress' => 'WordPress Gestionado',
    'mega.prod_wordpress_desc' => 'Deploy optimizado para WordPress',
    'mega.prod_nodejs' => 'APIs Node.js',
    'mega.prod_nodejs_desc' => 'Entornos listos para Node',
    'mega.prod_php' => 'Sistemas PHP',
    'mega.prod_php_desc' => 'Laravel, Symfony y mas',
    'mega.prod_python' => 'Apps Python',
    'mega.prod_python_desc' => 'Django, Flask y automatizaciones',
    'mega.prod_deploy' => 'Deploy automatico',
    'mega.prod_deploy_desc' => 'CI/CD integrado via Git',
    'mega.prod_devops' => 'Dev & Ops',
    'mega.prod_terminal' => 'Terminal Web (SSH)',
    'mega.prod_terminal_desc' => 'Acceso directo desde el navegador',
    'mega.prod_monitor' => 'Monitoreo',
    'mega.prod_monitor_desc' => 'CPU, RAM, disco en tiempo real',
    'mega.prod_backups' => 'Backups automaticos',
    'mega.prod_backups_desc' => 'Programados y bajo demanda',
    'mega.prod_logs' => 'Logs y metricas',
    'mega.prod_logs_desc' => 'Historial completo de operaciones',
    'mega.prod_comm' => 'Comunicacion',
    'mega.prod_email' => 'Correo profesional',
    'mega.prod_email_desc' => 'Dominio propio con Mailcow',
    'mega.prod_chat' => 'Chat en tiempo real',
    'mega.prod_chat_desc' => 'Soporte directo desde el panel',
    'mega.prod_tickets' => 'Soporte tecnico',
    'mega.prod_tickets_desc' => 'Tickets y centro de ayuda',
    'mega.prod_ver_todos' => 'Ver todos los productos',

    // Mega: Infraestructura
    'mega.infra_como' => 'Como funciona',
    'mega.infra_como_desc' => 'Arquitectura y tecnologia',
    'mega.infra_seguranca' => 'Seguridad',
    'mega.infra_seguranca_desc' => '2FA, RBAC, cifrado AES-256',
    'mega.infra_sla' => 'SLA / Uptime',
    'mega.infra_sla_desc' => '99,9% de disponibilidad garantizada',
    'mega.infra_dc' => 'Data Centers',
    'mega.infra_dc_desc' => 'Infraestructura Tier III+',

    // Mega: Recursos
    'mega.rec_perf' => 'Rendimiento',
    'mega.rec_alta_disp' => 'Alta disponibilidad',
    'mega.rec_balanceamento' => 'Balanceo de carga',
    'mega.rec_seg' => 'Seguridad',
    'mega.rec_isolamento' => 'Aislamiento por contenedor',
    'mega.rec_ddos' => 'Proteccion DDoS',
    'mega.rec_backups' => 'Backups automaticos',
    'mega.rec_monit' => 'Monitoreo',
    'mega.rec_status' => 'Estado en tiempo real',
    'mega.rec_metricas' => 'Metricas CPU/RAM/Disco',
    'mega.rec_alertas' => 'Alertas',
    'mega.rec_exp' => 'Experiencia',
    'mega.rec_painel' => 'Panel intuitivo',
    'mega.rec_deploy' => 'Deploy facil',
    'mega.rec_cli' => 'Terminal Web',

    // ── Paginas de soluciones (landing pages) ──
    // Compartido
    'sol.section_beneficios' => 'Por que elegir LRV?',
    'sol.section_como_funciona' => 'Un proceso estructurado para garantizar estabilidad',
    'sol.section_faq' => 'Preguntas frecuentes',
    'sol.section_prova' => 'Empresas que ya confian en LRV',
    'sol.passo1' => 'Cree su cuenta',
    'sol.passo1_desc' => 'Un proceso de registro simple, sin burocracia. Su cuenta estara lista en menos de un minuto.',
    'sol.passo2' => 'Preparamos su entorno',
    'sol.passo2_desc' => 'Nuestro equipo configura la infraestructura segun las necesidades de su negocio, garantizando estabilidad desde el primer dia.',
    'sol.passo3' => 'Concentrese en su negocio',
    'sol.passo3_desc' => 'Mientras cuidamos de la infraestructura, su equipo puede concentrarse en lo que realmente impulsa el crecimiento.',
    'sol.cta_planos' => 'Ver planes',
    'sol.cta_contato' => 'Hablar con un especialista',
    'sol.cta_final_titulo' => 'Lleve mas estabilidad y previsibilidad a su operacion',
    'sol.cta_final_desc' => 'Elija el plan que se adapte a sus necesidades o hable con nuestro equipo. Sin compromiso.',
    'sol.depoimento1_nome' => 'Ricardo Mendes',
    'sol.depoimento1_cargo' => 'CEO, TechStart',
    'sol.depoimento1_texto' => 'Migramos toda nuestra operacion a LRV y el impacto fue inmediato. Los tiempos de respuesta bajaron, la disponibilidad aumento y nuestro equipo dejo de preocuparse por la infraestructura.',
    'sol.depoimento2_nome' => 'Camila Ferreira',
    'sol.depoimento2_cargo' => 'Directora de TI, Agencia Pixel',
    'sol.depoimento2_texto' => 'Lo que diferencia a LRV es la calidad del soporte. Los problemas se resuelven en minutos, con comunicacion clara y sin rodeos. Eso marca una diferencia real en nuestras operaciones diarias.',
    'sol.depoimento3_nome' => 'Andre Oliveira',
    'sol.depoimento3_cargo' => 'CTO, SaaS Express',
    'sol.depoimento3_texto' => 'Necesitabamos una infraestructura que acompanara nuestro crecimiento sin agregar complejidad. LRV entrego exactamente eso, con previsibilidad y confiabilidad.',

    // VPS
    'sol.vps_titulo' => 'Infraestructura estable y gestionada para empresas que no pueden parar',
    'sol.vps_subtitulo' => 'Servidores dedicados configurados, monitoreados y protegidos las 24 horas para que su equipo se concentre en lo que importa.',
    'sol.vps_cta' => 'Comenzar ahora',
    'sol.vps_problema_titulo' => 'Problemas de infraestructura que impactan directamente su operacion',
    'sol.vps_problema_desc' => 'Muchas empresas aun enfrentan inestabilidad, lentitud y soporte inadecuado. Son problemas que afectan directamente la operacion, la experiencia del cliente y, en ultima instancia, los ingresos. Si su proveedor actual no puede garantizar disponibilidad y tiempos de respuesta rapidos, el costo de la inaccion crece cada dia.',
    'sol.vps_solucao_titulo' => 'Gestion completa para que usted se concentre en el crecimiento',
    'sol.vps_solucao_desc' => 'En LRV, nos encargamos de toda la capa tecnica. Desde la configuracion inicial hasta el monitoreo continuo, sus servidores estan configurados, protegidos y optimizados por nuestro equipo. Usted obtiene el rendimiento y la estabilidad que su negocio necesita, sin la carga operativa.',
    'sol.vps_b1_titulo' => 'Alto rendimiento',
    'sol.vps_b1_desc' => 'Infraestructura optimizada para mantener sus sistemas rapidos incluso en momentos de alta demanda.',
    'sol.vps_b2_titulo' => 'Disponibilidad continua',
    'sol.vps_b2_desc' => 'Un entorno preparado para mantener su operacion en linea con maxima estabilidad y 99,9% de uptime.',
    'sol.vps_b3_titulo' => 'Soporte especializado',
    'sol.vps_b3_desc' => 'Un equipo dedicado que conoce su entorno y resuelve problemas con rapidez y precision.',
    'sol.vps_b4_titulo' => 'Backups automatizados',
    'sol.vps_b4_desc' => 'Copias de seguridad diarias con restauracion en un clic, garantizando que sus datos esten siempre protegidos y recuperables.',
    'sol.vps_b5_titulo' => 'Monitoreo proactivo',
    'sol.vps_b5_desc' => 'Identificamos y abordamos problemas potenciales antes de que impacten su operacion.',
    'sol.vps_b6_titulo' => 'Escalabilidad sin fricciones',
    'sol.vps_b6_desc' => 'Aumente recursos a medida que su negocio crece, sin downtime y sin migraciones complejas.',
    'sol.vps_faq1_p' => 'Necesito conocimientos tecnicos para gestionar el servidor?',
    'sol.vps_faq1_r' => 'No. Nuestro equipo se encarga de toda la configuracion, mantenimiento y monitoreo. Usted interactua a traves de un panel intuitivo disenado para la simplicidad.',
    'sol.vps_faq2_p' => 'Ayudan con la migracion desde otro proveedor?',
    'sol.vps_faq2_r' => 'Si. Realizamos la migracion completa de sus sitios y sistemas sin costo adicional, garantizando una transicion fluida con minimo tiempo de inactividad.',
    'sol.vps_faq3_p' => 'Que sucede si mi negocio crece significativamente?',
    'sol.vps_faq3_r' => 'Puede escalar recursos en cualquier momento directamente desde el panel, sin downtime. Nuestra infraestructura esta disenada para crecer junto con su negocio.',
    'sol.vps_faq4_p' => 'Hay un periodo minimo de contrato?',
    'sol.vps_faq4_r' => 'No. No hay multas ni periodos de permanencia. Puede cancelar en cualquier momento con total flexibilidad.',

    // Aplicaciones
    'sol.apps_titulo' => 'Lance su proyecto en minutos, no en dias',
    'sol.apps_subtitulo' => 'Desde WordPress hasta aplicaciones web personalizadas. Despliegue con un solo clic y comience a operar de inmediato.',
    'sol.apps_cta' => 'Ver aplicaciones disponibles',
    'sol.apps_problema_titulo' => 'Desplegar una aplicacion no deberia requerir un equipo dedicado',
    'sol.apps_problema_desc' => 'Configuracion de servidores, gestion de dependencias, preparacion de entornos. Estas tareas consumen tiempo valioso y requieren conocimiento especializado que desvian el foco de su negocio principal. Para muchas empresas, la barrera tecnica entre una idea y un producto en produccion sigue siendo demasiado alta.',
    'sol.apps_solucao_titulo' => 'Despliegue simplificado con confiabilidad empresarial',
    'sol.apps_solucao_desc' => 'Nuestro catalogo de aplicaciones permite desplegar WordPress, sistemas web y proyectos personalizados con un solo clic. El entorno viene preconfigurado, optimizado y listo para produccion, sin configuracion manual.',
    'sol.apps_b1_titulo' => 'Despliegue en un clic',
    'sol.apps_b1_desc' => 'Seleccione su aplicacion y se despliega automaticamente con la configuracion correcta.',
    'sol.apps_b2_titulo' => 'Actualizaciones automaticas',
    'sol.apps_b2_desc' => 'Sus aplicaciones se mantienen actualizadas y seguras sin intervencion manual.',
    'sol.apps_b3_titulo' => 'Entrega continua',
    'sol.apps_b3_desc' => 'Envie su codigo y se publica automaticamente a traves de CI/CD integrado.',
    'sol.apps_b4_titulo' => 'Amplia compatibilidad',
    'sol.apps_b4_desc' => 'WordPress, e-commerce, APIs, sistemas internos y mas. Todo en una sola plataforma.',
    'sol.apps_b5_titulo' => 'Sin experiencia tecnica necesaria',
    'sol.apps_b5_desc' => 'Disenado para equipos de negocio que necesitan resultados sin complejidad operativa.',
    'sol.apps_b6_titulo' => 'Soporte incluido',
    'sol.apps_b6_desc' => 'Nuestro equipo esta disponible para asistir con despliegue, configuracion y resolucion de problemas.',
    'sol.apps_faq1_p' => 'Necesito conocimientos de programacion?',
    'sol.apps_faq1_r' => 'No. Las aplicaciones del catalogo se instalan automaticamente. Para proyectos personalizados, nuestro equipo puede asistir con la configuracion inicial.',
    'sol.apps_faq2_p' => 'Puedo desplegar mi propia aplicacion personalizada?',
    'sol.apps_faq2_r' => 'Si. Ademas del catalogo, puede desplegar cualquier proyecto usando integracion Git con builds automatizados.',
    'sol.apps_faq3_p' => 'Que tipo de soporte esta disponible?',
    'sol.apps_faq3_r' => 'Ofrecemos soporte via chat en vivo, tickets y correo electronico. Nuestro equipo esta capacitado para ayudar tanto con problemas de plataforma como de aplicacion.',
    'sol.apps_faq4_p' => 'Hay un limite en el numero de aplicaciones?',
    'sol.apps_faq4_r' => 'Depende de su plan, pero todos los planes soportan multiples aplicaciones ejecutandose simultaneamente.',

    // Dev & Ops
    'sol.devops_titulo' => 'Control operativo completo sin complejidad innecesaria',
    'sol.devops_subtitulo' => 'Gestione, monitoree y automatice su infraestructura desde un unico panel intuitivo.',
    'sol.devops_cta' => 'Conocer las herramientas',
    'sol.devops_problema_titulo' => 'La gestion de infraestructura no deberia consumir el tiempo de su equipo',
    'sol.devops_problema_desc' => 'Acceder a servidores por linea de comandos, revisar logs manualmente, descubrir problemas solo despues de que impactan a los usuarios. Estos patrones operativos consumen tiempo, aumentan el riesgo e impiden que su equipo se enfoque en trabajo estrategico.',
    'sol.devops_solucao_titulo' => 'Todo accesible desde su navegador, todo bajo control',
    'sol.devops_solucao_desc' => 'Con LRV, accede a terminales, monitorea recursos en tiempo real y recibe alertas inteligentes directamente desde el panel. Sin software que instalar, sin configuraciones complejas. Un enfoque estructurado para garantizar seguridad y estabilidad desde el inicio.',
    'sol.devops_b1_titulo' => 'Acceso desde el navegador',
    'sol.devops_b1_desc' => 'Gestione sus servidores desde cualquier lugar, sin necesidad de instalar software.',
    'sol.devops_b2_titulo' => 'Monitoreo en tiempo real',
    'sol.devops_b2_desc' => 'Visibilidad completa del uso de CPU, memoria y disco en todos sus servidores.',
    'sol.devops_b3_titulo' => 'Backups automatizados',
    'sol.devops_b3_desc' => 'Copias de seguridad programadas y bajo demanda con restauracion en un clic.',
    'sol.devops_b4_titulo' => 'Alertas inteligentes',
    'sol.devops_b4_desc' => 'Notificaciones proactivas que le avisan antes de que los problemas afecten su operacion.',
    'sol.devops_b5_titulo' => 'Registro de auditoria completo',
    'sol.devops_b5_desc' => 'Historial detallado de cada accion realizada, cuando ocurrio y por quien.',
    'sol.devops_b6_titulo' => 'Despliegue automatizado',
    'sol.devops_b6_desc' => 'Actualice sus sistemas con un simple envio de codigo a traves de CI/CD integrado.',
    'sol.devops_faq1_p' => 'Necesito instalar algun software?',
    'sol.devops_faq1_r' => 'No. Toda la plataforma funciona en su navegador. Puede gestionar su infraestructura desde cualquier dispositivo con acceso a internet.',
    'sol.devops_faq2_p' => 'Puedo monitorear mis servidores en tiempo real?',
    'sol.devops_faq2_r' => 'Si. El panel muestra uso de recursos, estado de servicios y alertas en vivo, brindandole visibilidad completa de su entorno.',
    'sol.devops_faq3_p' => 'Que sucede si algo sale mal?',
    'sol.devops_faq3_r' => 'Recibe alertas automaticas y puede restaurar backups con un solo clic. Nuestro equipo tambien esta disponible para asistir con la resolucion de incidentes.',
    'sol.devops_faq4_p' => 'Los miembros de mi equipo pueden tener su propio acceso?',
    'sol.devops_faq4_r' => 'Si. Puede crear cuentas individuales con permisos granulares, asegurando que cada miembro del equipo tenga acceso solo a lo que necesita.',

    // Correo
    'sol.email_titulo' => 'Correo profesional que refuerza su marca en cada mensaje',
    'sol.email_subtitulo' => 'Correo @suempresa.com listo para usar. Transmita credibilidad y profesionalismo en cada interaccion.',
    'sol.email_cta' => 'Crear mi correo profesional',
    'sol.email_problema_titulo' => 'Las direcciones de correo gratuitas debilitan la credibilidad de su negocio',
    'sol.email_problema_desc' => 'Los correos enviados desde direcciones @gmail o @hotmail proyectan una imagen amateur que sus clientes y socios perciben. En un mercado competitivo, la percepcion importa. Sus competidores ya se comunican con su propio dominio, reforzando confianza y autoridad en cada mensaje.',
    'sol.email_solucao_titulo' => 'Comunicacion profesional que genera confianza',
    'sol.email_solucao_desc' => 'Con correo @suempresa.com, cada mensaje refuerza la identidad de su marca. La configuracion es sencilla, la gestion es simple y el resultado es una imagen mas profesional que inspira confianza en sus clientes.',
    'sol.email_b1_titulo' => 'Su dominio, su identidad',
    'sol.email_b1_desc' => 'Cada correo enviado lleva el nombre de su empresa, reforzando el reconocimiento de marca.',
    'sol.email_b2_titulo' => 'Acceso desde cualquier dispositivo',
    'sol.email_b2_desc' => 'Funciona perfectamente en navegadores, smartphones y clientes de correo de escritorio.',
    'sol.email_b3_titulo' => 'Filtrado avanzado de spam',
    'sol.email_b3_desc' => 'Filtros inteligentes que mantienen su bandeja de entrada limpia y productiva.',
    'sol.email_b4_titulo' => 'Compatibilidad universal',
    'sol.email_b4_desc' => 'Totalmente compatible con Outlook, Gmail, Apple Mail y cualquier cliente de correo estandar.',
    'sol.email_b5_titulo' => 'Gestion sencilla',
    'sol.email_b5_desc' => 'Cree, modifique y elimine cuentas directamente desde el panel sin conocimientos tecnicos.',
    'sol.email_b6_titulo' => 'Seguro y confiable',
    'sol.email_b6_desc' => 'Sus comunicaciones protegidas con cifrado y copias de seguridad automatizadas.',
    'sol.email_faq1_p' => 'Necesito tener ya un dominio?',
    'sol.email_faq1_r' => 'Si, se requiere un dominio. Si aun no tiene uno, nuestro equipo puede guiarle en el proceso de registro.',
    'sol.email_faq2_p' => 'Puedo acceder a mi correo en dispositivos moviles?',
    'sol.email_faq2_r' => 'Si. Funciona con cualquier aplicacion de correo en smartphones y tablets, asi como a traves de webmail en cualquier navegador.',
    'sol.email_faq3_p' => 'Cuantas cuentas de correo puedo crear?',
    'sol.email_faq3_r' => 'El numero de cuentas depende de su plan. Todos los planes soportan multiples cuentas para acomodar a su equipo.',
    'sol.email_faq4_p' => 'Ustedes se encargan de la configuracion inicial?',
    'sol.email_faq4_r' => 'Si. Nuestro equipo asiste con la configuracion completa, incluyendo registros DNS y configuracion de clientes.',

    // Seguridad
    'sol.seg_titulo' => 'Proteccion integral para su negocio, las 24 horas',
    'sol.seg_subtitulo' => 'Seguridad de nivel empresarial integrada en cada capa de su infraestructura. Proteccion que funciona automaticamente para que opere con confianza.',
    'sol.seg_cta' => 'Proteger mi negocio',
    'sol.seg_problema_titulo' => 'Un incidente de seguridad puede costar mucho mas que la prevencion',
    'sol.seg_problema_desc' => 'Filtraciones de datos, interrupciones de servicio, clientes perdidos. Un solo incidente de seguridad puede causar perdidas financieras significativas y destruir la confianza que tardo anos en construir. Para empresas que dependen de su presencia digital, la seguridad no es opcional.',
    'sol.seg_solucao_titulo' => 'Proteccion de nivel profesional sin requerir experiencia especializada',
    'sol.seg_solucao_desc' => 'En LRV, la seguridad esta integrada desde el inicio. Sus datos estan aislados, cifrados y monitoreados continuamente. Cada capa de proteccion es configurada y mantenida por nuestro equipo, para que usted se beneficie de seguridad empresarial sin la complejidad.',
    'sol.seg_b1_titulo' => 'Entornos aislados',
    'sol.seg_b1_desc' => 'Sus datos y aplicaciones se ejecutan en contenedores aislados, completamente separados de otros clientes.',
    'sol.seg_b2_titulo' => 'Autenticacion de dos factores',
    'sol.seg_b2_desc' => 'Una capa adicional de verificacion que protege su cuenta incluso si las credenciales se ven comprometidas.',
    'sol.seg_b3_titulo' => 'Control de acceso granular',
    'sol.seg_b3_desc' => 'Defina con precision lo que cada miembro del equipo puede ver y modificar dentro de su cuenta.',
    'sol.seg_b4_titulo' => 'Cifrado de datos',
    'sol.seg_b4_desc' => 'Informacion sensible protegida con cifrado AES-256 de nivel bancario en reposo y en transito.',
    'sol.seg_b5_titulo' => 'Registro de auditoria completo',
    'sol.seg_b5_desc' => 'Registros detallados de cada accion realizada en su cuenta, proporcionando trazabilidad y responsabilidad total.',
    'sol.seg_b6_titulo' => 'Proteccion automatizada contra amenazas',
    'sol.seg_b6_desc' => 'Defensas activas que detectan y bloquean los vectores de ataque mas comunes automaticamente.',
    'sol.seg_faq1_p' => 'Necesito configurar los ajustes de seguridad manualmente?',
    'sol.seg_faq1_r' => 'No. Todas las medidas de seguridad estan configuradas y activas desde el primer dia. Nuestro equipo monitorea y actualiza continuamente las protecciones a medida que surgen nuevas amenazas.',
    'sol.seg_faq2_p' => 'Como se protegen mis datos?',
    'sol.seg_faq2_r' => 'Utilizamos cifrado AES-256, aislamiento por contenedores y copias de seguridad automatizadas. Sus datos estan protegidos en cada capa de la infraestructura.',
    'sol.seg_faq3_p' => 'Que sucede si alguien intenta vulnerar mi cuenta?',
    'sol.seg_faq3_r' => 'Nuestros sistemas de defensa automatizados detectan y bloquean intentos de intrusion en tiempo real. Se le notifica de cualquier actividad sospechosa y nuestro equipo esta disponible para asistir con la respuesta a incidentes.',
    'sol.seg_faq4_p' => 'Puedo controlar quien tiene acceso a mi cuenta?',
    'sol.seg_faq4_r' => 'Si. Puede crear cuentas individuales con permisos granulares basados en roles, asegurando que cada miembro del equipo tenga acceso solo a los recursos que necesita.',

    // ── Footer público ──
    'footer.desc' => 'Infraestructura cloud gestionada. VPS, deploy, correos, backups y soporte en un solo panel.',
    'footer.produto' => 'Producto',
    'footer.funcionalidades' => 'Funcionalidades',
    'footer.planos' => 'Planes',
    'footer.changelog' => 'Changelog',
    'footer.status' => 'Estado',
    'footer.suporte' => 'Soporte',
    'footer.contato' => 'Contacto',
    'footer.central_ajuda' => 'Centro de ayuda',
    'footer.tickets' => 'Tickets',
    'footer.legal' => 'Legal',
    'footer.termos' => 'Términos de uso',
    'footer.privacidade' => 'Privacidad',
    'footer.licenca' => 'Licencia de uso',
    'footer.sistemas_op' => 'Todos los sistemas operativos',
    'footer.cookies' => 'Cookies',

    // ── Cookies / Consentimiento ──
    'cookies.titulo' => 'Utilizamos cookies',
    'cookies.descricao' => 'Este sitio utiliza cookies para mejorar su experiencia de navegacion. Puede aceptar todas, rechazar las opcionales o configurar sus preferencias.',
    'cookies.saiba_mais' => 'Mas informacion',
    'cookies.aceitar_todos' => 'Aceptar todas',
    'cookies.rejeitar_opcionais' => 'Rechazar opcionales',
    'cookies.configurar' => 'Configurar',
    'cookies.config_titulo' => 'Preferencias de cookies',
    'cookies.config_desc' => 'Elija que categorias de cookies desea permitir. Las cookies necesarias estan siempre activas para garantizar el funcionamiento del sistema.',
    'cookies.cat_necessarios' => 'Necesarias',
    'cookies.cat_necessarios_desc' => 'Esenciales para autenticacion, sesion y seguridad. No se pueden desactivar.',
    'cookies.cat_analytics' => 'Analytics',
    'cookies.cat_analytics_desc' => 'Nos ayudan a entender como se utiliza el sitio para mejorar la experiencia.',
    'cookies.cat_marketing' => 'Marketing',
    'cookies.cat_marketing_desc' => 'Utilizadas para mostrar contenido relevante y medir campanas.',
    'cookies.cat_preferencias' => 'Preferencias',
    'cookies.cat_preferencias_desc' => 'Almacenan configuraciones como idioma y tema elegido.',
    'cookies.salvar_prefs' => 'Guardar preferencias',
    'cookies.privacidade_texto' => 'Utilizamos cookies para garantizar el funcionamiento del sistema, mejorar la experiencia de navegacion y, cuando se autoriza, analizar el uso del sitio. Puede gestionar sus preferencias en cualquier momento.',

    // ── Estado público ──
    'status.todos_operacionais' => 'Todos los sistemas operativos',
    'status.degradacao' => 'Degradación parcial detectada',
    'status.indisponivel' => 'Indisponibilidad en curso',
    'status.desconhecido' => 'Estado desconocido',

    // ── General ──
    'geral.erro_interno' => 'Error interno.',
    'geral.rota_nao_encontrada' => 'Ruta no encontrada.',
    'geral.salvar' => 'Guardar',
    'geral.cancelar' => 'Cancelar',
    'geral.voltar' => 'Volver',
    'geral.excluir' => 'Eliminar',
    'geral.editar' => 'Editar',
    'geral.novo' => 'Nuevo',
    'geral.ver' => 'Ver',
    'geral.fechar' => 'Cerrar',
    'geral.enviar' => 'Enviar',
    'geral.confirmar' => 'Confirmar',
    'geral.sim' => 'Si',
    'geral.nao' => 'No',
    'geral.ativo' => 'Activo',
    'geral.inativo' => 'Inactivo',
    'geral.status' => 'Estado',
    'geral.acoes' => 'Acciones',
    'geral.carregando' => 'Cargando...',
    'geral.nenhum_resultado' => 'No se encontraron resultados.',
    'geral.area_cliente' => 'Area del cliente',
    'geral.area_equipe' => 'Panel administrativo',
    'geral.sair' => 'Salir',
    'geral.minha_conta' => 'Mi Cuenta',
    'geral.configuracoes_salvas' => 'Configuracion guardada.',
    'geral.erro_formulario' => 'Corrija los errores a continuacion.',
    'geral.processando' => 'Procesando...',
    'geral.copyright' => '(c) %s LRV Web',
    'geral.recolher_menu' => 'Contraer menu',
    'geral.expandir_menu' => 'Expandir menu',
    'geral.menu' => 'Menu',

    // ── Auth ──
    'auth.entrar' => 'Iniciar sesion',
    'auth.email' => 'Correo electronico',
    'auth.senha' => 'Contrasena',
    'auth.esqueci_senha' => 'Olvide mi contrasena',
    'auth.criar_conta' => 'Crear cuenta',
    'auth.ja_tem_conta' => 'Ya tienes cuenta?',
    'auth.nao_tem_conta' => 'No tienes cuenta?',
    'auth.nome' => 'Nombre completo',
    'auth.credenciais_invalidas' => 'Correo o contrasena incorrectos.',
    'auth.conta_criada' => 'Cuenta creada con exito.',
    'auth.logout_sucesso' => 'Has cerrado sesion.',

    // ── Reset de contrasena ──
    'reset.titulo' => 'Restablecer contrasena',
    'reset.instrucao' => 'Ingresa tu correo para recibir el enlace de restablecimiento.',
    'reset.email_enviado' => 'Si el correo existe, recibiras un enlace de restablecimiento.',
    'reset.nova_senha' => 'Nueva contrasena',
    'reset.confirmar_senha' => 'Confirmar nueva contrasena',
    'reset.senha_alterada' => 'Contrasena cambiada con exito.',
    'reset.token_invalido' => 'Enlace invalido o expirado.',
    'reset.solicitar' => 'Enviar enlace',

    // ── 2FA ──
    '2fa.titulo' => 'Autenticacion de dos factores',
    '2fa.configurar' => 'Configurar 2FA',
    '2fa.ativar' => 'Activar',
    '2fa.desativar' => 'Desactivar',
    '2fa.verificar' => 'Verificar',
    '2fa.codigo' => 'Codigo de verificacion',
    '2fa.instrucao_qr' => 'Escanea el codigo QR con tu app autenticadora (Google Authenticator, Authy, etc.)',
    '2fa.instrucao_manual' => 'O ingresa la clave manualmente:',
    '2fa.ativado' => '2FA activado con exito.',
    '2fa.desativado' => '2FA desactivado.',
    '2fa.codigo_invalido' => 'Codigo invalido.',
    '2fa.confirme_senha' => 'Confirma tu contrasena para desactivar.',
    '2fa.ja_ativo' => 'La autenticacion de dos factores ya esta activa.',
    '2fa.seguranca' => 'Seguridad',

    // ── Sidebar cliente ──
    'sidebar.painel' => 'Panel',
    'sidebar.vps' => 'VPS',
    'sidebar.monitoramento' => 'Monitoreo',
    'sidebar.tickets' => 'Tickets',
    'sidebar.chat' => 'Chat',
    'sidebar.emails' => 'Correos',
    'sidebar.aplicacoes' => 'Aplicaciones',
    'sidebar.catalogo' => 'Catalogo',
    'sidebar.assinaturas' => 'Suscripciones',
    'sidebar.ajuda' => 'Ayuda',
    'sidebar.seguranca' => 'Seguridad',
    'sidebar.planos' => 'Planes',

    // ── Panel cliente ──
    'painel.titulo' => 'Panel',
    'painel.bem_vindo' => 'Bienvenido, %s',
    'painel.total_vps' => 'Total de VPS',
    'painel.vps_rodando' => 'VPS en ejecucion',
    'painel.tickets_abertos' => 'Tickets abiertos',
    'painel.plano_ativo' => 'Plan activo',
    'painel.nenhum_plano' => 'Sin plan activo',
    'painel.notificacoes' => 'Notificaciones',
    'painel.sem_notificacoes' => 'Sin notificaciones.',

    // ── VPS ──
    'vps.titulo' => 'Mis VPS',
    'vps.subtitulo' => 'Servidores virtuales vinculados a tu cuenta',
    'vps.nenhuma' => 'Aun no tienes VPS.',
    'vps.terminal' => 'Terminal',
    'vps.status_running' => 'En ejecucion',
    'vps.status_stopped' => 'Detenida',
    'vps.status_provisioning' => 'Aprovisionando',
    'vps.status_suspended' => 'Suspendida',
    'vps.status_error' => 'Error',

    // ── Monitoreo ──
    'monitoramento.titulo' => 'Monitoreo',
    'monitoramento.subtitulo' => 'Metricas de CPU, RAM y disco de tus VPS',
    'monitoramento.cpu' => 'CPU',
    'monitoramento.ram' => 'RAM',
    'monitoramento.disco' => 'Disco',
    'monitoramento.ultima_coleta' => 'Ultima recoleccion',
    'monitoramento.sem_dados' => 'Sin datos de monitoreo.',

    // ── Tickets ──
    'tickets.titulo' => 'Tickets de Soporte',
    'tickets.novo' => 'Nuevo Ticket',
    'tickets.assunto' => 'Asunto',
    'tickets.mensagem' => 'Mensaje',
    'tickets.prioridade' => 'Prioridad',
    'tickets.departamento' => 'Departamento',
    'tickets.status' => 'Estado',
    'tickets.aberto' => 'Abierto',
    'tickets.em_andamento' => 'En progreso',
    'tickets.aguardando_cliente' => 'Esperando al cliente',
    'tickets.fechado' => 'Cerrado',
    'tickets.resolvido' => 'Resuelto',
    'tickets.responder' => 'Responder',
    'tickets.nenhum' => 'Aun no tienes tickets.',
    'tickets.criado' => 'Ticket creado con exito.',
    'tickets.prioridade_baixa' => 'Baja',
    'tickets.prioridade_media' => 'Media',
    'tickets.prioridade_alta' => 'Alta',

    // ── Chat ──
    'chat.titulo' => 'Chat en vivo',
    'chat.subtitulo' => 'Habla en tiempo real con nuestro equipo',
    'chat.enviar' => 'Enviar',
    'chat.digite_mensagem' => 'Escribe tu mensaje...',
    'chat.conectando' => 'Conectando...',
    'chat.conectado' => 'Conectado',
    'chat.desconectado' => 'Desconectado',
    'chat.reconectando' => 'Reconectando...',
    'chat.encerrar' => 'Finalizar chat',
    'chat.encerrado' => 'Chat finalizado.',
    'chat.emoji' => 'Emojis',
    'chat.anexar' => 'Adjuntar archivo',
    'chat.arquivo_enviado' => 'Archivo enviado.',
    'chat.arquivo_grande' => 'Archivo demasiado grande (max. 5 MB).',
    'chat.widget_titulo' => 'Necesitas ayuda?',
    'chat.widget_abrir' => 'Abrir chat',

    // ── Correos ──
    'emails.titulo' => 'Mis Correos',
    'emails.subtitulo' => 'Administra tus cuentas de correo',
    'emails.criar' => 'Crear correo',
    'emails.usuario' => 'Usuario',
    'emails.dominio' => 'Dominio',
    'emails.webmail' => 'Webmail',
    'emails.alterar_senha' => 'Cambiar contrasena',
    'emails.remover' => 'Eliminar',
    'emails.nenhum' => 'Aun no tienes correos.',
    'emails.dominios' => 'Dominios de Correo',
    'emails.adicionar_dominio' => 'Agregar dominio',
    'emails.verificar_dns' => 'Verificar DNS',
    'emails.instrucoes_dns' => 'Instrucciones DNS',
    'emails.tutoriais_titulo' => 'Configurar en otras apps',
    'emails.tutoriais_desc' => 'Use su correo profesional en Outlook, Gmail, Apple Mail o cualquier app de correo.',
    'emails.dados_config' => 'Datos de configuración',
    'emails.porta' => 'Puerto',
    'emails.usuario_config' => 'Usuario',
    'emails.seu_email_completo' => 'Su correo completo (ej: contacto@sudominio.com)',
    'emails.senha_definida' => 'La contraseña que definió al crear el correo',
    'emails.pc_celular' => 'PC y Celular',
    'emails.outlook_1' => 'Abra Outlook y vaya a Archivo > Agregar Cuenta',
    'emails.outlook_2' => 'Seleccione "Configuración manual" y elija IMAP',
    'emails.outlook_3' => 'Complete los datos del servidor según la tabla anterior',
    'emails.outlook_4' => 'IMAP: puerto <code>993</code> con SSL/TLS — SMTP: puerto <code>587</code> con STARTTLS',
    'emails.outlook_5' => 'Haga clic en Conectar y espere la verificación',
    'emails.outlook_mobile' => 'En el celular: descargue la app Outlook, toque Agregar Cuenta y use los mismos datos.',
    'emails.gmail_1' => 'En Gmail, haga clic en el engranaje > Ver toda la configuración',
    'emails.gmail_2' => 'Vaya a "Cuentas e importación" > "Agregar una cuenta de correo"',
    'emails.gmail_3' => 'Ingrese su correo profesional y seleccione "Importar vía POP3" o "IMAP"',
    'emails.gmail_4' => 'Servidor IMAP: puerto <code>993</code> SSL — Servidor SMTP: puerto <code>587</code> TLS',
    'emails.gmail_5' => 'Confirme y Gmail sincronizará sus correos',
    'emails.gmail_mobile' => 'En el celular: abra la app Gmail > Agregar cuenta > Otra > use los mismos datos IMAP/SMTP.',
    'emails.apple_1' => 'Vaya a Ajustes > Mail > Cuentas > Agregar Cuenta > Otra',
    'emails.apple_2' => 'Toque "Agregar cuenta de correo"',
    'emails.apple_3' => 'Complete nombre, correo y contraseña',
    'emails.apple_4' => 'Servidor de entrada: puerto <code>993</code> SSL — Servidor de salida: puerto <code>587</code> TLS',
    'emails.apple_5' => 'Guarde y espere la verificación',
    'emails.thunder_1' => 'Abra Thunderbird y vaya a Configuración de Cuenta > Acciones > Agregar cuenta de correo',
    'emails.thunder_2' => 'Ingrese su nombre, correo y contraseña',
    'emails.thunder_3' => 'Thunderbird puede detectar automáticamente. Si no, haga clic en "Configuración manual" y use los datos de la tabla anterior',
    'emails.thunder_4' => 'Haga clic en Finalizar',
    'emails.cota' => 'Cuota de almacenamiento',
    'emails.cota_usada' => 'Usado',
    'emails.cota_total' => 'Total',
    'emails.cota_disponivel' => 'Disponible',
    'emails.cota_hint' => 'Espacio reservado para este buzón. Seleccione GB para valores mayores.',
    'emails.ativar_webmail' => 'Activar webmail personalizado',
    'emails.verificar_webmail' => 'Verificar webmail',
    'emails.webmail_ativado' => '¡Webmail personalizado activado con éxito!',
    'emails.webmail_personalizado_hint' => 'Acceda al webmail vía webmail.sudominio.com',

    // ── Aplicaciones ──
    'apps.titulo' => 'Mis Aplicaciones',
    'apps.subtitulo' => 'Apps instaladas en tus VPS',
    'apps.catalogo' => 'Catalogo de Aplicaciones',
    'apps.catalogo_subtitulo' => 'Instala aplicaciones listas con 1 clic en tu VPS',
    'apps.instalar' => 'Instalar',
    'apps.instalando' => 'Instalando...',
    'apps.instalacao_iniciada' => 'Instalacion iniciada!',
    'apps.nenhuma' => 'Aun no tienes aplicaciones.',
    'apps.vps_necessaria' => 'Necesitas una VPS activa para instalar aplicaciones.',
    'apps.voltar_painel' => 'Volver al panel',
    'apps.minhas_apps' => 'Mis aplicaciones',
    'apps.roundcube_aviso' => 'Roundcube se instalará en su VPS y consumirá recursos (CPU, RAM, disco). Al instalar, el webmail predeterminado del sistema será reemplazado por Roundcube para sus dominios.',
    'apps.catalogo_btn' => 'Catalogo - Instalar nueva',
    'apps.selecione_vps' => 'VPS',
    'apps.dominio' => 'Dominio',
    'apps.repositorio' => 'Repositorio Git',
    'apps.variaveis_env' => 'Variables de entorno (JSON)',
    'apps.status_installing' => 'Instalando',
    'apps.status_running' => 'Ejecutando',
    'apps.status_stopped' => 'Detenida',
    'apps.status_error' => 'Error',
    'apps.status_inactive' => 'Inactiva',
    'apps.status_deploying' => 'Desplegando',
    'apps.tipo' => 'Tipo',
    'apps.porta' => 'Puerto',
    'apps.aplicacao' => 'Aplicacion',

    // ── Suscripciones ──
    'assinaturas.titulo' => 'Mis Suscripciones',
    'assinaturas.subtitulo' => 'Historial de cobros y pagos',
    'assinaturas.nenhuma' => 'No se encontraron suscripciones.',
    'assinaturas.solicitar_reembolso' => 'Solicitar reembolso',
    'assinaturas.plano' => 'Plan',
    'assinaturas.valor' => 'Valor',
    'assinaturas.vencimento' => 'Vencimiento',

    // ── Planes ──
    'planos.titulo' => 'Planes Disponibles',
    'planos.subtitulo' => 'Elige el plan ideal para ti',
    'planos.assinar' => 'Suscribirse',
    'planos.atual' => 'Plan actual',
    'planos.mensal' => '/mes',

    // ── Mi Cuenta ──
    'conta.titulo' => 'Mi Cuenta',
    'conta.subtitulo' => 'Administre sus datos personales y contrasena',
    'conta.dados_pessoais' => 'Datos personales',
    'conta.alterar_senha' => 'Cambiar contrasena',
    'conta.senha_atual' => 'Contrasena actual',
    'conta.nova_senha' => 'Nueva contrasena',
    'conta.confirmar_senha' => 'Confirmar nueva contrasena',
    'conta.endereco' => 'Direccion',
    'conta.rua' => 'Calle',
    'conta.numero' => 'Numero',
    'conta.complemento' => 'Complemento',
    'conta.cidade' => 'Ciudad',
    'conta.estado' => 'Estado',
    'conta.cep' => 'Codigo postal',
    'conta.pais' => 'Pais',
    'conta.salvo' => 'Datos guardados con exito.',

    // ── Estado ──
    'status.titulo' => 'Estado de los Servicios',
    'status.operacional' => 'Operativo',
    'status.degradado' => 'Degradado',
    'status.fora' => 'Fuera de servicio',
    'status.incidentes' => 'Incidentes',

    // ── Ayuda ──
    'ajuda.titulo' => 'Centro de Ayuda',
    'ajuda.subtitulo' => 'Preguntas frecuentes',
    'ajuda.nao_encontrou' => 'No encontraste lo que buscabas?',
    'ajuda.chat_vivo' => 'Chat en vivo',
    'ajuda.abrir_ticket' => 'Abrir ticket',
    'ajuda.fale_conosco' => 'Contactanos',

    // ── Evaluacion ──
    'avaliacao.titulo' => 'Evaluacion',
    'avaliacao.como_foi' => 'Como fue tu atencion?',
    'avaliacao.comentario' => 'Comentario (opcional)',
    'avaliacao.enviar' => 'Enviar evaluacion',
    'avaliacao.obrigado' => 'Gracias por tu evaluacion!',

    // ── Onboarding ──
    'onboarding.titulo' => 'Bienvenido al sistema!',
    'onboarding.passo1' => 'Conoce tu panel',
    'onboarding.passo2' => 'Configura tu VPS',
    'onboarding.passo3' => 'Instala aplicaciones',
    'onboarding.passo4' => 'Necesitas ayuda?',
    'onboarding.concluir' => 'Listo',

    // ── Paginas publicas ──
    'pub.termos' => 'Terminos de Uso',
    'pub.privacidade' => 'Politica de Privacidad',
    'pub.licenca' => 'Licencia',
    'pub.changelog' => 'Changelog',
    'pub.contato' => 'Contacto',
    'pub.status' => 'Estado',

    // ── Home / Landing ──
    'home.titulo' => 'Infraestructura Cloud',
    'home.subtitulo' => 'Servidores VPS de alto rendimiento con gestion completa.',
    'home.comecar' => 'Comenzar ahora',
    'home.ver_planos' => 'Ver planes',
    'home.trial_cta' => 'Probar gratis',
    'home.nav_sobre' => 'Acerca de',
    'home.nav_planos' => 'Planes',
    'home.nav_condicoes' => 'Condiciones',
    'home.nav_devs' => 'Para devs',
    'home.nav_entrar' => 'Ingresar',
    'home.nav_contratar' => 'Contratar Ahora',
    'home.ver_planos_precos' => 'Ver Planes y Precios',
    'home.saiba_mais' => 'Saber mas',
    'home.footer_produto' => 'Producto',
    'home.footer_suporte' => 'Soporte',
    'home.footer_legal' => 'Legal',
    'home.footer_todos_operacionais' => 'Todos los sistemas operativos',

    // ── Categorias de apps ──
    'cat.cms' => 'CMS',
    'cat.backend' => 'Backend',
    'cat.database' => 'Base de Datos',
    'cat.webserver' => 'Servidor Web',
    'cat.dev' => 'Desarrollo',
    'cat.email' => 'Correo',
    'cat.other' => 'Otros',

    // ── Equipo ──
    'equipe.painel' => 'Panel',
    'equipe.clientes' => 'Clientes',
    'equipe.usuarios' => 'Usuarios',
    'equipe.servidores' => 'Servidores',
    'equipe.vps' => 'VPS',
    'equipe.aplicacoes' => 'Aplicaciones',
    'equipe.tickets' => 'Tickets',
    'equipe.chat' => 'Chat - Soporte',
    'equipe.chat_flows' => 'Flujos de Chat',
    'equipe.emails' => 'Correos',
    'equipe.monitoramento' => 'Monitoreo',
    'equipe.status' => 'Estado',
    'equipe.planos' => 'Planes',
    'equipe.assinaturas' => 'Suscripciones',
    'equipe.backups' => 'Backups',
    'equipe.jobs' => 'Jobs',
    'equipe.terminal' => 'Terminal',
    'equipe.erros' => 'Errores',
    'equipe.configuracoes' => 'Configuracion',
    'equipe.permissoes' => 'Permisos',
    'equipe.satisfacao' => 'Satisfaccion',
    'equipe.ajuda' => 'Ayuda',
    'equipe.inicializacao' => 'Inicializacion',
    'equipe.notificacoes' => 'Notificaciones',
    'equipe.operacoes' => 'Operaciones',

    // ── 2FA verificar ──
    '2fa.titulo_verificacao' => 'Verificacion en dos factores',
    '2fa.desc_verificacao' => 'Tu cuenta esta protegida con autenticacion en dos factores. Ingresa el codigo generado por tu aplicacion autenticadora para continuar.',
    '2fa.validade_30s' => 'Codigo valido por 30 segundos',
    '2fa.use_app' => 'Usa Google Authenticator, Authy o similar',
    '2fa.nao_compartilhe' => 'Nunca compartas tu codigo con nadie',
    '2fa.codigo_autenticador' => 'Codigo del autenticador',
    '2fa.abra_app' => 'Abre tu aplicacion autenticadora e ingresa el codigo de 6 digitos mostrado para esta cuenta.',
    '2fa.verificar_entrar' => 'Verificar e ingresar',
    '2fa.voltar_login' => '← Volver al login',

    // ── Terminal VPS ──
    'terminal.titulo' => 'Terminal VPS #%s',
    'terminal.subtitulo' => 'Sesion aislada dentro del contenedor',
    'terminal.abrir_sessao' => 'Abrir sesion',
    'terminal.auditado' => 'Todo es auditado. El acceso esta restringido al contenedor de tu VPS.',
    'terminal.conectar' => 'Conectar',
    'terminal.vps_nao_rodando' => 'VPS no esta en ejecucion (status=%s). El terminal estara disponible cuando este ejecutandose.',
    'terminal.upload' => '↑ Upload',
    'terminal.download' => '↓ Download',
    'terminal.desconectado' => 'Desconectado',
    'terminal.enviar_arquivo' => 'Enviar archivo a la VPS',
    'terminal.arquivo' => 'Archivo',
    'terminal.caminho_remoto' => 'Ruta remota',
    'terminal.baixar_arquivo' => 'Descargar archivo de la VPS',
    'terminal.baixar' => 'Descargar',
    'terminal.conexao_proxy' => 'Conexion via proxy reverso: /ws/terminal (WSS).',

    // ── Monitoreo detalle ──
    'monitoramento.titulo_vps' => 'Monitoreo — VPS #%s',
    'monitoramento.servidor' => 'Servidor',
    'monitoramento.ip' => 'IP',
    'monitoramento.coletas' => 'Recolecciones',
    'monitoramento.cpu_agora' => 'CPU ahora',
    'monitoramento.ram_agora' => 'RAM ahora',
    'monitoramento.disco_agora' => 'Disco ahora',
    'monitoramento.atualizacao_auto' => 'Actualizacion automatica cada 30s. Ultima:',
    'monitoramento.agora' => 'ahora',
    'monitoramento.historico' => 'Historial',
    'monitoramento.data_hora' => 'Fecha/Hora',
    'monitoramento.sem_metricas' => 'Aun no hay metricas.',
    'monitoramento.sem_node' => 'Esta VPS aun no tiene un nodo asociado para monitoreo.',

    // ── Estado cliente ──
    'status.suas_vps' => 'Tus VPS',
    'status.disponibilidade' => 'Disponibilidad de tus VPS',
    'status.uptime_24h' => 'Uptime (24h)',
    'status.historico' => 'Historial',
    'status.ultima_checagem' => 'Ultima verificacion',
    'status.sem_dados' => 'Sin datos aun.',
    'status.desconhecido' => 'Desconocido',
    'status.indisponivel' => 'No disponible',
    'status.monitorando' => 'Monitoreando',
    'status.identificado' => 'Identificado',
    'status.investigando' => 'Investigando',
    'status.critico' => 'Critico',
    'status.alto' => 'Alto',
    'status.baixo' => 'Bajo',
    'status.inicio' => 'Inicio',
    'status.resolvido_em' => 'Resuelto',
    'status.servicos_afetados' => 'Servicios afectados',
    'status.atualizacoes' => 'Actualizaciones',
    'status.nenhum_incidente' => 'Sin incidentes recientes.',

    // ── Suscripciones ──
    'assinaturas.cobrancas' => 'Cobros / Facturas',
    'assinaturas.id' => 'ID',
    'assinaturas.tipo' => 'Tipo',
    'assinaturas.link' => 'Enlace',
    'assinaturas.ver_fatura' => 'Ver factura',
    'assinaturas.nenhuma_ainda' => 'Sin suscripciones aun',
    'assinaturas.escolha_plano' => 'Elige un plan para comenzar.',
    'assinaturas.ver_planos' => 'Ver planes disponibles',
    'assinaturas.prox_vencimento' => 'Prox. vencimiento',
    'assinaturas.motivo' => 'Motivo',
    'assinaturas.motivo_placeholder' => 'Describe el motivo de la solicitud...',
    'assinaturas.enviar_solicitacao' => 'Enviar solicitud',
    'assinaturas.planos_cobrancas' => 'Planes, cobros y reembolsos',
    'assinaturas.mes' => 'mes',

    // ── Ayuda (FAQ) ──
    'ajuda.perguntas_frequentes' => 'Preguntas frecuentes',
    'ajuda.versao' => 'Preguntas frecuentes — v%s',
    'ajuda.secao_vps' => '🖥️ VPS',
    'ajuda.secao_email' => '📧 Correo',
    'ajuda.secao_chat' => '💬 Chat y Soporte',
    'ajuda.secao_apps' => '📦 Aplicaciones',
    'ajuda.secao_conta' => '🔐 Cuenta',

    // ── Header equipo ──
    'header.buscar' => 'Buscar...',
    'header.notificacoes' => 'Notificaciones',
    'header.seguranca_2fa' => 'Seguridad / 2FA',

    // ── Chat widget ──
    'widget.suporte' => 'Soporte',
    'widget.como_ajudar' => 'Como podemos ayudarte?',
    'widget.fechar' => 'Cerrar',
    'widget.abrir_suporte' => 'Abrir soporte',
    'widget.voltar' => '← Volver',
    'widget.ola' => 'Hola! Soy el asistente virtual. Como puedo ayudarte hoy?',
    'widget.tirar_duvida' => '💬 Hacer una pregunta',
    'widget.falar_atendente' => '🧑‍💻 Hablar con un agente',
    'widget.abrir_ticket' => '🎫 Abrir un ticket',
    'widget.enviar_email' => '📧 Enviar correo',
    'widget.conectando' => 'Conectando...',
    'widget.online' => '● En linea',
    'widget.chat_encerrado' => '● Chat finalizado',

    // ── Equipo — Panel ──
    'eq_painel.titulo' => 'Panel',
    'eq_painel.subtitulo' => 'Bienvenido de vuelta, %s.',
    'eq_painel.vps_ativas' => 'VPS Activas',
    'eq_painel.de_total' => 'de %s total',
    'eq_painel.clientes' => 'Clientes',
    'eq_painel.cadastrados' => 'registrados',
    'eq_painel.tickets_abertos' => 'Tickets Abiertos',
    'eq_painel.aguardando_resposta' => 'esperando respuesta',
    'eq_painel.jobs_pendentes' => 'Jobs Pendientes',
    'eq_painel.na_fila' => 'en cola',
    'eq_painel.nodes_online' => 'Nodes Online',
    'eq_painel.servidores_ativos' => 'servidores activos',
    'eq_painel.receita_mensal' => 'Ingreso Mensual',
    'eq_painel.assinaturas_ativas' => 'suscripciones activas',
    'eq_painel.acoes_rapidas' => 'Acciones rapidas',
    'eq_painel.gerenciar_vps' => 'Gestionar VPS',
    'eq_painel.ver_tickets' => 'Ver tickets',
    'eq_painel.seu_acesso' => 'Tu acceso',
    'eq_painel.seguranca' => 'Seguridad',
    'eq_painel.permissoes' => 'Permisos',
    'eq_painel.chat_vivo' => 'Chat en vivo',
    'eq_painel.inicializacao' => 'Inicializacion',

    // ── Equipo — Iniciar sesion ──
    'eq_entrar.titulo_painel' => 'Panel administrativo del equipo',
    'eq_entrar.desc_painel' => 'Acceso restringido. Usa tus credenciales de miembro del equipo para ingresar al panel de control.',
    'eq_entrar.2fa_disponivel' => 'Autenticacion de dos factores (2FA) disponible',
    'eq_entrar.controle_acesso' => 'Control de acceso por roles y permisos',
    'eq_entrar.auditoria' => 'Auditoria completa de acciones',
    'eq_entrar.sessao_expira' => 'Sesion con expiracion automatica',
    'eq_entrar.area_cliente' => 'Area del cliente →',
    'eq_entrar.acesso_equipe' => 'Acceso del equipo',
    'eq_entrar.desc_acesso' => 'Usa tu correo y contrasena para acceder al panel administrativo.',
    'eq_entrar.sessao_expirada' => 'Tu sesion expiro por inactividad. Inicia sesion nuevamente.',
    'eq_entrar.entrar_painel' => 'Ingresar al panel',
    'eq_entrar.voltar_inicio' => '← Volver al inicio',

    // ── Equipo — Tickets ──
    'eq_tickets.titulo' => 'Tickets',
    'eq_tickets.subtitulo' => 'Atencion e historial',
    'eq_tickets.buscar' => 'Buscar asunto o cliente...',
    'eq_tickets.todos_status' => 'Todos los estados',
    'eq_tickets.todas_prioridades' => 'Todas las prioridades',
    'eq_tickets.todos_departamentos' => 'Todos los departamentos',
    'eq_tickets.filtrar' => 'Filtrar',
    'eq_tickets.limpar' => 'Limpiar',
    'eq_tickets.cliente' => 'Cliente',
    'eq_tickets.assunto' => 'Asunto',
    'eq_tickets.dept' => 'Dept.',
    'eq_tickets.prioridade' => 'Prioridad',
    'eq_tickets.atribuido' => 'Asignado',
    'eq_tickets.atualizado' => 'Actualizado',
    'eq_tickets.abrir' => 'Abrir',
    'eq_tickets.nenhum' => 'No se encontraron tickets.',
    'eq_tickets.aberto' => 'Abierto',
    'eq_tickets.em_andamento' => 'En progreso',
    'eq_tickets.aguard_cliente' => 'Esperando cliente',
    'eq_tickets.fechado' => 'Cerrado',
    'eq_tickets.alta' => 'Alta',
    'eq_tickets.media' => 'Media',
    'eq_tickets.baixa' => 'Baja',

    // ── Equipo — Servidores ──
    'eq_servidores.titulo' => 'Servidores',
    'eq_servidores.subtitulo' => 'Nodos del cluster y capacidad disponible',
    'eq_servidores.cadastre' => 'Registra tus nodos y la capacidad total.',
    'eq_servidores.novo' => 'Nuevo servidor',
    'eq_servidores.hostname' => 'Hostname',
    'eq_servidores.cpu' => 'CPU',
    'eq_servidores.memoria' => 'Memoria',
    'eq_servidores.armazenamento' => 'Almacenamiento',
    'eq_servidores.setup' => 'Setup',
    'eq_servidores.ativo' => 'Activo',
    'eq_servidores.manutencao' => 'Mantenimiento',
    'eq_servidores.inativo' => 'Inactivo',
    'eq_servidores.online' => 'Online',
    'eq_servidores.offline' => 'Offline',
    'eq_servidores.pronto' => 'Listo',
    'eq_servidores.inicializando' => 'Inicializando…',
    'eq_servidores.erro' => 'Error',
    'eq_servidores.pendente' => 'Pendiente',
    'eq_servidores.editar' => 'Editar',
    'eq_servidores.continuar_setup' => 'Continuar setup',
    'eq_servidores.reiniciar' => 'Reiniciar',
    'eq_servidores.inicializar' => 'Inicializar',
    'eq_servidores.re_inicializar' => 'Re-inicializar',
    'eq_servidores.nenhum' => 'Ningun servidor registrado aun.',
    'eq_servidores.modal_titulo' => 'Inicializar servidor',
    'eq_servidores.modal_desc' => 'Conecta via SSH y prepara el servidor automaticamente: Docker, red lrv-net y usuario de terminal.',
    'eq_servidores.aguardando_inicio' => 'Esperando inicio…',
    'eq_servidores.inicializar_agora' => 'Inicializar ahora',
    'eq_servidores.modo_continuar' => 'Modo: continuar desde donde se detuvo.',
    'eq_servidores.clique_retomar' => 'Haz clic en el boton para reanudar.',
    'eq_servidores.clique_iniciar' => 'Haz clic en "Inicializar ahora" para comenzar.',
    'eq_servidores.servidor_pronto' => 'Servidor listo. Estado actualizado a Activo/Online.',
    'eq_servidores.setup_erros' => 'Setup completado con errores. Corrige y usa "Continuar desde donde se detuvo".',
    'eq_servidores.erro_comunicacao' => 'Error de comunicacion',
    'eq_servidores.etapas' => 'etapas',
    'eq_servidores.retomando' => 'Reanudando',
    'eq_servidores.iniciando' => 'Iniciando',

    // ── Equipo — Mi Cuenta ──
    'eq_conta.titulo' => 'Mi Cuenta',
    'eq_conta.subtitulo' => 'Administra tu informacion personal y contrasena',
    'eq_conta.info_pessoais' => 'Informacion personal',
    'eq_conta.foto_perfil' => 'Foto de perfil',
    'eq_conta.escolher_foto' => 'Elegir foto',
    'eq_conta.nenhum_arquivo' => 'Ningun archivo seleccionado',
    'eq_conta.nome' => 'Nombre',
    'eq_conta.alterar_senha' => 'Cambiar contrasena',
    'eq_conta.hint_senha' => '(dejar en blanco para no cambiar)',
    'eq_conta.senha_atual' => 'Contrasena actual',
    'eq_conta.nova_senha' => 'Nueva contrasena',
    'eq_conta.salvar' => 'Guardar cambios',
    'eq_conta.hint_avatar' => 'PNG, JPG, WEBP · max. 2 MB',

    // ── Equipo — Satisfaccion ──
    'eq_satisfacao.titulo' => 'Satisfaccion del Soporte',
    'eq_satisfacao.subtitulo' => 'Evaluaciones de tickets y chats cerrados',
    'eq_satisfacao.media_geral' => 'Promedio general',
    'eq_satisfacao.total_avaliacoes' => 'Total de evaluaciones',
    'eq_satisfacao.distribuicao' => 'Distribucion de notas',
    'eq_satisfacao.por_agente' => 'Por agente',
    'eq_satisfacao.agente' => 'Agente',
    'eq_satisfacao.avaliacoes' => 'Evaluaciones',
    'eq_satisfacao.media' => 'Promedio',
    'eq_satisfacao.positivas' => 'Positivas (≥4)',
    'eq_satisfacao.ultimas' => 'Ultimas evaluaciones',
    'eq_satisfacao.nenhuma' => 'Ninguna evaluacion registrada aun.',
    'eq_satisfacao.data' => 'Fecha',
    'eq_satisfacao.tipo' => 'Tipo',
    'eq_satisfacao.cliente' => 'Cliente',
    'eq_satisfacao.nota' => 'Nota',
    'eq_satisfacao.comentario' => 'Comentario',
    'eq_satisfacao.muito_ruim' => 'Muy malo',
    'eq_satisfacao.ruim' => 'Malo',
    'eq_satisfacao.regular' => 'Regular',
    'eq_satisfacao.bom' => 'Bueno',
    'eq_satisfacao.excelente' => 'Excelente',

    // ── Equipo — Jobs ──
    'eq_jobs.titulo' => 'Jobs',
    'eq_jobs.subtitulo' => 'Cola y logs (ultimos 200)',
    'eq_jobs.id' => 'ID',
    'eq_jobs.tipo' => 'Tipo',
    'eq_jobs.criado' => 'Creado',
    'eq_jobs.atualizado' => 'Actualizado',
    'eq_jobs.concluido' => 'Completado',
    'eq_jobs.falhou' => 'Fallo',
    'eq_jobs.rodando' => 'Ejecutando',
    'eq_jobs.pendente' => 'Pendiente',
    'eq_jobs.nenhum' => 'Ningun job encontrado.',
    'eq_jobs.dica' => 'Consejo: ejecuta <strong>php worker.php</strong> para procesar la cola.',

    // ── Equipo — Errores ──
    'eq_erros.titulo' => 'Errores del Sistema',
    'eq_erros.subtitulo' => 'Registro de errores HTTP, excepciones y fallos capturados',
    'eq_erros.total' => 'total',
    'eq_erros.pendentes' => 'pendientes',
    'eq_erros.codigo_http' => 'Codigo HTTP',
    'eq_erros.todos' => 'Todos',
    'eq_erros.tipo' => 'Tipo',
    'eq_erros.filtrar' => 'Filtrar',
    'eq_erros.limpar' => 'Limpiar',
    'eq_erros.limpar_resolvidos' => 'Limpiar resueltos',
    'eq_erros.nenhum' => 'Ningun error encontrado.',
    'eq_erros.codigo' => 'Codigo',
    'eq_erros.url' => 'URL',
    'eq_erros.mensagem' => 'Mensaje',
    'eq_erros.ip' => 'IP',
    'eq_erros.data' => 'Fecha',
    'eq_erros.resolvido' => 'Resuelto',
    'eq_erros.pendente' => 'Pendiente',
    'eq_erros.encontrados' => '%s error(es) encontrado(s)',
    'eq_erros.confirmar_limpar' => 'Eliminar todos los errores marcados como resueltos?',

    // ── Equipo — VPS ──
    'eq_vps.titulo' => 'VPS',
    'eq_vps.subtitulo' => 'Aprovisionamiento, estado y acciones',
    'eq_vps.cliente' => 'Cliente',
    'eq_vps.cpu_ram_disco' => 'CPU / RAM / Disco',
    'eq_vps.status' => 'Estado',
    'eq_vps.acoes' => 'Acciones',
    'eq_vps.node' => 'Nodo',
    'eq_vps.provisionar' => 'Aprovisionar',
    'eq_vps.reativar' => 'Reactivar',
    'eq_vps.reiniciar' => 'Reiniciar',
    'eq_vps.suspender' => 'Suspender',
    'eq_vps.remover' => 'Eliminar',
    'eq_vps.confirmar_remover' => 'Eliminar VPS #%s?',
    'eq_vps.nenhuma' => 'Ninguna VPS encontrada.',
    'eq_vps.em_execucao' => 'En ejecucion',
    'eq_vps.suspensa' => 'Suspendida',
    'eq_vps.aguard_pagamento' => 'Esperando pago',
    'eq_vps.aguard_node' => 'Esperando nodo',
    'eq_vps.prov_pendente' => 'Aprov. pendiente',
    'eq_vps.provisionando' => 'Aprovisionando',
    'eq_vps.erro' => 'Error',
    'eq_vps.removida' => 'Eliminada',

    // ── Equipo — Aplicaciones ──
    'eq_apps.titulo' => 'Aplicaciones',
    'eq_apps.subtitulo' => 'Apps vinculadas a VPS y puertos reservados',
    'eq_apps.desc' => 'Cree aplicaciones y reserve puertos únicos para exponer servicios.',
    'eq_apps.nova' => 'Nueva aplicación',
    'eq_apps.cliente' => 'Cliente',
    'eq_apps.tipo' => 'Tipo',
    'eq_apps.dominio' => 'Dominio',
    'eq_apps.porta' => 'Puerto',
    'eq_apps.status' => 'Estado',
    'eq_apps.acoes' => 'Acciones',
    'eq_apps.nenhuma' => 'Ninguna aplicación encontrada.',
    'eq_apps.confirmar_deploy' => '¿Iniciar deploy ahora?',
    'eq_apps.ativa' => 'Activa',
    'eq_apps.inativa' => 'Inactiva',
    'eq_apps.deploy' => 'Deploy',
    'eq_apps.erro' => 'Error',
    'eq_apps.catalogo' => 'Catálogo de plantillas',
    'eq_apps.catalogo_desc' => 'Plantillas disponibles para instalación con un clic por los clientes.',
    'eq_apps.requer_dominio' => 'Dominio',
    'eq_apps.requer_repo' => 'Repositorio',

    // ── Equipo — Planes ──
    'eq_planos.backup_slots' => 'Backups incluidos',
    'eq_planos.sem_backup' => 'Sin backup',

    // ── Equipo — Correos ──
    'eq_emails.titulo' => 'Correos',
    'eq_emails.subtitulo' => 'Cuentas de correo y dominios registrados por clientes',
    'eq_emails.abrir_webmail' => '🌐 Abrir Webmail',
    'eq_emails.buscar' => 'Buscar correo o cliente...',
    'eq_emails.contas' => 'Cuentas de correo',
    'eq_emails.nenhuma_conta' => 'Ninguna cuenta encontrada.',
    'eq_emails.quota' => 'Cuota',
    'eq_emails.criado_em' => 'Creado el',
    'eq_emails.remover' => 'Eliminar',
    'eq_emails.confirmar_remover_email' => 'Eliminar esta cuenta de correo?',
    'eq_emails.dominios_custom' => 'Dominios custom',
    'eq_emails.nenhum_dominio' => 'Ningun dominio registrado.',
    'eq_emails.dominio' => 'Dominio',
    'eq_emails.cadastrado_em' => 'Registrado el',
    'eq_emails.confirmar_remover_dominio' => 'Eliminar este dominio?',
    'eq_emails.operacao_sucesso' => 'Operacion realizada con exito.',
    'eq_emails.aguard_dns' => 'Esperando DNS',

    // ── Equipo — Estado ──
    'eq_status.titulo' => 'Estado',
    'eq_status.subtitulo' => 'Dashboard e incidentes',
    'eq_status.servicos_coletados' => 'Servicios recolectados',
    'eq_status.key' => 'Key',
    'eq_status.nome' => 'Nombre',
    'eq_status.scope' => 'Scope',
    'eq_status.cliente' => 'Cliente',
    'eq_status.node' => 'Nodo',
    'eq_status.ultima_checagem' => 'Ultima verificacion',
    'eq_status.sem_dados' => 'Sin datos aun. Inicia la recoleccion en Inicializacion.',
    'eq_status.criar_incidente' => 'Crear incidente',
    'eq_status.titulo_incidente' => 'Titulo',
    'eq_status.impacto' => 'Impacto',
    'eq_status.servicos_ids' => 'Servicios (IDs)',
    'eq_status.mensagem' => 'Mensaje',
    'eq_status.descreva' => 'Describe el incidente...',
    'eq_status.criar' => 'Crear incidente',
    'eq_status.incidentes' => 'Incidentes',
    'eq_status.nenhum_incidente' => 'Ningun incidente.',
    'eq_status.inicio' => 'Inicio',
    'eq_status.resolvido' => 'Resuelto',
    'eq_status.servicos_afetados' => 'Servicios afectados',
    'eq_status.salvar_servicos' => 'Guardar servicios',
    'eq_status.adicionar_update' => 'Agregar actualizacion',
    'eq_status.atualizacao_incidente' => 'Actualizacion del incidente...',
    'eq_status.ultimas_atualizacoes' => 'Ultimas actualizaciones',
    'eq_status.publico' => 'Publico',
    'eq_status.interno' => 'Interno',
    'eq_status.operacional' => 'Operativo',
    'eq_status.degradado' => 'Degradado',
    'eq_status.indisponivel' => 'No disponible',
    'eq_status.desconhecido' => 'Desconocido',
    'eq_status.investigando' => 'Investigando',
    'eq_status.identificado' => 'Identificado',
    'eq_status.monitorando' => 'Monitoreando',
    'eq_status.critico' => 'Critico',
    'eq_status.alto' => 'Alto',
    'eq_status.baixo' => 'Bajo',

    // ── Equipo — 2FA Configurar ──
    'eq_2fa.titulo' => 'Autenticacion de dos factores',
    'eq_2fa.subtitulo' => 'Protege tu cuenta con TOTP (Google Authenticator, Authy, etc.)',
    'eq_2fa.ativado' => '2FA activado',
    'eq_2fa.conta_protegida' => 'Tu cuenta esta protegida con autenticacion de dos factores.',
    'eq_2fa.desativar' => 'Desactivar 2FA',
    'eq_2fa.desc_desativar' => 'Para desactivar, confirma con el codigo de tu autenticador.',
    'eq_2fa.codigo_autenticador' => 'Codigo del autenticador',
    'eq_2fa.configurar' => 'Configurar autenticador',
    'eq_2fa.desc_configurar' => 'Escanea el codigo QR con tu app autenticadora o ingresa la clave manualmente.',
    'eq_2fa.chave_secreta' => 'Clave secreta (manual)',
    'eq_2fa.desc_app' => 'Usa Google Authenticator, Authy, Bitwarden o cualquier app TOTP compatible.',
    'eq_2fa.codigo_confirmar' => 'Codigo del autenticador para confirmar',
    'eq_2fa.ativar' => 'Activar 2FA',

    // ── Equipo — 2FA Verificar ──
    'eq_2fa_verificar.titulo' => 'Verificacion en dos factores',
    'eq_2fa_verificar.desc' => 'Tu cuenta esta protegida con autenticacion en dos factores. Ingresa el codigo generado por tu app autenticadora para continuar.',
    'eq_2fa_verificar.codigo_verificacao' => 'Codigo de verificacion',
    'eq_2fa_verificar.desc_codigo' => 'Abre tu app autenticadora e ingresa el codigo de 6 digitos mostrado para esta cuenta.',
    'eq_2fa_verificar.verificar_entrar' => 'Verificar e ingresar',
    'eq_2fa_verificar.voltar_login' => '← Volver al login',
    'eq_2fa_verificar.validade_30s' => 'Codigo valido por 30 segundos',
    'eq_2fa_verificar.use_app' => 'Usa Google Authenticator, Authy o similar',
    'eq_2fa_verificar.nao_compartilhe' => 'Nunca compartas tu codigo con nadie',

    // ── Equipo — Configuracion ──
    'eq_config.titulo' => 'Configuracion',
    'eq_config.subtitulo' => 'Pagos, webhooks, alertas e identidad visual',
    'eq_config.desc_banco' => 'Todo aqui se guarda en la base de datos (tabla <strong>settings</strong>). No usamos archivo <strong>.env</strong>.',
    'eq_config.salvas' => 'Configuracion guardada.',
    'eq_config.geral' => 'General',
    'eq_config.url_base' => 'URL base publica de la aplicacion',
    'eq_config.email_admin' => 'Correo del admin para alertas',
    'eq_config.secret_key' => 'Clave secreta de la aplicacion (app.secret_key)',
    'eq_config.gerar_chave' => 'Generar',
    'eq_config.hint_secret_key' => 'Usada para cifrar contrasenas SSH en la base de datos. Obligatoria para guardar servidores con autenticacion por contrasena. No cambiar despues de configurar.',
    'eq_config.identidade_visual' => 'Identidad Visual',
    'eq_config.nome_sistema' => 'Nombre del sistema',
    'eq_config.nome_empresa' => 'Nombre de la empresa',
    'eq_config.url_logo' => 'URL del logotipo',
    'eq_config.url_favicon' => 'URL del favicon',
    'eq_config.copyright_footer' => 'Texto de copyright (footer)',
    'eq_config.paginas_legais' => 'Paginas Legales',
    'eq_config.desc_legais' => 'HTML permitido. Accesible en',
    'eq_config.trial' => 'Prueba Gratis (Trial)',
    'eq_config.trial_desc' => 'Cuando esta activo, nuevos clientes reciben un servidor de prueba al crear cuenta.',
    'eq_config.trial_ativo' => 'Trial activo',
    'eq_config.duracao_dias' => 'Duracion (dias)',
    'eq_config.label_cta' => 'Label del boton CTA',
    'eq_config.desc_trial' => 'Descripcion del trial (mostrada en la home)',
    'eq_config.seo' => 'SEO e Indexacion',
    'eq_config.seo_desc' => 'Configuraciones para que Google y otros buscadores indexen correctamente el sitio publico.',
    'eq_config.salvar' => 'Guardar',

    // ── Chat equipo ──
    'chat_equipe.titulo' => 'Chat - Soporte',
    'chat_equipe.subtitulo' => 'Administra las conversaciones de soporte',
    'chat_equipe.abertos' => 'Chats abiertos',
    'chat_equipe.encerrados' => 'Chats cerrados',
    'chat_equipe.atender' => 'Atender',
    'chat_equipe.nenhum_aberto' => 'No hay chats abiertos en este momento.',
    'chat_equipe.nenhum_encerrado' => 'No hay chats cerrados.',
    'chat_equipe.cliente' => 'Cliente',
    'chat_equipe.agente' => 'Agente',
    'chat_equipe.iniciado_em' => 'Iniciado el',
    'chat_equipe.encerrado_em' => 'Cerrado el',
    'chat_equipe.sem_agente' => 'Sin agente',
    'chat_equipe.msgs' => 'Msgs',
    'chat_equipe.aberto_em' => 'Abierto el',
    'chat_equipe.ultima_ativ' => 'Ultima activ.',

    // ── Equipo — Ticket detalle ──
    'eq_ticket.mensagens' => 'Mensajes',
    'eq_ticket.nenhuma_msg' => 'Ningun mensaje aun.',
    'eq_ticket.responder' => 'Responder',
    'eq_ticket.sua_resposta' => 'Tu respuesta...',
    'eq_ticket.anexo' => 'Adjunto (opcional, max. 5 MB)',
    'eq_ticket.enviar_resposta' => 'Enviar respuesta',
    'eq_ticket.acoes' => 'Acciones',
    'eq_ticket.alterar_status' => 'Cambiar estado',
    'eq_ticket.atribuir_para' => 'Asignar a',
    'eq_ticket.ninguem' => 'Nadie',
    'eq_ticket.atribuir' => 'Asignar',
    'eq_ticket.ticket_fechado' => 'Ticket cerrado.',
    'eq_ticket.nenhuma_acao' => 'Ninguna accion disponible.',
    'eq_ticket.equipe' => 'Equipo',
    'eq_ticket.atualizado' => 'Actualizado',
    'eq_ticket.atribuido_a' => 'Asignado a',
    'eq_ticket.anexo_label' => 'Adjunto',

    // ── Home — Cuerpo ──
    'home.badge_trial' => 'Prueba gratis por %s dias disponible',
    'home.badge_servidores' => 'Servidores disponibles ahora',
    'home.hero_titulo' => 'Infraestructura VPS para',
    'home.hero_titulo_em' => 'escalar tu negocio',
    'home.hero_subtitulo' => 'Servidores VPS con recursos dedicados, proteccion DDoS nativa, uptime 99,9%% y soporte tecnico — activacion en hasta 6 dias habiles.',
    'home.servidor_destaque' => 'Servidor destacado',
    'home.processamento' => 'Procesamiento',
    'home.infra_dedicada' => 'Dedicada',
    'home.total_mensal' => 'Total mensual (servidor + backup)',
    'home.ddos_protection' => 'DDoS Protection',
    'home.ddos_ativada' => 'Activada por defecto',
    'home.uptime_sla' => 'SLA garantizado',
    'home.empresas_confiam' => 'Empresas que confian en %s',
    'home.stats_experiencia' => 'Experiencia en el mercado de infraestructura',
    'home.stats_clientes' => 'Clientes activos en todo Brasil',
    'home.stats_sla' => 'SLA de uptime garantizado en contrato',
    'home.stats_ativacao' => 'Activacion rapida de servidores',
    'home.porque' => 'Por que %s?',
    'home.melhor_infra' => 'La mejor infraestructura de Brasil',
    'home.sobre_desc' => '%s se especializa en servidores dedicados, hospedaje web e infraestructura digital. Tecnologia de punta con soporte humanizado, costos transparentes y escalabilidad real.',
    'home.sobre_desc2' => 'Nuestra infraestructura es base para sistemas empresariales, bases de datos, almacenamiento de archivos y soluciones de continuidad de negocios en todo Brasil.',
    'home.sobre_desc3' => 'Reajuste previsible basado en IGPM · Activacion en hasta 6 dias habiles · Trafico ilimitado incluido',
    'home.feat_desempenho' => 'Rendimiento Superior',
    'home.feat_desempenho_desc' => 'Procesadores Intel Xeon de ultima generacion para maximo throughput y minima latencia.',
    'home.feat_ddos' => 'Proteccion DDoS Nativa',
    'home.feat_ddos_desc' => 'Infraestructura blindada contra ataques volumetricos. Incluida en todos los planes.',
    'home.feat_conectividade' => 'Hiperconectividad',
    'home.feat_conectividade_desc' => 'Puertos de 1 a 10 Gbps con trafico ilimitado. Dentro del hub de conectividad de los DCs.',
    'home.feat_upgrades' => 'Upgrades sin Burocracia',
    'home.feat_upgrades_desc' => 'Escala recursos con rapidez. Ajusta CPU, RAM y almacenamiento bajo demanda.',
    'home.feat_hardware' => 'Hardware Exclusivo',
    'home.feat_hardware_desc' => 'Control total del servidor dedicado. Sin compartir, sin vecinos ruidosos.',
    'home.feat_custos' => 'Costos Transparentes',
    'home.feat_custos_desc' => 'Precios claros, sin tarifas ocultas. Reajuste anual por IGPM, siempre previsible.',

    // ── Home — Diferenciales ──
    'home.diff_titulo' => 'Diferenciales de los Servidores Dedicados %s',
    'home.diff_conectividade' => 'Conectividad',
    'home.diff_conectividade_desc' => 'Conexion directa con grandes redes como Akamai, CloudFlare, Microsoft, Google, AWS y UPX. Alcance a traves de los mayores peerings nacionales del IX.br. Transito por multiples operadoras en Brasil y el mundo.',
    'home.diff_kvm' => 'Consola/KVM',
    'home.diff_kvm_desc' => 'Panel intuitivo que brinda acceso externo al servidor (pantalla, teclado y mouse), permite montar ISOs en unidad virtual, encender, apagar y reiniciar el servidor, entre otras opciones.',
    'home.diff_resiliencia' => 'Resiliencia',
    'home.diff_resiliencia_desc' => 'Servidores con gran cantidad de recursos para altas demandas de uso sostenido o durante picos inesperados, sin cambios en la velocidad de respuesta.',
    'home.diff_io' => 'Rendimiento I/O',
    'home.diff_io_desc' => 'Latencia ultra baja en operaciones de lectura y escritura, incluso durante picos en cargas como bases de datos complejas o servidores de correo con gran flujo de mensajes.',
    'home.diff_rede' => 'Seguridad a nivel de red',
    'home.diff_rede_desc' => 'VLAN privada para trafico interno, VPN para integracion segura con su oficina, firewall dedicado para reglas de seguridad adecuadas y enlace punto a punto para interconectar oficinas (servicios adicionales).',
    'home.diff_backup' => 'Backup diario',
    'home.diff_backup_desc' => 'Sus datos almacenados en ambiente externo y a prueba de fallos. Seguridad total en casos de eliminacion indebida, corrupcion de base de datos, ransomware, entre otros (servicio adicional).',

    // ── Home — Planes ──
    'home.plans_titulo' => 'Elige el ideal para tu proyecto',
    'home.plans_sub' => 'Servidores VPS con recursos dedicados y escalables. Todos los planes incluyen proteccion DDoS y SSL gratuito.',
    'home.plans_comparar' => 'Comparar todos los planes',
    'home.plans_moeda' => '$',
    'home.plans_por_mes' => 'por mes',
    'home.plans_ddos' => 'Proteccion DDoS',
    'home.plans_ssl' => 'SSL gratuito',
    'home.plans_suporte' => 'Soporte especializado',
    'home.plans_addons' => 'Servicios adicionales',
    'home.plans_total' => 'Valor total',
    'home.plans_empty' => 'Planes proximamente.',
    'home.plans_empty_contato' => 'Contactenos',
    'home.plans_empty_saber' => 'para saber mas.',
    'home.plans_help_titulo' => 'Necesitas ayuda para decidir o mas recursos?',
    'home.plans_help_sub' => 'Hablanos para un plan personalizado',
    'home.plans_help_btn' => 'Hablar con Especialista',

    // ── Home — Condiciones ──
    'home.cond_eyebrow' => 'Transparencia total',
    'home.cond_titulo' => 'Condiciones Generales de los Servicios',
    'home.cond_sub' => 'Todo lo que necesitas saber antes de contratar. Sin letra pequena, sin sorpresas en la factura.',
    'home.cond_01' => 'Todos los valores incluyen los debidos <strong>impuestos segun la legislacion vigente</strong>.',
    'home.cond_02' => 'Servicios <strong>prepagos</strong>. El cobro inicia despues de la activacion. Primera factura proporcional con vencimiento en <strong>5 dias</strong>.',
    'home.cond_03' => 'Facturas mensuales enviadas con <strong>15 dias de anticipacion</strong>, pago exclusivamente por boleta bancaria.',
    'home.cond_04' => 'Reajuste anual basado en el <strong>IGPM</strong> al final de cada periodo de 12 meses de vigencia.',
    'home.cond_05' => '<strong>Renovacion automatica</strong> por periodos iguales si no hay contestacion con <strong>60 dias</strong> de anticipacion.',
    'home.cond_06' => 'Rescision anticipada: multa de <strong>50%% del valor mensual x meses restantes</strong> acordados en la propuesta.',
    'home.cond_07' => '<strong>Plazo de activacion SP1</strong>: 1 servidor = 6 dias habiles. Regiones PR1/CE1: +5 dias habiles adicionales.',
    'home.cond_08' => '<strong>Backup BaaS</strong> activado en hasta 4 dias habiles adicionales al plazo del servidor contratado.',
    'home.cond_09' => 'Cancelacion o downgrade debe ser <strong>comunicado con 60 dias</strong> de anticipacion a la suspension.',
    'home.cond_10' => 'Esta estrictamente prohibido el <strong>alojamiento de juegos</strong> para garantia de rendimiento de conectividad.',

    // ── Home — Testimonios ──
    'home.dep_eyebrow' => 'Testimonios',
    'home.dep_titulo' => 'Lo que dicen nuestros clientes',
    'home.dep_1' => '%s nos dio todo el soporte cuando enfrentamos un incidente critico. En ese momento teniamos todo el data center on-premise interno, y ahora toda nuestra infraestructura esta con ellos. Nuestra alianza ya tiene mas de 2 anos y la idea es continuar por mucho tiempo. Estamos muy contentos con la atencion prestada.',
    'home.dep_2' => '%s es el principal proveedor de tecnologia de Akahosting. Fundamentamos una alianza y en menos de un ano conseguimos ver el extremo exito en nuestra operacion. Gracias a ellos nuestra empresa logro impulsar mucho los negocios. Estamos agradecidos por el soporte en todas las ocasiones.',
    'home.dep_3' => 'Trabajabamos con proveedores de servidor fuera de Brasil, conocimos a %s y trajimos toda nuestra infraestructura para aca. Estamos con ellos hace algunos anos y nuestra evolucion conjunta es constante. Estamos muy satisfechos y planeamos extender esta alianza cada vez mas.',
    'home.dep_4' => 'La migracion a %s fue decisiva para nuestra operacion. El proceso fue transparente, el equipo tecnico siempre disponible y el rendimiento supero nuestras expectativas. Con el servidor dedicado redujimos latencia y aumentamos capacidad sin aumentar los costos.',

    // ── Home — CTA Final ──
    'home.cta_pronto' => 'Listo para comenzar?',
    'home.cta_trial_titulo' => 'Comienza tu prueba gratis',
    'home.cta_trial_titulo_em' => 'ahora mismo',
    'home.cta_trial_sub' => 'Crea tu cuenta y prueba la plataforma gratuitamente por %s dias, sin tarjeta de credito.',
    'home.cta_falar_equipe' => 'Hablar con el equipo',
    'home.cta_ative_titulo' => 'Activa tu servidor en',
    'home.cta_ative_titulo_em' => 'hasta 6 dias habiles',
    'home.cta_ative_sub' => 'Contactanos ahora y recibe una propuesta personalizada. Nuestro equipo tecnico esta listo para atenderte.',
    'home.cta_proposta' => 'Solicitar Propuesta por Email',
    'home.cta_consultor' => 'Hablar con Consultor',

    // ── Home — Footer ──
    'home.footer_desc' => 'Infraestructura cloud de alto rendimiento con proteccion DDoS, backups automaticos y soporte especializado.',
    'home.footer_sobre' => 'Acerca de',
    'home.footer_planos' => 'Planes',
    'home.footer_condicoes' => 'Condiciones',
    'home.footer_devs' => 'Para devs',
    'home.footer_contato' => 'Contacto',
    'home.footer_status' => 'Estado del sistema',
    'home.footer_tickets' => 'Tickets',
    'home.footer_ajuda' => 'Centro de ayuda',
    'home.footer_termos' => 'Terminos de uso',
    'home.footer_privacidade' => 'Privacidad',
    'home.footer_sistema_op' => 'Todos los sistemas operativos',
    'home.hero_preco_mes' => '/mes',
    'home.stats_num_exp' => '+5 anos',
    'home.stats_num_clientes' => '+200',
    'home.stats_num_sla' => '99,9%',
    'home.stats_num_ativacao' => '6 dias',
    'home.clients_logos' => 'Startups,E-commerce,SaaS,Agencias,Desarrolladores',

    // ── Equipo — Chat detalle ──
    'eq_chat_ver.aberto' => 'Abierto',
    'eq_chat_ver.encerrado' => 'Cerrado',
    'eq_chat_ver.encerrar' => 'Finalizar chat',
    'eq_chat_ver.confirmar_encerrar' => 'Finalizar este chat?',
    'eq_chat_ver.chat_encerrado' => 'Este chat fue cerrado.',
    'eq_chat_ver.enviar' => 'Enviar',
    'eq_chat_ver.placeholder' => 'Escribe tu mensaje...',
    'eq_chat_ver.carregando' => 'Cargando mensajes...',
    'eq_chat_ver.cancelar_arquivo' => 'Cancelar archivo',
    'eq_chat_ver.emojis' => 'Emojis',
    'eq_chat_ver.enviar_arquivo' => 'Enviar archivo',
    'eq_chat_ver.cliente_label' => 'Cliente',
    'eq_chat_ver.nome' => 'Nombre',
    'eq_chat_ver.email' => 'Correo',
    'eq_chat_ver.cadastro' => 'Registro',
    'eq_chat_ver.ver_perfil' => 'Ver perfil completo',
    'eq_chat_ver.nao_encontrado' => 'Cliente no encontrado.',
    'eq_chat_ver.assinaturas' => 'Suscripciones',
    'eq_chat_ver.plano' => 'Plan',
    'eq_chat_ver.nenhuma_assinatura' => 'Sin suscripciones.',
    'eq_chat_ver.vps' => 'VPS',
    'eq_chat_ver.nenhuma_vps' => 'Sin VPS.',
    'eq_chat_ver.tickets_recentes' => 'Tickets recientes',
    'eq_chat_ver.nenhum_ticket' => 'Sin tickets.',

    // ── Equipo — Servidor editar ──
    'eq_srv_edit.titulo_novo' => 'Nuevo servidor',
    'eq_srv_edit.titulo_editar' => 'Editar servidor',
    'eq_srv_edit.conectividade' => 'Conectividad',
    'eq_srv_edit.acoes' => 'Acciones',
    'eq_srv_edit.testar_ssh' => 'Probar conexion SSH',
    'eq_srv_edit.continuar_setup' => 'Continuar setup',
    'eq_srv_edit.re_inicializar' => 'Re-inicializar',
    'eq_srv_edit.inicializar' => 'Inicializar servidor',
    'eq_srv_edit.hostname' => 'Hostname',
    'eq_srv_edit.status' => 'Estado',
    'eq_srv_edit.ativo' => 'Activo',
    'eq_srv_edit.manutencao' => 'Mantenimiento',
    'eq_srv_edit.inativo' => 'Inactivo',
    'eq_srv_edit.ip' => 'Direccion IP',
    'eq_srv_edit.porta_ssh' => 'Puerto SSH',
    'eq_srv_edit.auth_ssh' => 'Autenticacion SSH',
    'eq_srv_edit.usuario_senha' => 'Usuario y contrasena',
    'eq_srv_edit.chave_ssh' => 'Clave SSH',
    'eq_srv_edit.usuario_ssh' => 'Usuario SSH',
    'eq_srv_edit.senha_ssh' => 'Contrasena SSH',
    'eq_srv_edit.manter_branco' => '(dejar en blanco para mantener)',
    'eq_srv_edit.id_chave' => 'Identificador de la clave SSH',
    'eq_srv_edit.hint_chave' => 'Nombre del archivo dentro del directorio configurado en',
    'eq_srv_edit.upload_chave' => 'Clave privada SSH (subir archivo)',
    'eq_srv_edit.hint_upload_chave' => 'Suba el archivo de clave privada (.pem, id_rsa, etc). El archivo se guardara en el directorio de claves del sistema.',
    'eq_srv_edit.hint_substituir_chave' => 'Suba un nuevo archivo para reemplazar la clave actual.',
    'eq_srv_edit.chave_configurada' => 'Clave configurada',
    'eq_srv_edit.upload_chave_terminal' => 'Clave privada del terminal (subir archivo)',
    'eq_srv_edit.hint_upload_terminal' => 'Suba la clave privada del terminal seguro. Dejar en blanco para desactivar.',
    'eq_srv_edit.usar_sudo' => 'Usar sudo',
    'eq_srv_edit.hint_sudo' => 'Marca si el usuario SSH no es root y necesita sudo para instalar paquetes.',
    'eq_srv_edit.senha_sudo' => 'Contrasena de sudo',
    'eq_srv_edit.hint_sudo_branco' => '(dejar en blanco para usar la misma contrasena SSH)',
    'eq_srv_edit.hint_nopasswd' => 'Si sudo no pide contrasena (NOPASSWD), dejar en blanco tambien.',
    'eq_srv_edit.terminal_seguro' => 'Terminal seguro (clientes)',
    'eq_srv_edit.terminal_desc' => 'Sesiones de terminal del cliente via',
    'eq_srv_edit.usuario_terminal' => 'Usuario SSH del terminal',
    'eq_srv_edit.chave_terminal' => 'Identificador de la clave del terminal',
    'eq_srv_edit.hint_terminal' => 'Dejar en blanco para desactivar terminal seguro en este nodo.',
    'eq_srv_edit.passo_a_passo' => 'Paso a paso en el nodo',
    'eq_srv_edit.cpu_total' => 'CPU total (vCPUs)',
    'eq_srv_edit.ram_total' => 'Memoria total (MB)',
    'eq_srv_edit.storage_total' => 'Almacenamiento total (MB)',
    'eq_srv_edit.salvar' => 'Guardar servidor',

    // ── Equipo — Terminal ──
    'eq_terminal.titulo' => 'Terminal (Admin)',
    'eq_terminal.subtitulo' => 'Acceso SSH al nodo via WebSocket',
    'eq_terminal.subtitulo_http' => 'Acceso SSH al nodo via HTTP — sin necesidad de WebSocket',
    'eq_terminal.escolha_node' => 'Elige un nodo y conecta. Todo es auditado.',
    'eq_terminal.node' => 'Nodo',
    'eq_terminal.selecione' => 'Seleccionar...',
    'eq_terminal.conectar' => 'Conectar',
    'eq_terminal.desconectado' => 'Desconectado',
    'eq_terminal.conectado_http' => 'Conectado (HTTP)',
    'eq_terminal.executando' => 'Ejecutando...',
    'eq_terminal.sessao_iniciada' => 'Sesión iniciada. Cada comando se ejecuta via SSH.',
    'eq_terminal.dica_http' => 'Consejo: usa "cd /ruta && comando" para ejecutar en otro directorio.',
    'eq_terminal.selecione_node' => 'Selecciona un nodo primero.',
    'eq_terminal.nao_conectado' => 'No conectado.',
    'eq_terminal.inativo' => 'inactivo',
    'eq_terminal.preencha_upload' => 'Selecciona un archivo e ingresa la ruta.',
    'eq_terminal.enviando' => 'Enviando...',
    'eq_terminal.http_hint' => 'Cada comando se ejecuta individualmente via SSH. Para comandos interactivos, configura WebSocket.',
    'eq_terminal.upload' => 'Upload',
    'eq_terminal.download' => 'Download',
    'eq_terminal.enviar_arquivo' => 'Enviar archivo al servidor',
    'eq_terminal.arquivo' => 'Archivo',
    'eq_terminal.caminho_remoto' => 'Ruta remota',
    'eq_terminal.enviar' => 'Enviar',
    'eq_terminal.cancelar' => 'Cancelar',
    'eq_terminal.baixar_arquivo' => 'Descargar archivo del servidor',
    'eq_terminal.baixar' => 'Descargar',
    'eq_terminal.placeholder' => 'Escribe un comando y presiona Enter',
    'eq_terminal.proxy_hint' => 'Conexion via proxy reverso:',

    // ── Equipo — Cliente detalle ──
    'eq_cliente.clientes' => 'Clientes',
    'eq_cliente.editar_dados' => 'Editar datos',
    'eq_cliente.dados_cadastrais' => 'Datos de registro',
    'eq_cliente.telefone' => 'Telefono',
    'eq_cliente.celular' => 'Celular',
    'eq_cliente.cpf_cnpj' => 'ID Fiscal',
    'eq_cliente.cadastro' => 'Registro',
    'eq_cliente.endereco' => 'Direccion',
    'eq_cliente.assinar_plano' => 'Asignar plan manualmente',
    'eq_cliente.plano' => 'Plan',
    'eq_cliente.assinar' => 'Asignar plan',
    'eq_cliente.vps' => 'VPS',
    'eq_cliente.container' => 'Container',
    'eq_cliente.cpu_ram_disco' => 'CPU / RAM / Disco',
    'eq_cliente.nenhum_vps' => 'Ningun VPS registrado.',
    'eq_cliente.assinaturas' => 'Suscripciones',
    'eq_cliente.valor_mes' => 'Valor/mes',
    'eq_cliente.prox_vencimento' => 'Prox. vencimiento',
    'eq_cliente.criada' => 'Creada',
    'eq_cliente.nenhuma_assinatura' => 'Sin suscripciones.',
    'eq_cliente.assinatura_criada' => 'Suscripcion creada con exito.',
    'eq_cliente.ativa' => 'Activa',
    'eq_cliente.suspensa' => 'Suspendida',
    'eq_cliente.cancelada' => 'Cancelada',
    'eq_cliente.ativo' => 'Activo',
    'eq_cliente.parado' => 'Detenido',
    'eq_cliente.suspenso' => 'Suspendido',
    'eq_cliente.assinaturas_ativas' => 'suscripcion(es) activa(s)',

    // ── Equipo — Inicializacion ──
    'eq_init.titulo' => 'Asistente de inicializacion',
    'eq_init.subtitulo' => 'Verificaciones y acciones para dejar el servidor listo',
    'eq_init.erro' => 'Error',
    'eq_init.acao_executada' => 'Accion ejecutada.',
    'eq_init.status' => 'Estado',
    'eq_init.item' => 'Item',
    'eq_init.detalhe' => 'Detalle',
    'eq_init.ok' => 'OK',
    'eq_init.pendente' => 'Pendiente',
    'eq_init.migrations_pendentes' => 'Migraciones pendientes:',
    'eq_init.acoes' => 'Acciones',
    'eq_init.aplicar_schema' => 'Aplicar schema.sql',
    'eq_init.aplicar_migrations' => 'Aplicar migraciones',
    'eq_init.criar_diretorios' => 'Crear directorios',
    'eq_init.gerar_tokens' => 'Generar tokens/defaults',
    'eq_init.processar_job' => 'Procesar 1 job',
    'eq_init.coletar_status' => 'Recolectar estado (1x)',
    'eq_init.enfileirar' => 'Encolar',
    'eq_init.coleta_continua' => 'Iniciar recoleccion continua',
    'eq_init.iniciar' => 'Iniciar',
    'eq_init.testar_nodes' => 'Probar conectividad de nodos',
    'eq_init.executar' => 'Ejecutar',
    'eq_init.terminal_ws' => 'Terminal WS (Admin)',
    'eq_init.instalar_deps' => 'Instalar dependencias (composer)',
    'eq_init.iniciar_daemon' => 'Iniciar daemon',
    'eq_init.parar_daemon' => 'Detener daemon',
    'eq_init.nodes_cadastrados' => 'Nodos registrados',
    'eq_init.nodes_desc' => 'Esta lista muestra el estado y el ultimo resultado de conectividad (SSH + docker version).',
    'eq_init.host' => 'Host',
    'eq_init.ultima_checagem' => 'Ultima verificacion',
    'eq_init.ultimo_erro' => 'Ultimo error',
    'eq_init.nenhum_node' => 'Ningun nodo registrado aun.',
    'eq_init.worker_http' => 'Worker via HTTP (sin CLI)',
    'eq_init.worker_desc' => 'Endpoint para ejecutar 1 job (ideal para cron externo). Autenticacion por header',
    'eq_init.testar_worker' => 'Probar (ejecutar 1 job via HTTP)',
    'eq_init.logs' => 'Logs',
    'eq_init.obs_deploy' => 'Nota: para Deploy/Backups el servidor necesita ssh y scp disponibles y PHP con shell_exec habilitado.',

    // ── Equipo — Ayuda ──
    'eq_ajuda.subtitulo' => 'Configuracion y operacion',

    // ── Infraestructura (pagina publica) ──
    'infra.nav_funcionalidades' => 'Funcionalidades',
    'infra.nav_planos' => 'Planes',
    'infra.nav_tecnologia' => 'Tecnologia',
    'infra.nav_status' => 'Estado',
    'infra.nav_contato' => 'Contacto',
    'infra.nav_entrar' => 'Ingresar',
    'infra.nav_criar_conta' => 'Crear cuenta',
    'infra.hero_eyebrow' => 'Plataforma Cloud SaaS',
    'infra.hero_titulo' => 'Infraestructura cloud',
    'infra.hero_titulo_grad' => 'simple y poderosa',
    'infra.hero_sub' => 'Aprovisiona VPS, despliega aplicaciones, gestiona correos, backups y soporte en un unico panel. Todo automatizado, seguro y listo para escalar.',
    'infra.hero_criar_conta' => 'Crear cuenta gratis',
    'infra.hero_ver_planos' => 'Ver planes →',
    'infra.badge_deploy' => 'Deploy automatizado',
    'infra.badge_backups' => 'Backups automaticos',
    'infra.badge_suporte' => 'Soporte via chat y tickets',
    'infra.badge_monitoramento' => 'Monitoreo 24/7',
    'infra.badge_terminal' => 'Terminal web integrado',
    'infra.stat_uptime' => 'Uptime garantizado',
    'infra.stat_provisioning' => 'Aprovisionamiento',
    'infra.stat_monitoring' => 'Monitoreo',
    'infra.stat_encryption' => 'Encriptacion',
    'infra.feat_label' => 'Funcionalidades',
    'infra.feat_titulo' => 'Todo lo que necesitas en un lugar',
    'infra.feat_sub' => 'Del aprovisionamiento al soporte, cada recurso fue pensado para simplificar tu operacion.',
    'infra.feat_vps' => 'VPS Gestionadas',
    'infra.feat_vps_desc' => 'Aprovisiona, suspende, reinicia y monitorea tus VPS con pocos clics.',
    'infra.feat_terminal' => 'Terminal Web',
    'infra.feat_terminal_desc' => 'Accede al terminal SSH directamente desde el navegador. Auditoria completa de comandos.',
    'infra.feat_deploy' => 'Deploy de Aplicaciones',
    'infra.feat_deploy_desc' => 'Despliega aplicaciones Docker con un clic. Logs en tiempo real y rollback facil.',
    'infra.feat_backups' => 'Backups Automaticos',
    'infra.feat_backups_desc' => 'Backups programados con descarga directa. Retencion configurable y restauracion con un clic.',
    'infra.feat_monitor' => 'Monitoreo',
    'infra.feat_monitor_desc' => 'CPU, memoria y disco en tiempo real. Alertas automaticas por correo y WhatsApp.',
    'infra.feat_email' => 'Correos Profesionales',
    'infra.feat_email_desc' => 'Crea cuentas en tu propio dominio. Integracion con Mailcow y webmail incluido.',
    'infra.feat_suporte' => 'Soporte Integrado',
    'infra.feat_suporte_desc' => 'Chat en vivo y sistema de tickets con historial completo de atenciones.',
    'infra.feat_planos' => 'Planes Flexibles',
    'infra.feat_planos_desc' => 'Elige el plan ideal para tu proyecto. Upgrade o downgrade en cualquier momento.',
    'infra.feat_2fa' => '2FA y Seguridad',
    'infra.feat_2fa_desc' => 'Autenticacion de dos factores, RBAC por roles, auditoria completa y proteccion CSRF.',
    'infra.steps_label' => 'Como funciona',
    'infra.steps_titulo' => 'De cero al aire en minutos',
    'infra.steps_sub' => 'Sin configuraciones complejas. Tu infraestructura lista para produccion en 4 pasos.',
    'infra.step1_titulo' => 'Crea tu cuenta',
    'infra.step1_desc' => 'Registro rapido, sin tarjeta de credito para comenzar.',
    'infra.step2_titulo' => 'Elige un plan',
    'infra.step2_desc' => 'Selecciona los recursos que tu proyecto necesita.',
    'infra.step3_titulo' => 'VPS aprovisionada',
    'infra.step3_desc' => 'Tu servidor se crea automaticamente en menos de 60 segundos.',
    'infra.step4_titulo' => 'Gestiona todo',
    'infra.step4_desc' => 'Terminal, deploy, backups, correos y soporte en un unico panel.',
    'infra.plans_label' => 'Planes',
    'infra.plans_titulo' => 'Precios transparentes, sin sorpresas',
    'infra.plans_sub' => 'Elige el plan ideal para tu proyecto. Todos incluyen soporte, backups y monitoreo.',
    'infra.plans_mensal' => 'Cobro mensual',
    'infra.plans_anual' => 'Cobro anual',
    'infra.plans_backups' => 'Backups automaticos',
    'infra.plans_monitor' => 'Monitoreo 24/7',
    'infra.plans_suporte' => 'Soporte via chat y tickets',
    'infra.plans_comecar' => 'Comenzar ahora',
    'infra.plans_empty' => 'Planes proximamente.',
    'infra.plans_contato' => 'Contactanos',
    'infra.plans_saber_mais' => 'para saber mas.',
    'infra.plans_custom' => 'Necesitas algo personalizado?',
    'infra.plans_fale' => 'Habla con el equipo',
    'infra.plans_popular' => 'Mas popular',
    'infra.plans_mes' => '/mes',
    'infra.plans_ano' => '/ano',
    'infra.plans_moeda' => '$',
    'infra.tech_label' => 'Tecnologia',
    'infra.tech_titulo' => 'Stack moderno y confiable',
    'infra.tech_sub' => 'Construido con las mejores tecnologias para garantizar rendimiento, seguridad y escalabilidad.',
    'infra.tech_php' => 'PHP 8.3 + MVC propio',
    'infra.tech_php_desc' => 'Framework MVC personalizado, sin overhead de dependencias externas. Rapido y predecible.',
    'infra.tech_mysql' => 'MySQL con prepared statements',
    'infra.tech_mysql_desc' => 'Todas las queries usan prepared statements. Zero ORM, control total sobre la base de datos.',
    'infra.tech_docker' => 'Docker y SSH remoto',
    'infra.tech_docker_desc' => 'Aprovisionamiento y deploy via SSH. Containers Docker gestionados directamente desde el panel.',
    'infra.tech_ws' => 'WebSocket en tiempo real',
    'infra.tech_ws_desc' => 'Terminal web y chat en vivo via WebSocket. Latencia minima, experiencia fluida.',
    'infra.tech_sec' => 'Seguridad en capas',
    'infra.tech_sec_desc' => 'CSRF, RBAC, 2FA TOTP, rate limiting, replay attack protection y auditoria completa.',
    'infra.tech_mail' => 'Mailcow integrado',
    'infra.tech_mail_desc' => 'Gestion de correos via API Mailcow. Dominios propios, webmail y DNS automatico.',
    'infra.sec_label' => 'Seguridad',
    'infra.sec_titulo' => 'Tu infraestructura protegida',
    'infra.sec_sub' => 'Multiples capas de seguridad para proteger tus datos y operaciones.',
    'infra.sec_2fa' => 'Autenticacion 2FA (TOTP)',
    'infra.sec_2fa_desc' => 'Proteccion extra con autenticacion de dos factores via Google Authenticator o similar.',
    'infra.sec_rbac' => 'RBAC por roles',
    'infra.sec_rbac_desc' => 'Control granular de permisos por rol: superadmin, admin, devops, dev y soporte.',
    'infra.sec_csrf' => 'Proteccion CSRF y Rate Limit',
    'infra.sec_csrf_desc' => 'Tokens CSRF en todos los formularios y rate limiting por IP para prevenir abusos.',
    'infra.sec_audit' => 'Auditoria completa',
    'infra.sec_audit_desc' => 'Log de todas las acciones del equipo y clientes. Trazabilidad total para compliance.',
    'infra.faq_label' => 'FAQ',
    'infra.faq_titulo' => 'Preguntas frecuentes',
    'infra.faq_sub' => 'Resuelve tus dudas sobre la plataforma.',
    'infra.faq1_q' => 'Necesito tarjeta de credito para comenzar?',
    'infra.faq1_a' => 'No. Puedes crear tu cuenta y explorar el panel gratuitamente. La tarjeta solo es necesaria al suscribir un plan pago.',
    'infra.faq2_q' => 'En cuanto tiempo mi VPS esta lista?',
    'infra.faq2_a' => 'El aprovisionamiento es automatico y toma menos de 60 segundos despues de la confirmacion del pago.',
    'infra.faq3_q' => 'Puedo hacer upgrade o downgrade del plan?',
    'infra.faq3_a' => 'Si. Puedes cambiar tu plan en cualquier momento desde el panel. El cambio se aplica inmediatamente.',
    'infra.faq4_q' => 'Los backups son automaticos?',
    'infra.faq4_a' => 'Si. Los backups se programan automaticamente segun el plan. Tambien puedes crear backups manuales y descargarlos en cualquier momento.',
    'infra.faq5_q' => 'Como funciona el soporte?',
    'infra.faq5_a' => 'El soporte se realiza via chat en vivo y sistema de tickets directamente en el panel. Nuestro equipo responde en horario comercial.',
    'infra.access_label' => 'Acceso',
    'infra.access_titulo' => 'Elige tu perfil',
    'infra.access_sub' => 'Area del cliente o panel administrativo — cada uno con su espacio.',
    'infra.access_cliente' => 'Area del cliente',
    'infra.access_cliente_desc' => 'Accede a tus VPS, aplicaciones, correos, backups, monitoreo y soporte.',
    'infra.access_admin' => 'Panel administrativo',
    'infra.access_admin_desc' => 'Gestiona clientes, servidores, cobros, tickets y toda la infraestructura.',
    'infra.access_entrar_equipe' => 'Ingresar como equipo',
    'infra.cta_trial' => 'Comienza tu prueba gratis ahora',
    'infra.cta_pronto' => 'Listo para comenzar?',
    'infra.cta_sub' => 'Crea tu cuenta ahora y ten tu infraestructura funcionando en minutos.',
    'infra.cta_falar' => 'Hablar con el equipo',
    'infra.footer_desc' => 'Plataforma cloud SaaS para gestion de VPS, aplicaciones, correos y soporte.',
    'infra.footer_col_produto' => 'Producto',
    'infra.footer_col_suporte' => 'Soporte',
    'infra.footer_col_legal' => 'Legal',
    'infra.footer_funcionalidades' => 'Funcionalidades',
    'infra.footer_planos' => 'Planes',
    'infra.footer_tecnologia' => 'Tecnologia',
    'infra.footer_contato' => 'Contacto',
    'infra.footer_status' => 'Estado del sistema',
    'infra.footer_tickets' => 'Tickets',
    'infra.footer_termos' => 'Terminos de uso',
    'infra.footer_privacidade' => 'Privacidad',
    'infra.footer_sistema_op' => 'Todos los sistemas operativos',
    'infra.cta_criar_conta' => 'Crear cuenta gratis',
    'infra.access_entrar' => 'Ingresar',

    // ── Licencia (pagina publica) ──
    'licenca.label' => 'Legal',
    'licenca.titulo' => 'Licencia de Uso Propietaria',
    'licenca.subtitulo' => 'Este documento establece los terminos y condiciones de uso del software LRV Cloud Manager.',
    'licenca.nav_termos' => 'Terminos',
    'licenca.nav_privacidade' => 'Privacidad',
    'licenca.nav_contato' => 'Contacto',

    // ── Changelog ──
    'changelog.label' => 'Historial de versiones',
    'changelog.titulo' => 'Changelog',
    'changelog.sub' => 'Sigue todas las novedades, mejoras y correcciones del sistema.',

    // ── Contacto ──
    'contato.label' => 'Contáctenos',
    'contato.titulo' => 'Contacto',
    'contato.sub' => '¿Tiene alguna duda o necesita ayuda? Envíenos un mensaje y le responderemos pronto.',
    'contato.nome' => 'Nombre',
    'contato.email' => 'Correo electrónico',
    'contato.assunto' => 'Asunto',
    'contato.mensagem' => 'Mensaje',
    'contato.enviar' => 'Enviar mensaje',
    'contato.ph_nome' => 'Su nombre',
    'contato.ph_email' => 'su@email.com',
    'contato.ph_assunto' => '¿Cómo podemos ayudar?',
    'contato.ph_mensagem' => 'Describa su duda o solicitud...',

    // ── Status ──
    'status_page.label' => 'Transparencia operacional',
    'status_page.titulo' => 'Estado del sistema',
    'status_page.servicos' => 'Servicios',
    'status_page.auto_refresh' => 'Actualización automática cada 30s',
    'status_page.th_servico' => 'Servicio',
    'status_page.th_status' => 'Estado',
    'status_page.th_uptime' => 'Uptime 24h',
    'status_page.th_historico' => 'Historial',
    'status_page.th_checagem' => 'Última verificación',
    'status_page.nenhum_servico' => 'Ningún servicio configurado aún.',
    'status_page.incidentes' => 'Incidentes recientes',
    'status_page.nenhum_incidente' => 'Ningún incidente reciente. Todo funcionando normalmente.',
    'status_page.inicio' => 'Inicio:',
    'status_page.resolvido' => 'Resuelto:',
    'status_page.operacional' => 'Operacional',
    'status_page.degradado' => 'Degradado',
    'status_page.indisponivel' => 'No disponible',
    'status_page.desconhecido' => 'Desconocido',
    'status_page.resolvido_badge' => 'Resuelto',
    'status_page.monitorando' => 'Monitoreando',
    'status_page.identificado' => 'Identificado',
    'status_page.investigando' => 'Investigando',
    'status_page.critico' => 'Crítico',
    'status_page.alto' => 'Alto',
    'status_page.baixo' => 'Bajo',

    // ── Status Incidentes ──
    'status_inc.nenhum' => 'Ningún incidente registrado.',
    'status_inc.anterior' => '← Anterior',
    'status_inc.proxima' => 'Siguiente →',
    'status_inc.pagina' => 'Página %d de %d',
    'status_inc.titulo' => 'Historial de incidentes',
    'status_inc.sub' => 'Vea el historial completo de incidentes y mantenimientos.',

    // ── Términos ──
    'termos.label' => 'Legal',
    'termos.titulo' => 'Términos de Uso',
    'termos.sub' => 'Lea con atención los términos que rigen el uso de la plataforma.',
    'termos.vazio' => 'Los términos de uso aún no han sido configurados. Contacte al administrador.',

    // ── Privacidad ──
    'privacidade.label' => 'Legal',
    'privacidade.titulo' => 'Política de Privacidad',
    'privacidade.sub' => 'Sepa cómo recopilamos, usamos y protegemos sus datos.',
    'privacidade.vazio' => 'La política de privacidad aún no ha sido configurada. Contacte al administrador.',

    // ── Stripe Checkout ──
    'stripe.sucesso_titulo' => 'Pago confirmado',
    'stripe.sucesso_sub' => 'Su suscripción ha sido activada con éxito.',
    'stripe.erro_tentar' => 'Intentar de nuevo',
    'stripe.detalhes' => 'Detalles de la suscripción',
    'stripe.plano' => 'Plan',
    'stripe.valor' => 'Valor',
    'stripe.prox_cobranca' => 'Próx. cobro',
    'stripe.status' => 'Estado',
    'stripe.ativa' => 'Activa',
    'stripe.vps_vinculada' => 'VPS vinculada',
    'stripe.proximos_passos' => 'Próximos pasos:',
    'stripe.passo_1' => 'Su VPS será aprovisionada automáticamente en unos minutos.',
    'stripe.passo_2' => 'Recibirá las credenciales de acceso en el panel.',
    'stripe.passo_3' => 'Si tiene dudas, abra un ticket de soporte.',
    'stripe.ver_vps' => 'Ver mis VPS',
    'stripe.ver_assinaturas' => 'Ver suscripciones',
    'stripe.cancelado_titulo' => 'Checkout cancelado',
    'stripe.cancelado_sub' => 'Ha cancelado el checkout. No se generó ningún cobro.',
    'stripe.escolher_plano' => 'Elegir otro plan',
    'stripe.voltar_planos' => 'Ver planes',

    // ── Checkout ──
    'checkout.forma_pagamento' => 'Forma de pago',
    'checkout.cartao' => 'Tarjeta',

    // ── Chat Flows ──
    'chat_flows.titulo' => 'Flujos de Chat',
    'chat_flows.subtitulo' => 'Gestione secuencias automatizadas de mensajes',
    'chat_flows.novo_fluxo' => 'Nuevo Flujo',
    'chat_flows.editar_fluxo' => 'Editar Flujo',
    'chat_flows.dados_fluxo' => 'Datos del Flujo',
    'chat_flows.nome' => 'Nombre',
    'chat_flows.descricao' => 'Descripcion',
    'chat_flows.gatilho' => 'Disparador',
    'chat_flows.trigger_inatividade' => 'Inactividad del cliente',
    'chat_flows.trigger_encerramento' => 'Cierre del chat',
    'chat_flows.trigger_manual' => 'Manual',
    'chat_flows.passos' => 'Pasos',
    'chat_flows.tipo' => 'Tipo',
    'chat_flows.conteudo' => 'Contenido',
    'chat_flows.tipo_mensagem' => 'Mensaje',
    'chat_flows.tipo_atraso' => 'Retraso',
    'chat_flows.tipo_acao' => 'Accion',
    'chat_flows.segundos' => 'Segundos',
    'chat_flows.acao_fechar_chat' => 'Cerrar chat',
    'chat_flows.acao_enviar_satisfacao' => 'Enviar enlace de satisfaccion',
    'chat_flows.adicionar_passo' => 'Agregar Paso',
    'chat_flows.adicionar' => 'Agregar',
    'chat_flows.confirmar_excluir' => 'Esta seguro de que desea eliminar este flujo?',
    'chat_flows.confirmar_remover_passo' => 'Esta seguro de que desea eliminar este paso?',
    'chat_flows.nenhum_passo' => 'Ningun paso configurado.',
    'chat_flows.historico_execucoes' => 'Historial de Ejecuciones',
    'chat_flows.nenhuma_execucao' => 'Ninguna ejecucion registrada.',
    'chat_flows.sala' => 'Sala',
    'chat_flows.origem' => 'Origen',
    'chat_flows.iniciado_em' => 'Iniciado en',
    'chat_flows.concluido_em' => 'Completado en',
    'chat_flows.timeout_inatividade' => 'Tiempo de inactividad',
    'chat_flows.minutos' => 'minutos',
    'chat_flows.fluxos' => 'Flujos',
    'chat_flows.disparar_fluxo' => 'Disparar flujo manual',
    'chat_flows.sistema' => 'Sistema',
];
