<?php

return [
    // ── Navbar pública ──
    'nav.inicio' => 'Início',
    'nav.produtos' => 'Produtos',
    'nav.infraestrutura' => 'Infraestrutura',
    'nav.recursos' => 'Recursos',
    'nav.planos' => 'Planos',
    'nav.status' => 'Status',
    'nav.contato' => 'Contato',
    'nav.entrar' => 'Entrar',
    'nav.contratar' => 'Contratar Agora',
    'nav.changelog' => 'Changelog',
    'nav.termos' => 'Termos de uso',
    'nav.privacidade' => 'Privacidade',
    'nav.licenca' => 'Licença',

    // Mega: Produtos
    'mega.prod_infra' => 'Infraestrutura',
    'mega.prod_vps' => 'VPS Gerenciada',
    'mega.prod_vps_desc' => 'Servidores virtuais com painel completo',
    'mega.prod_enterprise' => 'VPS Enterprise',
    'mega.prod_enterprise_desc' => 'Alta performance para projetos críticos',
    'mega.prod_dedicado' => 'Servidores Dedicados',
    'mega.prod_dedicado_desc' => 'Hardware exclusivo sob demanda',
    'mega.prod_apps' => 'Aplicações',
    'mega.prod_wordpress' => 'WordPress Gerenciado',
    'mega.prod_wordpress_desc' => 'Deploy otimizado para WordPress',
    'mega.prod_nodejs' => 'APIs Node.js',
    'mega.prod_nodejs_desc' => 'Ambientes prontos para Node',
    'mega.prod_php' => 'Sistemas PHP',
    'mega.prod_php_desc' => 'Laravel, Symfony e mais',
    'mega.prod_python' => 'Apps Python',
    'mega.prod_python_desc' => 'Django, Flask e automações',
    'mega.prod_deploy' => 'Deploy automático',
    'mega.prod_deploy_desc' => 'CI/CD integrado via Git',
    'mega.prod_devops' => 'Dev & Ops',
    'mega.prod_terminal' => 'Terminal Web (SSH)',
    'mega.prod_terminal_desc' => 'Acesso direto pelo navegador',
    'mega.prod_monitor' => 'Monitoramento',
    'mega.prod_monitor_desc' => 'CPU, RAM, disco em tempo real',
    'mega.prod_backups' => 'Backups automáticos',
    'mega.prod_backups_desc' => 'Agendados e sob demanda',
    'mega.prod_logs' => 'Logs e métricas',
    'mega.prod_logs_desc' => 'Histórico completo de operações',
    'mega.prod_comm' => 'Comunicação',
    'mega.prod_email' => 'E-mail profissional',
    'mega.prod_email_desc' => 'Domínio próprio com Mailcow',
    'mega.prod_chat' => 'Chat em tempo real',
    'mega.prod_chat_desc' => 'Suporte direto pelo painel',
    'mega.prod_tickets' => 'Suporte técnico',
    'mega.prod_tickets_desc' => 'Tickets e central de ajuda',
    'mega.prod_ver_todos' => 'Ver todos os produtos',

    // Mega: Infraestrutura
    'mega.infra_como' => 'Como funciona',
    'mega.infra_como_desc' => 'Arquitetura e tecnologia',
    'mega.infra_seguranca' => 'Segurança',
    'mega.infra_seguranca_desc' => '2FA, RBAC, criptografia AES-256',
    'mega.infra_sla' => 'SLA / Uptime',
    'mega.infra_sla_desc' => '99,9% de disponibilidade garantida',
    'mega.infra_dc' => 'Data Centers',
    'mega.infra_dc_desc' => 'Infraestrutura Tier III+',

    // Mega: Recursos
    'mega.rec_perf' => 'Performance',
    'mega.rec_alta_disp' => 'Alta disponibilidade',
    'mega.rec_balanceamento' => 'Balanceamento de carga',
    'mega.rec_seg' => 'Segurança',
    'mega.rec_isolamento' => 'Isolamento por container',
    'mega.rec_ddos' => 'Proteção DDoS',
    'mega.rec_backups' => 'Backups automáticos',
    'mega.rec_monit' => 'Monitoramento',
    'mega.rec_status' => 'Status em tempo real',
    'mega.rec_metricas' => 'Métricas CPU/RAM/Disco',
    'mega.rec_alertas' => 'Alertas',
    'mega.rec_exp' => 'Experiência',
    'mega.rec_painel' => 'Painel intuitivo',
    'mega.rec_deploy' => 'Deploy fácil',
    'mega.rec_cli' => 'Terminal Web',

    // ── Páginas de soluções (landing pages) ──
    // Compartilhado
    'sol.section_beneficios' => 'Por que escolher a LRV?',
    'sol.section_como_funciona' => 'Simples assim',
    'sol.section_faq' => 'Perguntas frequentes',
    'sol.section_prova' => 'Quem já confia na LRV',
    'sol.passo1' => 'Crie sua conta',
    'sol.passo1_desc' => 'Cadastro rápido, sem burocracia. Leva menos de 1 minuto.',
    'sol.passo2' => 'Nós configuramos tudo',
    'sol.passo2_desc' => 'Nossa equipe prepara o ambiente ideal para o seu negócio.',
    'sol.passo3' => 'Você usa tranquilo',
    'sol.passo3_desc' => 'Foque no que importa. A infraestrutura fica por nossa conta.',
    'sol.cta_planos' => 'Ver planos',
    'sol.cta_contato' => 'Falar com especialista',
    'sol.cta_final_titulo' => 'Pronto para dar o próximo passo?',
    'sol.cta_final_desc' => 'Escolha o plano ideal ou fale com nossa equipe. Sem compromisso.',
    'sol.depoimento1_nome' => 'Ricardo Mendes',
    'sol.depoimento1_cargo' => 'CEO, TechStart',
    'sol.depoimento1_texto' => 'Migramos toda nossa operação para a LRV e a diferença foi imediata. Mais velocidade, menos dor de cabeça.',
    'sol.depoimento2_nome' => 'Camila Ferreira',
    'sol.depoimento2_cargo' => 'Diretora de TI, Agência Pixel',
    'sol.depoimento2_texto' => 'O suporte é excepcional. Qualquer problema é resolvido em minutos, não em dias.',
    'sol.depoimento3_nome' => 'André Oliveira',
    'sol.depoimento3_cargo' => 'CTO, SaaS Express',
    'sol.depoimento3_texto' => 'Finalmente uma infraestrutura que acompanha nosso crescimento sem complicação.',

    // VPS
    'sol.vps_titulo' => 'Infraestrutura confiável para o crescimento da sua empresa',
    'sol.vps_subtitulo' => 'Servidores rápidos, seguros e gerenciados. Sem se preocupar com tecnologia.',
    'sol.vps_cta' => 'Começar agora',
    'sol.vps_problema_titulo' => 'Cansado de problemas com hospedagem?',
    'sol.vps_problema_desc' => 'Site lento, fora do ar no pior momento, suporte que demora dias para responder. Você já passou por isso. Seu negócio merece uma infraestrutura que funcione de verdade.',
    'sol.vps_solucao_titulo' => 'Com a LRV, você não precisa entender de servidor',
    'sol.vps_solucao_desc' => 'Nós cuidamos de toda a parte técnica. Você só precisa focar no seu negócio. Servidores configurados, monitorados e protegidos 24 horas por dia.',
    'sol.vps_b1_titulo' => 'Alta performance',
    'sol.vps_b1_desc' => 'Seu site e sistemas carregam rápido, sem travamentos.',
    'sol.vps_b2_titulo' => 'Disponibilidade 99,9%',
    'sol.vps_b2_desc' => 'Seu negócio online 24 horas, sem surpresas.',
    'sol.vps_b3_titulo' => 'Suporte humano',
    'sol.vps_b3_desc' => 'Fale com pessoas reais que resolvem de verdade.',
    'sol.vps_b4_titulo' => 'Backups diários',
    'sol.vps_b4_desc' => 'Seus dados protegidos. Restauração com um clique.',
    'sol.vps_b5_titulo' => 'Monitoramento 24h',
    'sol.vps_b5_desc' => 'Sabemos de qualquer problema antes de você.',
    'sol.vps_b6_titulo' => 'Cresce com você',
    'sol.vps_b6_desc' => 'Aumente recursos quando precisar, sem migração.',
    'sol.vps_faq1_p' => 'Preciso saber configurar servidor?',
    'sol.vps_faq1_r' => 'Não. Nós cuidamos de toda a configuração. Você só usa.',
    'sol.vps_faq2_p' => 'Vocês ajudam na migração?',
    'sol.vps_faq2_r' => 'Sim. Nossa equipe migra seus sites e sistemas sem custo adicional.',
    'sol.vps_faq3_p' => 'E se meu site crescer muito?',
    'sol.vps_faq3_r' => 'Você pode aumentar os recursos a qualquer momento, sem downtime.',
    'sol.vps_faq4_p' => 'Posso cancelar quando quiser?',
    'sol.vps_faq4_r' => 'Sim. Sem multa, sem fidelidade. Cancele quando quiser.',

    // Aplicações
    'sol.apps_titulo' => 'Coloque seu projeto no ar em minutos',
    'sol.apps_subtitulo' => 'WordPress, loja virtual, sistema web. Instale com um clique e comece a vender.',
    'sol.apps_cta' => 'Ver aplicações disponíveis',
    'sol.apps_problema_titulo' => 'Colocar um site no ar não deveria ser complicado',
    'sol.apps_problema_desc' => 'Configurar servidor, instalar dependências, resolver erros. Tudo isso toma tempo e exige conhecimento técnico que nem todo mundo tem.',
    'sol.apps_solucao_titulo' => 'Na LRV, é só escolher e clicar',
    'sol.apps_solucao_desc' => 'Nosso catálogo de aplicações permite instalar WordPress, sistemas web e muito mais com um único clique. Sem configuração manual.',
    'sol.apps_b1_titulo' => 'Instalação em 1 clique',
    'sol.apps_b1_desc' => 'Escolha a aplicação e pronto. Nós fazemos o resto.',
    'sol.apps_b2_titulo' => 'Atualizações automáticas',
    'sol.apps_b2_desc' => 'Seu sistema sempre atualizado e seguro.',
    'sol.apps_b3_titulo' => 'Publicação rápida',
    'sol.apps_b3_desc' => 'Envie seu código e ele vai ao ar automaticamente.',
    'sol.apps_b4_titulo' => 'Compatível com tudo',
    'sol.apps_b4_desc' => 'WordPress, lojas, APIs, sistemas internos e mais.',
    'sol.apps_b5_titulo' => 'Sem conhecimento técnico',
    'sol.apps_b5_desc' => 'Feito para quem quer resultado, não complicação.',
    'sol.apps_b6_titulo' => 'Suporte incluso',
    'sol.apps_b6_desc' => 'Precisa de ajuda? Estamos aqui para você.',
    'sol.apps_faq1_p' => 'Preciso saber programar?',
    'sol.apps_faq1_r' => 'Não. As aplicações são instaladas automaticamente.',
    'sol.apps_faq2_p' => 'Posso instalar meu próprio sistema?',
    'sol.apps_faq2_r' => 'Sim. Além do catálogo, você pode publicar qualquer projeto.',
    'sol.apps_faq3_p' => 'E se eu precisar de ajuda?',
    'sol.apps_faq3_r' => 'Nosso suporte está disponível por chat, ticket e e-mail.',
    'sol.apps_faq4_p' => 'Tem limite de aplicações?',
    'sol.apps_faq4_r' => 'Depende do seu plano. Mas todos permitem múltiplas aplicações.',

    // Dev & Ops
    'sol.devops_titulo' => 'Controle total sem complicação',
    'sol.devops_subtitulo' => 'Gerencie, monitore e automatize sua operação em um painel simples e poderoso.',
    'sol.devops_cta' => 'Conhecer as ferramentas',
    'sol.devops_problema_titulo' => 'Gerenciar infraestrutura não precisa ser um pesadelo',
    'sol.devops_problema_desc' => 'Acessar servidores por linha de comando, verificar logs manualmente, descobrir problemas tarde demais. Isso consome tempo e gera riscos.',
    'sol.devops_solucao_titulo' => 'Tudo no seu navegador, tudo sob controle',
    'sol.devops_solucao_desc' => 'Com a LRV, você acessa terminais, monitora recursos e recebe alertas direto pelo painel. Sem instalar nada, sem complicação.',
    'sol.devops_b1_titulo' => 'Acesso pelo navegador',
    'sol.devops_b1_desc' => 'Gerencie seus servidores de qualquer lugar.',
    'sol.devops_b2_titulo' => 'Monitoramento em tempo real',
    'sol.devops_b2_desc' => 'Saiba exatamente como seus recursos estão sendo usados.',
    'sol.devops_b3_titulo' => 'Backups automáticos',
    'sol.devops_b3_desc' => 'Seus dados protegidos sem precisar lembrar.',
    'sol.devops_b4_titulo' => 'Alertas inteligentes',
    'sol.devops_b4_desc' => 'Receba avisos antes que problemas afetem seu negócio.',
    'sol.devops_b5_titulo' => 'Histórico completo',
    'sol.devops_b5_desc' => 'Veja tudo que aconteceu, quando e por quem.',
    'sol.devops_b6_titulo' => 'Publicação automática',
    'sol.devops_b6_desc' => 'Atualize seu sistema com um simples envio de código.',
    'sol.devops_faq1_p' => 'Preciso instalar algum programa?',
    'sol.devops_faq1_r' => 'Não. Tudo funciona direto no navegador.',
    'sol.devops_faq2_p' => 'Consigo ver o que está acontecendo em tempo real?',
    'sol.devops_faq2_r' => 'Sim. O painel mostra uso de recursos, status e alertas ao vivo.',
    'sol.devops_faq3_p' => 'E se algo der errado?',
    'sol.devops_faq3_r' => 'Você recebe alertas automáticos e pode restaurar backups com um clique.',
    'sol.devops_faq4_p' => 'Minha equipe pode usar também?',
    'sol.devops_faq4_r' => 'Sim. Você pode criar acessos com permissões diferentes para cada pessoa.',

    // E-mail
    'sol.email_titulo' => 'E-mail com o nome da sua empresa',
    'sol.email_subtitulo' => 'Transmita profissionalismo em cada mensagem. E-mail @suaempresa.com pronto para usar.',
    'sol.email_cta' => 'Criar meu e-mail profissional',
    'sol.email_problema_titulo' => 'Ainda usando e-mail gratuito para o seu negócio?',
    'sol.email_problema_desc' => 'E-mails com @gmail ou @hotmail passam uma imagem amadora. Seus clientes percebem. Seus concorrentes já usam domínio próprio.',
    'sol.email_solucao_titulo' => 'Profissionalismo que gera confiança',
    'sol.email_solucao_desc' => 'Com e-mail @suaempresa.com, você transmite credibilidade em cada mensagem. Configuração simples, sem dor de cabeça.',
    'sol.email_b1_titulo' => 'Seu domínio, sua marca',
    'sol.email_b1_desc' => 'E-mails com o nome da sua empresa em todas as mensagens.',
    'sol.email_b2_titulo' => 'Acesse de qualquer lugar',
    'sol.email_b2_desc' => 'Pelo navegador, celular ou programa de e-mail favorito.',
    'sol.email_b3_titulo' => 'Sem spam',
    'sol.email_b3_desc' => 'Filtros inteligentes mantêm sua caixa de entrada limpa.',
    'sol.email_b4_titulo' => 'Funciona com tudo',
    'sol.email_b4_desc' => 'Outlook, Gmail, celular. Compatível com qualquer dispositivo.',
    'sol.email_b5_titulo' => 'Fácil de gerenciar',
    'sol.email_b5_desc' => 'Crie e remova contas direto pelo painel, sem complicação.',
    'sol.email_b6_titulo' => 'Seguro e confiável',
    'sol.email_b6_desc' => 'Seus e-mails protegidos com criptografia e backups.',
    'sol.email_faq1_p' => 'Preciso ter um domínio?',
    'sol.email_faq1_r' => 'Sim. Se ainda não tem, podemos ajudar você a registrar um.',
    'sol.email_faq2_p' => 'Consigo usar no celular?',
    'sol.email_faq2_r' => 'Sim. Funciona em qualquer app de e-mail do celular.',
    'sol.email_faq3_p' => 'Quantas contas posso criar?',
    'sol.email_faq3_r' => 'Depende do seu plano. Todos permitem múltiplas contas.',
    'sol.email_faq4_p' => 'Vocês configuram para mim?',
    'sol.email_faq4_r' => 'Sim. Nossa equipe ajuda na configuração completa.',

    // Segurança
    'sol.seg_titulo' => 'Seu negócio protegido 24 horas por dia',
    'sol.seg_subtitulo' => 'Segurança de verdade, sem complicação. Proteção em todas as camadas para você dormir tranquilo.',
    'sol.seg_cta' => 'Proteger meu negócio',
    'sol.seg_problema_titulo' => 'Um ataque pode custar caro',
    'sol.seg_problema_desc' => 'Dados vazados, site fora do ar, clientes perdidos. Um incidente de segurança pode causar prejuízos enormes e destruir a confiança que você levou anos para construir.',
    'sol.seg_solucao_titulo' => 'Proteção profissional sem precisar ser especialista',
    'sol.seg_solucao_desc' => 'Na LRV, a segurança já vem configurada. Seus dados ficam isolados, protegidos e monitorados automaticamente.',
    'sol.seg_b1_titulo' => 'Ambiente isolado',
    'sol.seg_b1_desc' => 'Seus dados ficam separados de outros clientes. Ninguém acessa o que é seu.',
    'sol.seg_b2_titulo' => 'Verificação em duas etapas',
    'sol.seg_b2_desc' => 'Uma camada extra de proteção para acessar sua conta.',
    'sol.seg_b3_titulo' => 'Controle de acessos',
    'sol.seg_b3_desc' => 'Defina quem pode ver e fazer o quê na sua conta.',
    'sol.seg_b4_titulo' => 'Dados criptografados',
    'sol.seg_b4_desc' => 'Informações sensíveis protegidas com criptografia de nível bancário.',
    'sol.seg_b5_titulo' => 'Registro de atividades',
    'sol.seg_b5_desc' => 'Saiba tudo que acontece na sua conta, quando e por quem.',
    'sol.seg_b6_titulo' => 'Proteção contra ataques',
    'sol.seg_b6_desc' => 'Defesas automáticas contra as ameaças mais comuns da internet.',
    'sol.seg_faq1_p' => 'Preciso configurar a segurança?',
    'sol.seg_faq1_r' => 'Não. Tudo já vem configurado e ativo desde o primeiro dia.',
    'sol.seg_faq2_p' => 'Meus dados ficam seguros?',
    'sol.seg_faq2_r' => 'Sim. Usamos criptografia e isolamento para proteger tudo.',
    'sol.seg_faq3_p' => 'E se alguém tentar invadir?',
    'sol.seg_faq3_r' => 'Nossas defesas automáticas bloqueiam tentativas de ataque em tempo real.',
    'sol.seg_faq4_p' => 'Posso controlar quem acessa minha conta?',
    'sol.seg_faq4_r' => 'Sim. Você define permissões diferentes para cada pessoa da sua equipe.',

    // ── Footer público ──
    'footer.desc' => 'Infraestrutura cloud gerenciada. VPS, deploy, e-mails, backups e suporte em um único painel.',
    'footer.produto' => 'Produto',
    'footer.funcionalidades' => 'Funcionalidades',
    'footer.planos' => 'Planos',
    'footer.changelog' => 'Changelog',
    'footer.status' => 'Status',
    'footer.suporte' => 'Suporte',
    'footer.contato' => 'Contato',
    'footer.central_ajuda' => 'Central de ajuda',
    'footer.tickets' => 'Tickets',
    'footer.legal' => 'Legal',
    'footer.termos' => 'Termos de uso',
    'footer.privacidade' => 'Privacidade',
    'footer.licenca' => 'Licença de uso',
    'footer.sistemas_op' => 'Todos os sistemas operacionais',
    'footer.cookies' => 'Cookies',

    // ── Cookies / Consentimento ──
    'cookies.titulo' => 'Utilizamos cookies',
    'cookies.descricao' => 'Este site utiliza cookies para melhorar sua experiência de navegação. Você pode aceitar todos, rejeitar os opcionais ou configurar suas preferências.',
    'cookies.saiba_mais' => 'Saiba mais',
    'cookies.aceitar_todos' => 'Aceitar todos',
    'cookies.rejeitar_opcionais' => 'Rejeitar opcionais',
    'cookies.configurar' => 'Configurar',
    'cookies.config_titulo' => 'Preferências de cookies',
    'cookies.config_desc' => 'Escolha quais categorias de cookies deseja permitir. Cookies necessários são sempre ativos para garantir o funcionamento do sistema.',
    'cookies.cat_necessarios' => 'Necessários',
    'cookies.cat_necessarios_desc' => 'Essenciais para autenticação, sessão e segurança. Não podem ser desativados.',
    'cookies.cat_analytics' => 'Analytics',
    'cookies.cat_analytics_desc' => 'Nos ajudam a entender como o site é utilizado para melhorar a experiência.',
    'cookies.cat_marketing' => 'Marketing',
    'cookies.cat_marketing_desc' => 'Utilizados para exibir conteúdo relevante e medir campanhas.',
    'cookies.cat_preferencias' => 'Preferências',
    'cookies.cat_preferencias_desc' => 'Armazenam configurações como idioma e tema escolhido.',
    'cookies.salvar_prefs' => 'Salvar preferências',
    'cookies.privacidade_texto' => 'Utilizamos cookies para garantir o funcionamento do sistema, melhorar a experiência de navegação e, quando autorizado, analisar o uso do site. Você pode gerenciar suas preferências a qualquer momento.',

    // ── Status público ──
    'status.todos_operacionais' => 'Todos os sistemas operacionais',
    'status.degradacao' => 'Degradação parcial detectada',
    'status.indisponivel' => 'Indisponibilidade em andamento',
    'status.desconhecido' => 'Status desconhecido',

    // ── Geral ──
    'geral.erro_interno' => 'Erro interno.',
    'geral.rota_nao_encontrada' => 'Rota não encontrada.',
    'geral.salvar' => 'Salvar',
    'geral.cancelar' => 'Cancelar',
    'geral.voltar' => 'Voltar',
    'geral.excluir' => 'Excluir',
    'geral.editar' => 'Editar',
    'geral.novo' => 'Novo',
    'geral.ver' => 'Ver',
    'geral.fechar' => 'Fechar',
    'geral.enviar' => 'Enviar',
    'geral.confirmar' => 'Confirmar',
    'geral.sim' => 'Sim',
    'geral.nao' => 'Não',
    'geral.ativo' => 'Ativo',
    'geral.inativo' => 'Inativo',
    'geral.status' => 'Status',
    'geral.acoes' => 'Ações',
    'geral.carregando' => 'Carregando...',
    'geral.nenhum_resultado' => 'Nenhum resultado encontrado.',
    'geral.area_cliente' => 'Área do cliente',
    'geral.area_equipe' => 'Painel administrativo',
    'geral.sair' => 'Sair',
    'geral.minha_conta' => 'Minha Conta',
    'geral.configuracoes_salvas' => 'Configurações salvas.',
    'geral.erro_formulario' => 'Corrija os erros abaixo.',
    'geral.processando' => 'Processando...',
    'geral.copyright' => '© %s LRV Web',
    'geral.recolher_menu' => 'Recolher menu',
    'geral.expandir_menu' => 'Expandir menu',
    'geral.menu' => 'Menu',

    // ── Auth ──
    'auth.entrar' => 'Entrar',
    'auth.email' => 'E-mail',
    'auth.senha' => 'Senha',
    'auth.esqueci_senha' => 'Esqueci minha senha',
    'auth.criar_conta' => 'Criar conta',
    'auth.ja_tem_conta' => 'Já tem conta?',
    'auth.nao_tem_conta' => 'Não tem conta?',
    'auth.nome' => 'Nome completo',
    'auth.credenciais_invalidas' => 'E-mail ou senha incorretos.',
    'auth.conta_criada' => 'Conta criada com sucesso.',
    'auth.logout_sucesso' => 'Você saiu com sucesso.',

    // ── Reset de senha ──
    'reset.titulo' => 'Redefinir senha',
    'reset.instrucao' => 'Informe seu e-mail para receber o link de redefinição.',
    'reset.email_enviado' => 'Se o e-mail existir, você receberá um link de redefinição.',
    'reset.nova_senha' => 'Nova senha',
    'reset.confirmar_senha' => 'Confirmar nova senha',
    'reset.senha_alterada' => 'Senha alterada com sucesso.',
    'reset.token_invalido' => 'Link inválido ou expirado.',
    'reset.solicitar' => 'Enviar link',

    // ── 2FA ──
    '2fa.titulo' => 'Autenticação de dois fatores',
    '2fa.configurar' => 'Configurar 2FA',
    '2fa.ativar' => 'Ativar',
    '2fa.desativar' => 'Desativar',
    '2fa.verificar' => 'Verificar',
    '2fa.codigo' => 'Código de verificação',
    '2fa.instrucao_qr' => 'Escaneie o QR code com seu app autenticador (Google Authenticator, Authy, etc.)',
    '2fa.instrucao_manual' => 'Ou insira a chave manualmente:',
    '2fa.ativado' => '2FA ativado com sucesso.',
    '2fa.desativado' => '2FA desativado.',
    '2fa.codigo_invalido' => 'Código inválido.',
    '2fa.confirme_senha' => 'Confirme sua senha para desativar.',
    '2fa.ja_ativo' => 'A autenticação de dois fatores já está ativa.',
    '2fa.seguranca' => 'Segurança',

    // ── Sidebar cliente ──
    'sidebar.painel' => 'Painel',
    'sidebar.vps' => 'VPS',
    'sidebar.monitoramento' => 'Monitoramento',
    'sidebar.tickets' => 'Tickets',
    'sidebar.chat' => 'Chat',
    'sidebar.emails' => 'E-mails',
    'sidebar.aplicacoes' => 'Aplicações',
    'sidebar.catalogo' => 'Catálogo',
    'sidebar.assinaturas' => 'Assinaturas',
    'sidebar.ajuda' => 'Ajuda',
    'sidebar.seguranca' => 'Segurança',
    'sidebar.planos' => 'Planos',

    // ── Painel cliente ──
    'painel.titulo' => 'Painel',
    'painel.bem_vindo' => 'Bem-vindo, %s',
    'painel.total_vps' => 'Total de VPS',
    'painel.vps_rodando' => 'VPS em execução',
    'painel.tickets_abertos' => 'Tickets abertos',
    'painel.plano_ativo' => 'Plano ativo',
    'painel.nenhum_plano' => 'Nenhum plano ativo',
    'painel.notificacoes' => 'Notificações',
    'painel.sem_notificacoes' => 'Nenhuma notificação.',

    // ── VPS ──
    'vps.titulo' => 'Minhas VPS',
    'vps.subtitulo' => 'Servidores virtuais vinculados à sua conta',
    'vps.nenhuma' => 'Você ainda não tem VPS.',
    'vps.terminal' => 'Terminal',
    'vps.status_running' => 'Em execução',
    'vps.status_stopped' => 'Parada',
    'vps.status_provisioning' => 'Provisionando',
    'vps.status_suspended' => 'Suspensa',
    'vps.status_error' => 'Erro',

    // ── Monitoramento ──
    'monitoramento.titulo' => 'Monitoramento',
    'monitoramento.subtitulo' => 'Métricas de CPU, RAM e disco das suas VPS',
    'monitoramento.cpu' => 'CPU',
    'monitoramento.ram' => 'RAM',
    'monitoramento.disco' => 'Disco',
    'monitoramento.ultima_coleta' => 'Última coleta',
    'monitoramento.sem_dados' => 'Sem dados de monitoramento.',

    // ── Tickets ──
    'tickets.titulo' => 'Tickets de Suporte',
    'tickets.novo' => 'Novo Ticket',
    'tickets.assunto' => 'Assunto',
    'tickets.mensagem' => 'Mensagem',
    'tickets.prioridade' => 'Prioridade',
    'tickets.departamento' => 'Departamento',
    'tickets.status' => 'Status',
    'tickets.aberto' => 'Aberto',
    'tickets.em_andamento' => 'Em andamento',
    'tickets.aguardando_cliente' => 'Aguardando cliente',
    'tickets.fechado' => 'Fechado',
    'tickets.resolvido' => 'Resolvido',
    'tickets.responder' => 'Responder',
    'tickets.nenhum' => 'Você ainda não tem tickets.',
    'tickets.criado' => 'Ticket criado com sucesso.',
    'tickets.prioridade_baixa' => 'Baixa',
    'tickets.prioridade_media' => 'Média',
    'tickets.prioridade_alta' => 'Alta',

    // ── Chat ──
    'chat.titulo' => 'Chat ao vivo',
    'chat.subtitulo' => 'Converse em tempo real com nossa equipe',
    'chat.enviar' => 'Enviar',
    'chat.digite_mensagem' => 'Digite sua mensagem...',
    'chat.conectando' => 'Conectando...',
    'chat.conectado' => 'Conectado',
    'chat.desconectado' => 'Desconectado',
    'chat.reconectando' => 'Reconectando...',
    'chat.encerrar' => 'Encerrar chat',
    'chat.encerrado' => 'Chat encerrado.',
    'chat.emoji' => 'Emojis',
    'chat.anexar' => 'Anexar arquivo',
    'chat.arquivo_enviado' => 'Arquivo enviado.',
    'chat.arquivo_grande' => 'Arquivo muito grande (máx. 5 MB).',
    'chat.widget_titulo' => 'Precisa de ajuda?',
    'chat.widget_abrir' => 'Abrir chat',

    // ── E-mails ──
    'emails.titulo' => 'Meus E-mails',
    'emails.subtitulo' => 'Gerencie suas contas de e-mail',
    'emails.criar' => 'Criar e-mail',
    'emails.usuario' => 'Usuário',
    'emails.dominio' => 'Domínio',
    'emails.webmail' => 'Webmail',
    'emails.alterar_senha' => 'Alterar senha',
    'emails.remover' => 'Remover',
    'emails.nenhum' => 'Você ainda não tem e-mails.',
    'emails.dominios' => 'Domínios de E-mail',
    'emails.adicionar_dominio' => 'Adicionar domínio',
    'emails.verificar_dns' => 'Verificar DNS',
    'emails.instrucoes_dns' => 'Instruções DNS',
    'emails.tutoriais_titulo' => 'Configurar em outros apps',
    'emails.tutoriais_desc' => 'Use seu e-mail profissional no Outlook, Gmail, Apple Mail ou qualquer app de e-mail.',
    'emails.dados_config' => 'Dados de configuração',
    'emails.porta' => 'Porta',
    'emails.usuario_config' => 'Usuário',
    'emails.seu_email_completo' => 'Seu e-mail completo (ex: contato@seudominio.com)',
    'emails.senha_definida' => 'A senha que você definiu ao criar o e-mail',
    'emails.pc_celular' => 'PC e Celular',
    'emails.outlook_1' => 'Abra o Outlook e vá em Arquivo > Adicionar Conta',
    'emails.outlook_2' => 'Selecione "Configuração manual" e escolha IMAP',
    'emails.outlook_3' => 'Preencha os dados de servidor conforme a tabela acima',
    'emails.outlook_4' => 'IMAP: porta <code>993</code> com SSL/TLS — SMTP: porta <code>587</code> com STARTTLS',
    'emails.outlook_5' => 'Clique em Conectar e aguarde a verificação',
    'emails.outlook_mobile' => 'No celular: baixe o app Outlook, toque em Adicionar Conta e use os mesmos dados.',
    'emails.gmail_1' => 'No Gmail, clique na engrenagem > Ver todas as configurações',
    'emails.gmail_2' => 'Vá na aba "Contas e importação" > "Adicionar uma conta de e-mail"',
    'emails.gmail_3' => 'Informe seu e-mail profissional e marque "Importar via POP3" ou "IMAP"',
    'emails.gmail_4' => 'Servidor IMAP: porta <code>993</code> SSL — Servidor SMTP: porta <code>587</code> TLS',
    'emails.gmail_5' => 'Confirme e o Gmail vai sincronizar seus e-mails',
    'emails.gmail_mobile' => 'No celular: abra o app Gmail > Adicionar conta > Outra > use os mesmos dados IMAP/SMTP.',
    'emails.apple_1' => 'Vá em Ajustes > Mail > Contas > Adicionar Conta > Outra',
    'emails.apple_2' => 'Toque em "Adicionar conta de e-mail"',
    'emails.apple_3' => 'Preencha nome, e-mail e senha',
    'emails.apple_4' => 'Em "Servidor de entrada": porta <code>993</code> SSL — Em "Servidor de saída": porta <code>587</code> TLS',
    'emails.apple_5' => 'Salve e aguarde a verificação',
    'emails.thunder_1' => 'Abra o Thunderbird e vá em Configurações de Conta > Ações > Adicionar conta de e-mail',
    'emails.thunder_2' => 'Informe seu nome, e-mail e senha',
    'emails.thunder_3' => 'O Thunderbird pode detectar automaticamente. Se não, clique em "Configuração manual" e use os dados da tabela acima',
    'emails.thunder_4' => 'Clique em Concluído',
    'emails.cota' => 'Cota de armazenamento',
    'emails.cota_usada' => 'Usado',
    'emails.cota_total' => 'Total',
    'emails.cota_disponivel' => 'Disponível',
    'emails.cota_hint' => 'Espaço reservado para esta caixa de e-mail. Selecione GB para valores maiores.',
    'emails.ativar_webmail' => 'Ativar webmail personalizado',
    'emails.verificar_webmail' => 'Verificar webmail',
    'emails.webmail_ativado' => 'Webmail personalizado ativado com sucesso!',
    'emails.webmail_personalizado_hint' => 'Permite acessar o webmail via webmail.seudominio.com',

    // ── Aplicações ──
    'apps.titulo' => 'Minhas Aplicações',
    'apps.subtitulo' => 'Apps instaladas nas suas VPS',
    'apps.catalogo' => 'Catálogo de Aplicações',
    'apps.catalogo_subtitulo' => 'Instale aplicações prontas com 1 clique na sua VPS',
    'apps.instalar' => 'Instalar',
    'apps.instalando' => 'Instalando...',
    'apps.instalacao_iniciada' => 'Instalação iniciada!',
    'apps.nenhuma' => 'Você ainda não tem aplicações.',
    'apps.vps_necessaria' => 'Você precisa de uma VPS ativa para instalar aplicações.',
    'apps.voltar_painel' => 'Voltar ao painel',
    'apps.minhas_apps' => '← Minhas aplicações',
    'apps.roundcube_aviso' => 'O Roundcube será instalado na sua VPS e consumirá recursos (CPU, RAM, disco). Ao instalar, o webmail padrão do sistema será substituído pelo Roundcube para seus domínios.',
    'apps.catalogo_btn' => '📦 Catálogo — Instalar nova',
    'apps.selecione_vps' => 'VPS',
    'apps.dominio' => 'Domínio',
    'apps.repositorio' => 'Repositório Git',
    'apps.variaveis_env' => 'Variáveis de ambiente (JSON)',
    'apps.status_installing' => 'Instalando',
    'apps.status_running' => 'Rodando',
    'apps.status_stopped' => 'Parada',
    'apps.status_error' => 'Erro',
    'apps.status_inactive' => 'Inativa',
    'apps.status_deploying' => 'Deploy',
    'apps.tipo' => 'Tipo',
    'apps.porta' => 'Porta',
    'apps.aplicacao' => 'Aplicação',

    // ── Assinaturas ──
    'assinaturas.titulo' => 'Minhas Assinaturas',
    'assinaturas.subtitulo' => 'Histórico de cobranças e pagamentos',
    'assinaturas.nenhuma' => 'Nenhuma assinatura encontrada.',
    'assinaturas.solicitar_reembolso' => 'Solicitar reembolso',
    'assinaturas.plano' => 'Plano',
    'assinaturas.valor' => 'Valor',
    'assinaturas.vencimento' => 'Vencimento',

    // ── Planos ──
    'planos.titulo' => 'Planos Disponíveis',
    'planos.subtitulo' => 'Escolha o plano ideal para você',
    'planos.assinar' => 'Assinar',
    'planos.atual' => 'Plano atual',
    'planos.mensal' => '/mês',

    // ── Minha Conta ──
    'conta.titulo' => 'Minha Conta',
    'conta.subtitulo' => 'Gerencie seus dados pessoais e senha de acesso',
    'conta.dados_pessoais' => 'Dados pessoais',
    'conta.alterar_senha' => 'Alterar senha',
    'conta.senha_atual' => 'Senha atual',
    'conta.nova_senha' => 'Nova senha',
    'conta.confirmar_senha' => 'Confirmar nova senha',
    'conta.endereco' => 'Endereço',
    'conta.rua' => 'Rua',
    'conta.numero' => 'Número',
    'conta.complemento' => 'Complemento',
    'conta.cidade' => 'Cidade',
    'conta.estado' => 'Estado',
    'conta.cep' => 'CEP',
    'conta.pais' => 'País',
    'conta.salvo' => 'Dados salvos com sucesso.',

    // ── Status ──
    'status.titulo' => 'Status dos Serviços',
    'status.operacional' => 'Operacional',
    'status.degradado' => 'Degradado',
    'status.fora' => 'Fora do ar',
    'status.incidentes' => 'Incidentes',

    // ── Ajuda ──
    'ajuda.titulo' => 'Central de Ajuda',
    'ajuda.subtitulo' => 'Dúvidas frequentes',
    'ajuda.nao_encontrou' => 'Não encontrou o que procurava?',
    'ajuda.chat_vivo' => 'Chat ao vivo',
    'ajuda.abrir_ticket' => 'Abrir ticket',
    'ajuda.fale_conosco' => 'Fale conosco',

    // ── Avaliação ──
    'avaliacao.titulo' => 'Avaliação',
    'avaliacao.como_foi' => 'Como foi seu atendimento?',
    'avaliacao.comentario' => 'Comentário (opcional)',
    'avaliacao.enviar' => 'Enviar avaliação',
    'avaliacao.obrigado' => 'Obrigado pela sua avaliação!',

    // ── Onboarding ──
    'onboarding.titulo' => 'Bem-vindo ao sistema!',
    'onboarding.passo1' => 'Conheça seu painel',
    'onboarding.passo2' => 'Configure sua VPS',
    'onboarding.passo3' => 'Instale aplicações',
    'onboarding.passo4' => 'Precisa de ajuda?',
    'onboarding.concluir' => 'Concluir',

    // ── Páginas públicas ──
    'pub.termos' => 'Termos de Uso',
    'pub.privacidade' => 'Política de Privacidade',
    'pub.licenca' => 'Licença',
    'pub.changelog' => 'Changelog',
    'pub.contato' => 'Contato',
    'pub.status' => 'Status',

    // ── Home / Landing ──
    'home.titulo' => 'Infraestrutura Cloud',
    'home.subtitulo' => 'Servidores VPS de alta performance com gerenciamento completo.',
    'home.comecar' => 'Começar agora',
    'home.ver_planos' => 'Ver planos',
    'home.trial_cta' => 'Testar grátis',
    'home.nav_sobre' => 'Sobre',
    'home.nav_planos' => 'Planos',
    'home.nav_condicoes' => 'Condições',
    'home.nav_devs' => 'Para devs',
    'home.nav_entrar' => 'Entrar',
    'home.nav_contratar' => 'Contratar Agora',
    'home.ver_planos_precos' => 'Ver Planos e Preços',
    'home.saiba_mais' => 'Saiba mais',
    'home.footer_produto' => 'Produto',
    'home.footer_suporte' => 'Suporte',
    'home.footer_legal' => 'Legal',
    'home.footer_todos_operacionais' => 'Todos os sistemas operacionais',

    // ── Home — Corpo ──
    'home.badge_trial' => 'Teste grátis por %s dias disponível',
    'home.badge_servidores' => 'Servidores disponíveis agora',
    'home.hero_titulo' => 'Infraestrutura VPS para',
    'home.hero_titulo_em' => 'escalar seu negócio',
    'home.hero_subtitulo' => 'Servidores VPS com recursos dedicados, proteção DDoS nativa, uptime 99,9%% e suporte técnico — ativação em até 6 dias úteis.',
    'home.servidor_destaque' => 'Servidor em destaque',
    'home.processamento' => 'Processamento',
    'home.infra_dedicada' => 'Dedicada',
    'home.total_mensal' => 'Total mensal (servidor + backup)',
    'home.ddos_protection' => 'DDoS Protection',
    'home.ddos_ativada' => 'Ativada por padrão',
    'home.uptime_sla' => 'SLA garantido',
    'home.empresas_confiam' => 'Empresas que confiam na %s',
    'home.stats_experiencia' => 'Experiência no mercado de infraestrutura',
    'home.stats_clientes' => 'Clientes ativos em todo o Brasil',
    'home.stats_sla' => 'SLA de uptime garantido em contrato',
    'home.stats_ativacao' => 'Ativação rápida dos servidores',
    'home.porque' => 'Por que a %s?',
    'home.melhor_infra' => 'A melhor infraestrutura do Brasil',
    'home.sobre_desc' => 'A %s é especializada em servidores dedicados, hospedagem web e infraestrutura digital. Tecnologia de ponta com suporte humanizado, custos transparentes e escalabilidade real.',
    'home.sobre_desc2' => 'Nossa infraestrutura é base para sistemas empresariais, bancos de dados, armazenamento de arquivos e soluções de continuidade de negócios em todo o Brasil.',
    'home.sobre_desc3' => 'Reajuste previsível baseado no IGPM · Ativação em até 6 dias úteis · Tráfego ilimitado incluído',
    'home.feat_desempenho' => 'Desempenho Superior',
    'home.feat_desempenho_desc' => 'Processadores Intel Xeon de última geração para máximo throughput e mínima latência.',
    'home.feat_ddos' => 'Proteção DDoS Nativa',
    'home.feat_ddos_desc' => 'Infraestrutura blindada contra ataques volumétricos. Incluída em todos os planos.',
    'home.feat_conectividade' => 'Hiperconectividade',
    'home.feat_conectividade_desc' => 'Portas de 1 a 10 Gbps com tráfego ilimitado. Dentro do hub de conectividade dos DCs.',
    'home.feat_upgrades' => 'Upgrades sem Burocracia',
    'home.feat_upgrades_desc' => 'Escale recursos com rapidez. Ajuste CPU, RAM e armazenamento sob demanda.',
    'home.feat_hardware' => 'Hardware Exclusivo',
    'home.feat_hardware_desc' => 'Controle total do servidor dedicado. Sem compartilhamento, sem vizinhos barulhentos.',
    'home.feat_custos' => 'Custos Transparentes',
    'home.feat_custos_desc' => 'Preços claros, sem taxas ocultas. Reajuste anual pelo IGPM, sempre previsível.',

    // ── Home — Diferenciais ──
    'home.diff_titulo' => 'Diferenciais dos Servidores Dedicados %s',
    'home.diff_conectividade' => 'Conectividade',
    'home.diff_conectividade_desc' => 'Conexão direta com grandes redes como Akamai, CloudFlare, Microsoft, Google, AWS e UPX. Capilaridade através dos maiores peerings nacionais do IX.br. Trânsito por múltiplas operadoras atuantes no Brasil e no mundo.',
    'home.diff_kvm' => 'Console/KVM',
    'home.diff_kvm_desc' => 'Painel intuitivo que fornece acesso externo ao servidor (display, teclado e mouse), possibilita a montagem de ISOs em drive virtual, permite ligar, desligar e reiniciar o servidor, entre outras opções.',
    'home.diff_resiliencia' => 'Resiliência',
    'home.diff_resiliencia_desc' => 'Servidores com grande quantidade de recursos para altas demandas de utilização sustentada ou durante picos inesperados, sem alterações na velocidade de resposta.',
    'home.diff_io' => 'Desempenho I/O',
    'home.diff_io_desc' => 'Baixíssima latência em operações de leitura e gravação, mesmo durante picos em cargas como bancos de dados complexos ou servidores de e-mail com grande fluxo de mensagens.',
    'home.diff_rede' => 'Segurança a nível de rede',
    'home.diff_rede_desc' => 'VLAN privada para tráfego interno, VPN para integração segura com seu escritório, firewall dedicado para regras de segurança adequadas e link ponto a ponto para interligar escritórios (serviços adicionais).',
    'home.diff_backup' => 'Backup diário',
    'home.diff_backup_desc' => 'Seus dados armazenados em ambiente externo e à prova de falhas. Segurança total em casos de remoção indevida, corrompimento de banco de dados, ransomware, entre outros (serviço adicional).',

    // ── Home — Planos ──
    'home.plans_titulo' => 'Escolha o ideal para seu projeto',
    'home.plans_sub' => 'Servidores VPS com recursos dedicados e escaláveis. Todos os planos incluem proteção DDoS e SSL gratuito.',
    'home.plans_comparar' => 'Comparar todos os planos',
    'home.plans_moeda' => 'R$',
    'home.plans_por_mes' => 'por mês',
    'home.plans_ddos' => 'Proteção DDoS',
    'home.plans_ssl' => 'SSL gratuito',
    'home.plans_suporte' => 'Suporte especializado',
    'home.plans_addons' => 'Serviços adicionais',
    'home.plans_total' => 'Valor total',
    'home.plans_empty' => 'Planos em breve.',
    'home.plans_empty_contato' => 'Entre em contato',
    'home.plans_empty_saber' => 'para saber mais.',
    'home.plans_help_titulo' => 'Precisando de ajuda para decidir ou mais recursos?',
    'home.plans_help_sub' => 'Fale conosco para um plano personalizado',
    'home.plans_help_btn' => 'Falar com Especialista',

    // ── Home — Condições ──
    'home.cond_eyebrow' => 'Transparência total',
    'home.cond_titulo' => 'Condições Gerais dos Serviços',
    'home.cond_sub' => 'Tudo o que você precisa saber antes de contratar. Sem letras miúdas, sem surpresas na fatura.',
    'home.cond_01' => 'Todos os valores incluem os devidos <strong>impostos conforme a legislação vigente</strong>.',
    'home.cond_02' => 'Serviços <strong>pré-pagos</strong>. Cobrança inicia após a ativação. Primeira fatura proporcional com vencimento em <strong>5 dias</strong>.',
    'home.cond_03' => 'Faturas mensais enviadas com <strong>15 dias de antecedência</strong>, pagamento exclusivamente por boleto bancário.',
    'home.cond_04' => 'Reajuste anual baseado no <strong>IGPM</strong> ao final de cada período de 12 meses de vigência.',
    'home.cond_05' => '<strong>Renovação automática</strong> por períodos iguais se não houver contestação com <strong>60 dias</strong> de antecedência.',
    'home.cond_06' => 'Rescisão antecipada: multa de <strong>50%% do valor mensal × meses restantes</strong> acordados na proposta.',
    'home.cond_07' => '<strong>Prazo de ativação SP1</strong>: 1 servidor = 6 dias úteis. Regiões PR1/CE1: +5 dias úteis adicionais.',
    'home.cond_08' => '<strong>Backup BaaS</strong> ativado em até 4 dias úteis adicionais ao prazo do servidor contratado.',
    'home.cond_09' => 'Cancelamento ou downgrade deve ser <strong>comunicado com 60 dias</strong> de antecedência da suspensão.',
    'home.cond_10' => 'É estritamente proibida a <strong>hospedagem de jogos</strong> para garantia de performance de conectividade.',

    // ── Home — Depoimentos ──
    'home.dep_eyebrow' => 'Depoimentos',
    'home.dep_titulo' => 'O que nossos clientes dizem',
    'home.dep_1' => 'A %s nos deu todo o suporte quando enfrentamos um incidente crítico. Na época tínhamos todo o data center on-premise interno, e agora toda nossa infraestrutura está com eles. Nossa parceria já tem mais de 2 anos e a ideia é continuar por muito tempo. Estamos muito felizes com o atendimento prestado.',
    'home.dep_2' => 'A %s é a principal fornecedora de tecnologia da Akahosting. Fundamentamos uma parceria e em menos de um ano conseguimos ver o extremo sucesso em nossa operação. Graças a eles nossa empresa conseguiu alavancar muito os negócios. Somos gratos pelo suporte em todas as ocasiões.',
    'home.dep_3' => 'Trabalhávamos com provedores de servidor fora do Brasil, conhecemos a %s e trouxemos toda nossa infraestrutura para cá. Estamos com eles há alguns anos e nossa evolução conjunta é constante. Estamos muito satisfeitos e planejamos estender essa parceria cada vez mais.',
    'home.dep_4' => 'A migração para a %s foi decisiva para nossa operação. O processo foi transparente, o time técnico sempre disponível e o desempenho superou nossas expectativas. Com o servidor dedicado reduzimos latência e aumentamos capacidade sem aumentar os custos.',

    // ── Home — CTA Final ──
    'home.cta_pronto' => 'Pronto para começar?',
    'home.cta_trial_titulo' => 'Comece seu teste grátis',
    'home.cta_trial_titulo_em' => 'agora mesmo',
    'home.cta_trial_sub' => 'Crie sua conta e experimente a plataforma gratuitamente por %s dias, sem cartão de crédito.',
    'home.cta_falar_equipe' => 'Falar com a equipe',
    'home.cta_ative_titulo' => 'Ative seu servidor em',
    'home.cta_ative_titulo_em' => 'até 6 dias úteis',
    'home.cta_ative_sub' => 'Entre em contato agora e receba uma proposta personalizada. Nossa equipe técnica está pronta para atender você.',
    'home.cta_proposta' => 'Solicitar Proposta por E-mail',
    'home.cta_consultor' => 'Falar com Consultor',

    // ── Home — Footer ──
    'home.footer_desc' => 'Infraestrutura cloud de alta performance com proteção DDoS, backups automáticos e suporte especializado.',
    'home.footer_sobre' => 'Sobre',
    'home.footer_planos' => 'Planos',
    'home.footer_condicoes' => 'Condições',
    'home.footer_devs' => 'Para devs',
    'home.footer_contato' => 'Contato',
    'home.footer_status' => 'Status do sistema',
    'home.footer_tickets' => 'Tickets',
    'home.footer_ajuda' => 'Central de ajuda',
    'home.footer_termos' => 'Termos de uso',
    'home.footer_privacidade' => 'Privacidade',
    'home.footer_sistema_op' => 'Sistema operacional',
    'home.hero_preco_mes' => '/mês',
    'home.stats_num_exp' => '+5 anos',
    'home.stats_num_clientes' => '+200',
    'home.stats_num_sla' => '99,9%',
    'home.stats_num_ativacao' => '6 dias',
    'home.clients_logos' => 'Startups,E-commerce,SaaS,Agências,Desenvolvedores',

    // ── Categorias de apps ──
    'cat.cms' => 'CMS',
    'cat.backend' => 'Backend',
    'cat.database' => 'Banco de Dados',
    'cat.webserver' => 'Web Server',
    'cat.dev' => 'Desenvolvimento',
    'cat.email' => 'E-mail',
    'cat.other' => 'Outros',

    // ── Equipe ──
    'equipe.painel' => 'Painel',
    'equipe.clientes' => 'Clientes',
    'equipe.usuarios' => 'Usuários',
    'equipe.servidores' => 'Servidores',
    'equipe.vps' => 'VPS',
    'equipe.aplicacoes' => 'Aplicações',
    'equipe.tickets' => 'Tickets',
    'equipe.chat' => 'Chat — Atendimento',
    'equipe.chat_flows' => 'Fluxos de Chat',
    'equipe.emails' => 'E-mails',
    'equipe.monitoramento' => 'Monitoramento',
    'equipe.status' => 'Status',
    'equipe.planos' => 'Planos',
    'equipe.assinaturas' => 'Assinaturas',
    'equipe.backups' => 'Backups',
    'equipe.jobs' => 'Jobs',
    'equipe.terminal' => 'Terminal',
    'equipe.erros' => 'Erros',
    'equipe.configuracoes' => 'Configurações',
    'equipe.permissoes' => 'Permissões',
    'equipe.satisfacao' => 'Satisfação',
    'equipe.ajuda' => 'Ajuda',
    'equipe.inicializacao' => 'Inicialização',
    'equipe.notificacoes' => 'Notificações',
    'equipe.operacoes' => 'Operações',

    // ── 2FA verificar ──
    '2fa.titulo_verificacao' => 'Verificação em dois fatores',
    '2fa.desc_verificacao' => 'Sua conta está protegida com autenticação em dois fatores. Insira o código gerado pelo seu aplicativo autenticador para continuar.',
    '2fa.validade_30s' => 'Código válido por 30 segundos',
    '2fa.use_app' => 'Use Google Authenticator, Authy ou similar',
    '2fa.nao_compartilhe' => 'Nunca compartilhe seu código com ninguém',
    '2fa.codigo_autenticador' => 'Código do autenticador',
    '2fa.abra_app' => 'Abra seu aplicativo autenticador e insira o código de 6 dígitos exibido para esta conta.',
    '2fa.verificar_entrar' => 'Verificar e entrar',
    '2fa.voltar_login' => '← Voltar ao login',

    // ── Terminal VPS ──
    'terminal.titulo' => 'Terminal VPS #%s',
    'terminal.subtitulo' => 'Sessão isolada dentro do contêiner',
    'terminal.abrir_sessao' => 'Abrir sessão',
    'terminal.auditado' => 'Tudo é auditado. O acesso é restrito ao contêiner da sua VPS.',
    'terminal.conectar' => 'Conectar',
    'terminal.vps_nao_rodando' => 'VPS não está em execução (status=%s). O terminal ficará disponível quando estiver rodando.',
    'terminal.upload' => '↑ Upload',
    'terminal.download' => '↓ Download',
    'terminal.desconectado' => 'Desconectado',
    'terminal.enviar_arquivo' => 'Enviar arquivo para a VPS',
    'terminal.arquivo' => 'Arquivo',
    'terminal.caminho_remoto' => 'Caminho remoto',
    'terminal.baixar_arquivo' => 'Baixar arquivo da VPS',
    'terminal.baixar' => 'Baixar',
    'terminal.conexao_proxy' => 'Conexão via proxy reverso: /ws/terminal (WSS).',

    // ── Monitoramento ver ──
    'monitoramento.titulo_vps' => 'Monitoramento — VPS #%s',
    'monitoramento.servidor' => 'Servidor',
    'monitoramento.ip' => 'IP',
    'monitoramento.coletas' => 'Coletas',
    'monitoramento.cpu_agora' => 'CPU agora',
    'monitoramento.ram_agora' => 'RAM agora',
    'monitoramento.disco_agora' => 'Disco agora',
    'monitoramento.atualizacao_auto' => 'Atualização automática a cada 30s. Última:',
    'monitoramento.agora' => 'agora',
    'monitoramento.historico' => 'Histórico',
    'monitoramento.data_hora' => 'Data/Hora',
    'monitoramento.sem_metricas' => 'Ainda não há métricas.',
    'monitoramento.sem_node' => 'Esta VPS ainda não possui node associado para monitoramento.',

    // ── Status cliente ──
    'status.suas_vps' => 'Suas VPS',
    'status.disponibilidade' => 'Disponibilidade das suas VPS',
    'status.uptime_24h' => 'Uptime (24h)',
    'status.historico' => 'Histórico',
    'status.ultima_checagem' => 'Última checagem',
    'status.sem_dados' => 'Sem dados ainda.',
    'status.desconhecido' => 'Desconhecido',
    'status.indisponivel' => 'Indisponível',
    'status.monitorando' => 'Monitorando',
    'status.identificado' => 'Identificado',
    'status.investigando' => 'Investigando',
    'status.critico' => 'Crítico',
    'status.alto' => 'Alto',
    'status.baixo' => 'Baixo',
    'status.inicio' => 'Início',
    'status.resolvido_em' => 'Resolvido',
    'status.servicos_afetados' => 'Serviços afetados',
    'status.atualizacoes' => 'Atualizações',
    'status.nenhum_incidente' => 'Nenhum incidente recente.',

    // ── Assinaturas ──
    'assinaturas.cobrancas' => 'Cobranças / Faturas',
    'assinaturas.id' => 'ID',
    'assinaturas.tipo' => 'Tipo',
    'assinaturas.link' => 'Link',
    'assinaturas.ver_fatura' => 'Ver fatura',
    'assinaturas.nenhuma_ainda' => 'Nenhuma assinatura ainda',
    'assinaturas.escolha_plano' => 'Escolha um plano para começar.',
    'assinaturas.ver_planos' => 'Ver planos disponíveis',
    'assinaturas.prox_vencimento' => 'Próx. vencimento',
    'assinaturas.motivo' => 'Motivo',
    'assinaturas.motivo_placeholder' => 'Descreva o motivo da solicitação...',
    'assinaturas.enviar_solicitacao' => 'Enviar solicitação',
    'assinaturas.planos_cobrancas' => 'Planos, cobranças e reembolsos',
    'assinaturas.mes' => 'mês',

    // ── Ajuda (FAQ) ──
    'ajuda.perguntas_frequentes' => 'Perguntas frequentes',
    'ajuda.versao' => 'Dúvidas frequentes — v%s',
    'ajuda.secao_vps' => '🖥️ VPS',
    'ajuda.secao_email' => '📧 E-mail',
    'ajuda.secao_chat' => '💬 Chat e Suporte',
    'ajuda.secao_apps' => '📦 Aplicações',
    'ajuda.secao_conta' => '🔐 Conta',

    // ── Header equipe ──
    'header.buscar' => 'Buscar...',
    'header.notificacoes' => 'Notificações',
    'header.seguranca_2fa' => 'Segurança / 2FA',

    // ── Chat widget ──
    'widget.suporte' => 'Suporte',
    'widget.como_ajudar' => 'Como podemos ajudar?',
    'widget.fechar' => 'Fechar',
    'widget.abrir_suporte' => 'Abrir suporte',
    'widget.voltar' => '← Voltar',
    'widget.ola' => 'Olá! Sou o assistente virtual. Como posso ajudar você hoje?',
    'widget.tirar_duvida' => '💬 Tirar uma dúvida',
    'widget.falar_atendente' => '🧑‍💻 Falar com atendente',
    'widget.abrir_ticket' => '🎫 Abrir um ticket',
    'widget.enviar_email' => '📧 Enviar e-mail',
    'widget.conectando' => 'Conectando...',
    'widget.online' => '● Online',
    'widget.chat_encerrado' => '● Chat encerrado',

    // ── Equipe — Painel ──
    'eq_painel.titulo' => 'Dashboard',
    'eq_painel.subtitulo' => 'Bem-vindo de volta, %s.',
    'eq_painel.vps_ativas' => 'VPS Ativas',
    'eq_painel.de_total' => 'de %s total',
    'eq_painel.clientes' => 'Clientes',
    'eq_painel.cadastrados' => 'cadastrados',
    'eq_painel.tickets_abertos' => 'Tickets Abertos',
    'eq_painel.aguardando_resposta' => 'aguardando resposta',
    'eq_painel.jobs_pendentes' => 'Jobs Pendentes',
    'eq_painel.na_fila' => 'na fila',
    'eq_painel.nodes_online' => 'Nodes Online',
    'eq_painel.servidores_ativos' => 'servidores ativos',
    'eq_painel.receita_mensal' => 'Receita Mensal',
    'eq_painel.assinaturas_ativas' => 'assinaturas ativas',
    'eq_painel.acoes_rapidas' => 'Ações rápidas',
    'eq_painel.gerenciar_vps' => 'Gerenciar VPS',
    'eq_painel.ver_tickets' => 'Ver tickets',
    'eq_painel.seu_acesso' => 'Seu acesso',
    'eq_painel.seguranca' => 'Segurança',
    'eq_painel.permissoes' => 'Permissões',
    'eq_painel.chat_vivo' => 'Chat ao vivo',
    'eq_painel.inicializacao' => 'Inicialização',

    // ── Equipe — Entrar ──
    'eq_entrar.titulo_painel' => 'Painel administrativo da equipe',
    'eq_entrar.desc_painel' => 'Acesso restrito. Use suas credenciais de membro da equipe para entrar no painel de controle.',
    'eq_entrar.2fa_disponivel' => 'Autenticação em dois fatores (2FA) disponível',
    'eq_entrar.controle_acesso' => 'Controle de acesso por roles e permissões',
    'eq_entrar.auditoria' => 'Auditoria completa de ações',
    'eq_entrar.sessao_expira' => 'Sessão com expiração automática',
    'eq_entrar.area_cliente' => 'Área do cliente →',
    'eq_entrar.acesso_equipe' => 'Acesso da equipe',
    'eq_entrar.desc_acesso' => 'Use seu e-mail e senha para acessar o painel administrativo.',
    'eq_entrar.sessao_expirada' => 'Sua sessão expirou por inatividade. Faça login novamente.',
    'eq_entrar.entrar_painel' => 'Entrar no painel',
    'eq_entrar.voltar_inicio' => '← Voltar ao início',

    // ── Equipe — Tickets ──
    'eq_tickets.titulo' => 'Tickets',
    'eq_tickets.subtitulo' => 'Atendimento e histórico',
    'eq_tickets.buscar' => 'Buscar assunto ou cliente...',
    'eq_tickets.todos_status' => 'Todos os status',
    'eq_tickets.todas_prioridades' => 'Todas as prioridades',
    'eq_tickets.todos_departamentos' => 'Todos os departamentos',
    'eq_tickets.filtrar' => 'Filtrar',
    'eq_tickets.limpar' => 'Limpar',
    'eq_tickets.cliente' => 'Cliente',
    'eq_tickets.assunto' => 'Assunto',
    'eq_tickets.dept' => 'Dept.',
    'eq_tickets.prioridade' => 'Prioridade',
    'eq_tickets.atribuido' => 'Atribuído',
    'eq_tickets.atualizado' => 'Atualizado',
    'eq_tickets.abrir' => 'Abrir',
    'eq_tickets.nenhum' => 'Nenhum ticket encontrado.',
    'eq_tickets.aberto' => 'Aberto',
    'eq_tickets.em_andamento' => 'Em andamento',
    'eq_tickets.aguard_cliente' => 'Aguard. cliente',
    'eq_tickets.fechado' => 'Fechado',
    'eq_tickets.alta' => 'Alta',
    'eq_tickets.media' => 'Média',
    'eq_tickets.baixa' => 'Baixa',

    // ── Equipe — Servidores ──
    'eq_servidores.titulo' => 'Servidores',
    'eq_servidores.subtitulo' => 'Nodes do cluster e capacidade disponível',
    'eq_servidores.cadastre' => 'Cadastre seus nodes e a capacidade total.',
    'eq_servidores.novo' => 'Novo servidor',
    'eq_servidores.hostname' => 'Hostname',
    'eq_servidores.cpu' => 'CPU',
    'eq_servidores.memoria' => 'Memória',
    'eq_servidores.armazenamento' => 'Armazenamento',
    'eq_servidores.setup' => 'Setup',
    'eq_servidores.ativo' => 'Ativo',
    'eq_servidores.manutencao' => 'Manutenção',
    'eq_servidores.inativo' => 'Inativo',
    'eq_servidores.online' => 'Online',
    'eq_servidores.offline' => 'Offline',
    'eq_servidores.pronto' => 'Pronto',
    'eq_servidores.inicializando' => 'Inicializando…',
    'eq_servidores.erro' => 'Erro',
    'eq_servidores.pendente' => 'Pendente',
    'eq_servidores.editar' => 'Editar',
    'eq_servidores.continuar_setup' => 'Continuar setup',
    'eq_servidores.reiniciar' => 'Reiniciar',
    'eq_servidores.inicializar' => 'Inicializar',
    'eq_servidores.re_inicializar' => 'Re-inicializar',
    'eq_servidores.nenhum' => 'Nenhum servidor cadastrado ainda.',
    'eq_servidores.modal_titulo' => 'Inicializar servidor',
    'eq_servidores.modal_desc' => 'Conecta via SSH e prepara o servidor automaticamente: Docker, rede lrv-net e usuário de terminal.',
    'eq_servidores.aguardando_inicio' => 'Aguardando início…',
    'eq_servidores.inicializar_agora' => 'Inicializar agora',
    'eq_servidores.modo_continuar' => 'Modo: continuar de onde parou.',
    'eq_servidores.clique_retomar' => 'Clique no botão para retomar.',
    'eq_servidores.clique_iniciar' => 'Clique em "Inicializar agora" para começar.',
    'eq_servidores.servidor_pronto' => 'Servidor pronto. Status atualizado para Ativo/Online.',
    'eq_servidores.setup_erros' => 'Setup concluído com erros. Corrija e use "Continuar de onde parou".',
    'eq_servidores.erro_comunicacao' => 'Erro de comunicação',
    'eq_servidores.etapas' => 'etapas',
    'eq_servidores.retomando' => 'Retomando',
    'eq_servidores.iniciando' => 'Iniciando',

    // ── Equipe — Minha Conta ──
    'eq_conta.titulo' => 'Minha Conta',
    'eq_conta.subtitulo' => 'Gerencie suas informações pessoais e senha',
    'eq_conta.info_pessoais' => 'Informações pessoais',
    'eq_conta.foto_perfil' => 'Foto de perfil',
    'eq_conta.escolher_foto' => 'Escolher foto',
    'eq_conta.nenhum_arquivo' => 'Nenhum arquivo selecionado',
    'eq_conta.nome' => 'Nome',
    'eq_conta.alterar_senha' => 'Alterar senha',
    'eq_conta.hint_senha' => '(deixe em branco para não alterar)',
    'eq_conta.senha_atual' => 'Senha atual',
    'eq_conta.nova_senha' => 'Nova senha',
    'eq_conta.salvar' => 'Salvar alterações',
    'eq_conta.hint_avatar' => 'PNG, JPG, WEBP · máx. 2 MB',

    // ── Equipe — Satisfação ──
    'eq_satisfacao.titulo' => 'Satisfação do Suporte',
    'eq_satisfacao.subtitulo' => 'Avaliações de tickets e chats encerrados',
    'eq_satisfacao.media_geral' => 'Média geral',
    'eq_satisfacao.total_avaliacoes' => 'Total de avaliações',
    'eq_satisfacao.distribuicao' => 'Distribuição de notas',
    'eq_satisfacao.por_agente' => 'Por agente',
    'eq_satisfacao.agente' => 'Agente',
    'eq_satisfacao.avaliacoes' => 'Avaliações',
    'eq_satisfacao.media' => 'Média',
    'eq_satisfacao.positivas' => 'Positivas (≥4)',
    'eq_satisfacao.ultimas' => 'Últimas avaliações',
    'eq_satisfacao.nenhuma' => 'Nenhuma avaliação registrada ainda.',
    'eq_satisfacao.data' => 'Data',
    'eq_satisfacao.tipo' => 'Tipo',
    'eq_satisfacao.cliente' => 'Cliente',
    'eq_satisfacao.nota' => 'Nota',
    'eq_satisfacao.comentario' => 'Comentário',
    'eq_satisfacao.muito_ruim' => 'Muito ruim',
    'eq_satisfacao.ruim' => 'Ruim',
    'eq_satisfacao.regular' => 'Regular',
    'eq_satisfacao.bom' => 'Bom',
    'eq_satisfacao.excelente' => 'Excelente',

    // ── Equipe — Jobs ──
    'eq_jobs.titulo' => 'Jobs',
    'eq_jobs.subtitulo' => 'Fila e logs (últimos 200)',
    'eq_jobs.id' => 'ID',
    'eq_jobs.tipo' => 'Tipo',
    'eq_jobs.criado' => 'Criado',
    'eq_jobs.atualizado' => 'Atualizado',
    'eq_jobs.concluido' => 'Concluído',
    'eq_jobs.falhou' => 'Falhou',
    'eq_jobs.rodando' => 'Rodando',
    'eq_jobs.pendente' => 'Pendente',
    'eq_jobs.nenhum' => 'Nenhum job encontrado.',
    'eq_jobs.dica' => 'Dica: rode <strong>php worker.php</strong> para processar a fila.',

    // ── Equipe — Erros ──
    'eq_erros.titulo' => 'Erros do Sistema',
    'eq_erros.subtitulo' => 'Registro de erros HTTP, exceções e falhas capturadas',
    'eq_erros.total' => 'total',
    'eq_erros.pendentes' => 'pendentes',
    'eq_erros.codigo_http' => 'Código HTTP',
    'eq_erros.todos' => 'Todos',
    'eq_erros.tipo' => 'Tipo',
    'eq_erros.filtrar' => 'Filtrar',
    'eq_erros.limpar' => 'Limpar',
    'eq_erros.limpar_resolvidos' => 'Limpar resolvidos',
    'eq_erros.nenhum' => 'Nenhum erro encontrado.',
    'eq_erros.codigo' => 'Código',
    'eq_erros.url' => 'URL',
    'eq_erros.mensagem' => 'Mensagem',
    'eq_erros.ip' => 'IP',
    'eq_erros.data' => 'Data',
    'eq_erros.resolvido' => 'Resolvido',
    'eq_erros.pendente' => 'Pendente',
    'eq_erros.encontrados' => '%s erro(s) encontrado(s)',
    'eq_erros.confirmar_limpar' => 'Excluir todos os erros marcados como resolvidos?',

    // ── Equipe — VPS ──
    'eq_vps.titulo' => 'VPS',
    'eq_vps.subtitulo' => 'Provisionamento, status e ações',
    'eq_vps.cliente' => 'Cliente',
    'eq_vps.cpu_ram_disco' => 'CPU / RAM / Disco',
    'eq_vps.status' => 'Status',
    'eq_vps.acoes' => 'Ações',
    'eq_vps.node' => 'Node',
    'eq_vps.provisionar' => 'Provisionar',
    'eq_vps.reativar' => 'Reativar',
    'eq_vps.reiniciar' => 'Reiniciar',
    'eq_vps.suspender' => 'Suspender',
    'eq_vps.remover' => 'Remover',
    'eq_vps.confirmar_remover' => 'Remover VPS #%s?',
    'eq_vps.nenhuma' => 'Nenhuma VPS encontrada.',
    'eq_vps.em_execucao' => 'Em execução',
    'eq_vps.suspensa' => 'Suspensa',
    'eq_vps.aguard_pagamento' => 'Aguard. pagamento',
    'eq_vps.aguard_node' => 'Aguard. node',
    'eq_vps.prov_pendente' => 'Prov. pendente',
    'eq_vps.provisionando' => 'Provisionando',
    'eq_vps.erro' => 'Erro',
    'eq_vps.removida' => 'Removida',

    // ── Equipe — Aplicações ──
    'eq_apps.titulo' => 'Aplicações',
    'eq_apps.subtitulo' => 'Apps vinculados às VPS e portas reservadas',
    'eq_apps.desc' => 'Crie aplicações e reserve portas únicas para expor serviços.',
    'eq_apps.nova' => 'Nova aplicação',
    'eq_apps.cliente' => 'Cliente',
    'eq_apps.tipo' => 'Tipo',
    'eq_apps.dominio' => 'Domínio',
    'eq_apps.porta' => 'Porta',
    'eq_apps.status' => 'Status',
    'eq_apps.acoes' => 'Ações',
    'eq_apps.nenhuma' => 'Nenhuma aplicação cadastrada.',
    'eq_apps.confirmar_deploy' => 'Iniciar deploy agora?',
    'eq_apps.ativa' => 'Ativa',
    'eq_apps.inativa' => 'Inativa',
    'eq_apps.deploy' => 'Deploy',
    'eq_apps.erro' => 'Erro',
    'eq_apps.catalogo' => 'Catálogo de templates',
    'eq_apps.catalogo_desc' => 'Templates disponíveis para instalação one-click pelos clientes.',
    'eq_apps.requer_dominio' => 'Domínio',
    'eq_apps.requer_repo' => 'Repositório',

    // ── Equipe — Planos ──
    'eq_planos.backup_slots' => 'Backups inclusos',
    'eq_planos.sem_backup' => 'Sem backup',

    // ── Equipe — E-mails ──
    'eq_emails.titulo' => 'E-mails',
    'eq_emails.subtitulo' => 'Contas de e-mail e domínios cadastrados pelos clientes',
    'eq_emails.abrir_webmail' => '🌐 Abrir Webmail',
    'eq_emails.buscar' => 'Buscar e-mail ou cliente...',
    'eq_emails.contas' => 'Contas de e-mail',
    'eq_emails.nenhuma_conta' => 'Nenhuma conta encontrada.',
    'eq_emails.quota' => 'Quota',
    'eq_emails.criado_em' => 'Criado em',
    'eq_emails.remover' => 'Remover',
    'eq_emails.confirmar_remover_email' => 'Remover esta conta de e-mail?',
    'eq_emails.dominios_custom' => 'Domínios custom',
    'eq_emails.nenhum_dominio' => 'Nenhum domínio cadastrado.',
    'eq_emails.dominio' => 'Domínio',
    'eq_emails.cadastrado_em' => 'Cadastrado em',
    'eq_emails.confirmar_remover_dominio' => 'Remover este domínio?',
    'eq_emails.operacao_sucesso' => 'Operação realizada com sucesso.',
    'eq_emails.aguard_dns' => 'Aguard. DNS',

    // ── Equipe — Status ──
    'eq_status.titulo' => 'Status',
    'eq_status.subtitulo' => 'Dashboard e incidentes',
    'eq_status.servicos_coletados' => 'Serviços coletados',
    'eq_status.key' => 'Key',
    'eq_status.nome' => 'Nome',
    'eq_status.scope' => 'Scope',
    'eq_status.cliente' => 'Cliente',
    'eq_status.node' => 'Node',
    'eq_status.ultima_checagem' => 'Última checagem',
    'eq_status.sem_dados' => 'Sem dados ainda. Inicie a coleta em Inicialização.',
    'eq_status.criar_incidente' => 'Criar incidente',
    'eq_status.titulo_incidente' => 'Título',
    'eq_status.impacto' => 'Impacto',
    'eq_status.servicos_ids' => 'Serviços (IDs)',
    'eq_status.mensagem' => 'Mensagem',
    'eq_status.descreva' => 'Descreva o incidente...',
    'eq_status.criar' => 'Criar incidente',
    'eq_status.incidentes' => 'Incidentes',
    'eq_status.nenhum_incidente' => 'Nenhum incidente.',
    'eq_status.inicio' => 'Início',
    'eq_status.resolvido' => 'Resolvido',
    'eq_status.servicos_afetados' => 'Serviços afetados',
    'eq_status.salvar_servicos' => 'Salvar serviços',
    'eq_status.adicionar_update' => 'Adicionar update',
    'eq_status.atualizacao_incidente' => 'Atualização do incidente...',
    'eq_status.ultimas_atualizacoes' => 'Últimas atualizações',
    'eq_status.publico' => 'Público',
    'eq_status.interno' => 'Interno',
    'eq_status.operacional' => 'Operacional',
    'eq_status.degradado' => 'Degradado',
    'eq_status.indisponivel' => 'Indisponível',
    'eq_status.desconhecido' => 'Desconhecido',
    'eq_status.investigando' => 'Investigando',
    'eq_status.identificado' => 'Identificado',
    'eq_status.monitorando' => 'Monitorando',
    'eq_status.critico' => 'Crítico',
    'eq_status.alto' => 'Alto',
    'eq_status.baixo' => 'Baixo',

    // ── Equipe — 2FA Configurar ──
    'eq_2fa.titulo' => 'Autenticação em dois fatores',
    'eq_2fa.subtitulo' => 'Proteja sua conta com TOTP (Google Authenticator, Authy, etc.)',
    'eq_2fa.ativado' => '2FA ativado',
    'eq_2fa.conta_protegida' => 'Sua conta está protegida com autenticação em dois fatores.',
    'eq_2fa.desativar' => 'Desativar 2FA',
    'eq_2fa.desc_desativar' => 'Para desativar, confirme com o código do seu autenticador.',
    'eq_2fa.codigo_autenticador' => 'Código do autenticador',
    'eq_2fa.configurar' => 'Configurar autenticador',
    'eq_2fa.desc_configurar' => 'Escaneie o QR code com seu aplicativo autenticador ou insira a chave manualmente.',
    'eq_2fa.chave_secreta' => 'Chave secreta (manual)',
    'eq_2fa.desc_app' => 'Use Google Authenticator, Authy, Bitwarden ou qualquer app TOTP compatível.',
    'eq_2fa.codigo_confirmar' => 'Código do autenticador para confirmar',
    'eq_2fa.ativar' => 'Ativar 2FA',

    // ── Equipe — 2FA Verificar ──
    'eq_2fa_verificar.titulo' => 'Verificação em dois fatores',
    'eq_2fa_verificar.desc' => 'Sua conta está protegida com autenticação em dois fatores. Insira o código gerado pelo seu aplicativo autenticador para continuar.',
    'eq_2fa_verificar.codigo_verificacao' => 'Código de verificação',
    'eq_2fa_verificar.desc_codigo' => 'Abra seu aplicativo autenticador e insira o código de 6 dígitos exibido para esta conta.',
    'eq_2fa_verificar.verificar_entrar' => 'Verificar e entrar',
    'eq_2fa_verificar.voltar_login' => '← Voltar ao login',
    'eq_2fa_verificar.validade_30s' => 'Código válido por 30 segundos',
    'eq_2fa_verificar.use_app' => 'Use Google Authenticator, Authy ou similar',
    'eq_2fa_verificar.nao_compartilhe' => 'Nunca compartilhe seu código com ninguém',

    // ── Equipe — Configurações ──
    'eq_config.titulo' => 'Configurações',
    'eq_config.subtitulo' => 'Pagamentos, webhooks, alertas e identidade visual',
    'eq_config.desc_banco' => 'Tudo aqui fica salvo no banco (tabela <strong>settings</strong>). Não usamos arquivo <strong>.env</strong>.',
    'eq_config.salvas' => 'Configurações salvas.',
    'eq_config.geral' => 'Geral',
    'eq_config.url_base' => 'URL base pública da aplicação',
    'eq_config.email_admin' => 'E-mail do admin para alertas',
    'eq_config.secret_key' => 'Chave secreta da aplicação (app.secret_key)',
    'eq_config.gerar_chave' => 'Gerar',
    'eq_config.hint_secret_key' => 'Usada para criptografar senhas SSH no banco. Obrigatória para salvar servidores com autenticação por senha. Não altere após configurar.',
    'eq_config.identidade_visual' => 'Identidade Visual',
    'eq_config.nome_sistema' => 'Nome do sistema',
    'eq_config.nome_empresa' => 'Nome da empresa',
    'eq_config.url_logo' => 'URL do logotipo',
    'eq_config.url_favicon' => 'URL do favicon',
    'eq_config.copyright_footer' => 'Texto de copyright (footer)',
    'eq_config.paginas_legais' => 'Páginas Legais',
    'eq_config.desc_legais' => 'HTML permitido. Acessível em',
    'eq_config.trial' => 'Teste Grátis (Trial)',
    'eq_config.trial_desc' => 'Quando ativo, novos clientes recebem um servidor de teste ao criar conta.',
    'eq_config.trial_ativo' => 'Trial ativo',
    'eq_config.duracao_dias' => 'Duração (dias)',
    'eq_config.label_cta' => 'Label do botão CTA',
    'eq_config.desc_trial' => 'Descrição do trial (exibida na home)',
    'eq_config.seo' => 'SEO & Indexação',
    'eq_config.seo_desc' => 'Configurações para o Google e outros buscadores indexarem corretamente o site público.',
    'eq_config.salvar' => 'Salvar',

    // ── Chat equipe ──
    'chat_equipe.titulo' => 'Chat — Atendimento',
    'chat_equipe.subtitulo' => 'Gerencie as conversas de suporte',
    'chat_equipe.abertos' => 'Chats abertos',
    'chat_equipe.encerrados' => 'Chats encerrados',
    'chat_equipe.atender' => 'Atender',
    'chat_equipe.nenhum_aberto' => 'Nenhum chat aberto no momento.',
    'chat_equipe.nenhum_encerrado' => 'Nenhum chat encerrado.',
    'chat_equipe.cliente' => 'Cliente',
    'chat_equipe.agente' => 'Agente',
    'chat_equipe.iniciado_em' => 'Iniciado em',
    'chat_equipe.encerrado_em' => 'Encerrado em',
    'chat_equipe.sem_agente' => 'Sem agente',
    'chat_equipe.msgs' => 'Msgs',
    'chat_equipe.aberto_em' => 'Aberto em',
    'chat_equipe.ultima_ativ' => 'Última ativ.',

    // ── Equipe — Ticket ver ──
    'eq_ticket.mensagens' => 'Mensagens',
    'eq_ticket.nenhuma_msg' => 'Nenhuma mensagem ainda.',
    'eq_ticket.responder' => 'Responder',
    'eq_ticket.sua_resposta' => 'Sua resposta...',
    'eq_ticket.anexo' => 'Anexo (opcional, máx. 5 MB)',
    'eq_ticket.enviar_resposta' => 'Enviar resposta',
    'eq_ticket.acoes' => 'Ações',
    'eq_ticket.alterar_status' => 'Alterar status',
    'eq_ticket.atribuir_para' => 'Atribuir para',
    'eq_ticket.ninguem' => 'Ninguém',
    'eq_ticket.atribuir' => 'Atribuir',
    'eq_ticket.ticket_fechado' => 'Ticket fechado.',
    'eq_ticket.nenhuma_acao' => 'Nenhuma ação disponível.',
    'eq_ticket.equipe' => 'Equipe',
    'eq_ticket.atualizado' => 'Atualizado',
    'eq_ticket.atribuido_a' => 'Atribuído a',
    'eq_ticket.anexo_label' => 'Anexo',

    // ── Equipe — Chat ver ──
    'eq_chat_ver.aberto' => 'Aberto',
    'eq_chat_ver.encerrado' => 'Encerrado',
    'eq_chat_ver.encerrar' => 'Encerrar chat',
    'eq_chat_ver.confirmar_encerrar' => 'Encerrar este chat?',
    'eq_chat_ver.chat_encerrado' => 'Este chat foi encerrado.',
    'eq_chat_ver.enviar' => 'Enviar',
    'eq_chat_ver.placeholder' => 'Digite sua mensagem...',
    'eq_chat_ver.carregando' => 'Carregando mensagens...',
    'eq_chat_ver.cancelar_arquivo' => 'Cancelar arquivo',
    'eq_chat_ver.emojis' => 'Emojis',
    'eq_chat_ver.enviar_arquivo' => 'Enviar arquivo',
    'eq_chat_ver.cliente_label' => 'Cliente',
    'eq_chat_ver.nome' => 'Nome',
    'eq_chat_ver.email' => 'E-mail',
    'eq_chat_ver.cadastro' => 'Cadastro',
    'eq_chat_ver.ver_perfil' => 'Ver perfil completo',
    'eq_chat_ver.nao_encontrado' => 'Cliente não encontrado.',
    'eq_chat_ver.assinaturas' => 'Assinaturas',
    'eq_chat_ver.plano' => 'Plano',
    'eq_chat_ver.nenhuma_assinatura' => 'Nenhuma assinatura.',
    'eq_chat_ver.vps' => 'VPS',
    'eq_chat_ver.nenhuma_vps' => 'Nenhuma VPS.',
    'eq_chat_ver.tickets_recentes' => 'Tickets recentes',
    'eq_chat_ver.nenhum_ticket' => 'Nenhum ticket.',

    // ── Equipe — Servidor editar ──
    'eq_srv_edit.titulo_novo' => 'Novo servidor',
    'eq_srv_edit.titulo_editar' => 'Editar servidor',
    'eq_srv_edit.conectividade' => 'Conectividade',
    'eq_srv_edit.acoes' => 'Ações',
    'eq_srv_edit.testar_ssh' => 'Testar conexão SSH',
    'eq_srv_edit.continuar_setup' => 'Continuar setup',
    'eq_srv_edit.re_inicializar' => 'Re-inicializar',
    'eq_srv_edit.inicializar' => 'Inicializar servidor',
    'eq_srv_edit.hostname' => 'Hostname',
    'eq_srv_edit.status' => 'Status',
    'eq_srv_edit.ativo' => 'Ativo',
    'eq_srv_edit.manutencao' => 'Manutenção',
    'eq_srv_edit.inativo' => 'Inativo',
    'eq_srv_edit.ip' => 'Endereço IP',
    'eq_srv_edit.porta_ssh' => 'Porta SSH',
    'eq_srv_edit.auth_ssh' => 'Autenticação SSH',
    'eq_srv_edit.usuario_senha' => 'Usuário e senha',
    'eq_srv_edit.chave_ssh' => 'Chave SSH',
    'eq_srv_edit.usuario_ssh' => 'Usuário SSH',
    'eq_srv_edit.senha_ssh' => 'Senha SSH',
    'eq_srv_edit.manter_branco' => '(deixe em branco para manter)',
    'eq_srv_edit.id_chave' => 'Identificador da chave SSH',
    'eq_srv_edit.hint_chave' => 'Nome do arquivo dentro do diretório configurado em',
    'eq_srv_edit.upload_chave' => 'Chave privada SSH (upload)',
    'eq_srv_edit.hint_upload_chave' => 'Envie o arquivo da chave privada (.pem, id_rsa, etc). O arquivo será salvo no diretório de chaves do sistema.',
    'eq_srv_edit.hint_substituir_chave' => 'Envie um novo arquivo para substituir a chave atual.',
    'eq_srv_edit.chave_configurada' => 'Chave configurada',
    'eq_srv_edit.upload_chave_terminal' => 'Chave privada do terminal (upload)',
    'eq_srv_edit.hint_upload_terminal' => 'Envie a chave privada do terminal seguro. Deixe em branco para desativar.',
    'eq_srv_edit.usar_sudo' => 'Usar sudo',
    'eq_srv_edit.hint_sudo' => 'Marque se o usuário SSH não é root e precisa de sudo para instalar pacotes.',
    'eq_srv_edit.senha_sudo' => 'Senha do sudo',
    'eq_srv_edit.hint_sudo_branco' => '(deixe em branco para usar a mesma senha SSH)',
    'eq_srv_edit.hint_nopasswd' => 'Se o sudo não pede senha (NOPASSWD), deixe em branco também.',
    'eq_srv_edit.terminal_seguro' => 'Terminal seguro (clientes)',
    'eq_srv_edit.terminal_desc' => 'Sessões de terminal do cliente via',
    'eq_srv_edit.usuario_terminal' => 'Usuário SSH do terminal',
    'eq_srv_edit.chave_terminal' => 'Identificador da chave do terminal',
    'eq_srv_edit.hint_terminal' => 'Deixe em branco para desativar terminal seguro neste node.',
    'eq_srv_edit.passo_a_passo' => 'Passo-a-passo no node',
    'eq_srv_edit.cpu_total' => 'CPU total (vCPUs)',
    'eq_srv_edit.ram_total' => 'Memória total (MB)',
    'eq_srv_edit.storage_total' => 'Armazenamento total (MB)',
    'eq_srv_edit.salvar' => 'Salvar servidor',

    // ── Equipe — Terminal ──
    'eq_terminal.titulo' => 'Terminal (Admin)',
    'eq_terminal.subtitulo' => 'Acesso SSH ao node via WebSocket',
    'eq_terminal.subtitulo_http' => 'Acesso SSH ao node via HTTP — sem necessidade de WebSocket',
    'eq_terminal.escolha_node' => 'Escolha um node e conecte. Tudo é auditado.',
    'eq_terminal.node' => 'Node',
    'eq_terminal.selecione' => 'Selecione...',
    'eq_terminal.conectar' => 'Conectar',
    'eq_terminal.desconectado' => 'Desconectado',
    'eq_terminal.conectado_http' => 'Conectado (HTTP)',
    'eq_terminal.executando' => 'Executando...',
    'eq_terminal.sessao_iniciada' => 'Sessão iniciada. Cada comando é executado via SSH.',
    'eq_terminal.dica_http' => 'Dica: use "cd /caminho && comando" para executar em outro diretório.',
    'eq_terminal.selecione_node' => 'Selecione um node primeiro.',
    'eq_terminal.nao_conectado' => 'Não conectado.',
    'eq_terminal.inativo' => 'inativo',
    'eq_terminal.preencha_upload' => 'Selecione um arquivo e informe o caminho.',
    'eq_terminal.enviando' => 'Enviando...',
    'eq_terminal.http_hint' => 'Cada comando é executado individualmente via SSH. Para comandos interativos, configure o WebSocket.',
    'eq_terminal.upload' => 'Upload',
    'eq_terminal.download' => 'Download',
    'eq_terminal.enviar_arquivo' => 'Enviar arquivo para o servidor',
    'eq_terminal.arquivo' => 'Arquivo',
    'eq_terminal.caminho_remoto' => 'Caminho remoto',
    'eq_terminal.enviar' => 'Enviar',
    'eq_terminal.cancelar' => 'Cancelar',
    'eq_terminal.baixar_arquivo' => 'Baixar arquivo do servidor',
    'eq_terminal.baixar' => 'Baixar',
    'eq_terminal.placeholder' => 'Digite um comando e pressione Enter',
    'eq_terminal.proxy_hint' => 'Conexão via proxy reverso:',

    // ── Equipe — Cliente ver ──
    'eq_cliente.clientes' => 'Clientes',
    'eq_cliente.editar_dados' => 'Editar dados',
    'eq_cliente.dados_cadastrais' => 'Dados cadastrais',
    'eq_cliente.telefone' => 'Telefone',
    'eq_cliente.celular' => 'Celular',
    'eq_cliente.cpf_cnpj' => 'CPF / CNPJ',
    'eq_cliente.cadastro' => 'Cadastro',
    'eq_cliente.endereco' => 'Endereço',
    'eq_cliente.assinar_plano' => 'Assinar plano manualmente',
    'eq_cliente.plano' => 'Plano',
    'eq_cliente.assinar' => 'Assinar plano',
    'eq_cliente.vps' => 'VPS',
    'eq_cliente.container' => 'Container',
    'eq_cliente.cpu_ram_disco' => 'CPU / RAM / Disco',
    'eq_cliente.nenhum_vps' => 'Nenhum VPS cadastrado.',
    'eq_cliente.assinaturas' => 'Assinaturas',
    'eq_cliente.valor_mes' => 'Valor/mês',
    'eq_cliente.prox_vencimento' => 'Próx. vencimento',
    'eq_cliente.criada' => 'Criada',
    'eq_cliente.nenhuma_assinatura' => 'Nenhuma assinatura.',
    'eq_cliente.assinatura_criada' => 'Assinatura criada com sucesso.',
    'eq_cliente.ativa' => 'Ativa',
    'eq_cliente.suspensa' => 'Suspensa',
    'eq_cliente.cancelada' => 'Cancelada',
    'eq_cliente.ativo' => 'Ativo',
    'eq_cliente.parado' => 'Parado',
    'eq_cliente.suspenso' => 'Suspenso',
    'eq_cliente.assinaturas_ativas' => 'assinatura(s) ativa(s)',

    // ── Equipe — Inicialização ──
    'eq_init.titulo' => 'Assistente de inicialização',
    'eq_init.subtitulo' => 'Verificações e ações para deixar o servidor pronto',
    'eq_init.erro' => 'Erro',
    'eq_init.acao_executada' => 'Ação executada.',
    'eq_init.status' => 'Status',
    'eq_init.item' => 'Item',
    'eq_init.detalhe' => 'Detalhe',
    'eq_init.ok' => 'OK',
    'eq_init.pendente' => 'Pendente',
    'eq_init.migrations_pendentes' => 'Migrations pendentes:',
    'eq_init.acoes' => 'Ações',
    'eq_init.aplicar_schema' => 'Aplicar schema.sql',
    'eq_init.aplicar_migrations' => 'Aplicar migrations',
    'eq_init.criar_diretorios' => 'Criar diretórios',
    'eq_init.gerar_tokens' => 'Gerar tokens/defaults',
    'eq_init.processar_job' => 'Processar 1 job',
    'eq_init.coletar_status' => 'Coletar status (1x)',
    'eq_init.enfileirar' => 'Enfileirar',
    'eq_init.coleta_continua' => 'Iniciar coleta contínua',
    'eq_init.iniciar' => 'Iniciar',
    'eq_init.testar_nodes' => 'Testar conectividade dos nodes',
    'eq_init.executar' => 'Executar',
    'eq_init.terminal_ws' => 'Terminal WS (Admin)',
    'eq_init.instalar_deps' => 'Instalar dependências (composer)',
    'eq_init.iniciar_daemon' => 'Iniciar daemon',
    'eq_init.parar_daemon' => 'Parar daemon',
    'eq_init.nodes_cadastrados' => 'Nodes cadastrados',
    'eq_init.nodes_desc' => 'Esta lista mostra o status e o último resultado de conectividade (SSH + docker version).',
    'eq_init.host' => 'Host',
    'eq_init.ultima_checagem' => 'Última checagem',
    'eq_init.ultimo_erro' => 'Último erro',
    'eq_init.nenhum_node' => 'Nenhum node cadastrado ainda.',
    'eq_init.worker_http' => 'Worker via HTTP (sem CLI)',
    'eq_init.worker_desc' => 'Endpoint para rodar 1 job (ideal para cron externo). Autenticação por header',
    'eq_init.testar_worker' => 'Testar (executar 1 job via HTTP)',
    'eq_init.logs' => 'Logs',
    'eq_init.obs_deploy' => 'Observação: para Deploy/Backups o servidor precisa ter ssh e scp disponíveis e o PHP com shell_exec habilitado.',

    // ── Equipe — Ajuda ──
    'eq_ajuda.subtitulo' => 'Configuração e operação',

    // ── Infraestrutura (página pública) ──
    'infra.nav_funcionalidades' => 'Funcionalidades',
    'infra.nav_planos' => 'Planos',
    'infra.nav_tecnologia' => 'Tecnologia',
    'infra.nav_status' => 'Status',
    'infra.nav_contato' => 'Contato',
    'infra.nav_entrar' => 'Entrar',
    'infra.nav_criar_conta' => 'Criar conta',
    'infra.hero_eyebrow' => 'Plataforma Cloud SaaS',
    'infra.hero_titulo' => 'Infraestrutura cloud',
    'infra.hero_titulo_grad' => 'simples e poderosa',
    'infra.hero_sub' => 'Provisione VPS, faça deploy de aplicações, gerencie e-mails, backups e suporte em um único painel. Tudo automatizado, seguro e pronto para escalar.',
    'infra.hero_criar_conta' => 'Criar conta grátis',
    'infra.hero_ver_planos' => 'Ver planos →',
    'infra.badge_deploy' => 'Deploy automatizado',
    'infra.badge_backups' => 'Backups automáticos',
    'infra.badge_suporte' => 'Suporte via chat e tickets',
    'infra.badge_monitoramento' => 'Monitoramento 24/7',
    'infra.badge_terminal' => 'Terminal web integrado',
    'infra.stat_uptime' => 'Uptime garantido',
    'infra.stat_provisioning' => 'Provisionamento',
    'infra.stat_monitoring' => 'Monitoramento',
    'infra.stat_encryption' => 'Criptografia',
    'infra.feat_label' => 'Funcionalidades',
    'infra.feat_titulo' => 'Tudo que você precisa em um lugar',
    'infra.feat_sub' => 'Do provisionamento ao suporte, cada recurso foi pensado para simplificar sua operação.',
    'infra.feat_vps' => 'VPS Gerenciadas',
    'infra.feat_vps_desc' => 'Provisione, suspenda, reinicie e monitore suas VPS com poucos cliques.',
    'infra.feat_terminal' => 'Terminal Web',
    'infra.feat_terminal_desc' => 'Acesse o terminal SSH diretamente pelo navegador. Auditoria completa de comandos.',
    'infra.feat_deploy' => 'Deploy de Aplicações',
    'infra.feat_deploy_desc' => 'Faça deploy de aplicações Docker com um clique. Logs em tempo real e rollback fácil.',
    'infra.feat_backups' => 'Backups Automáticos',
    'infra.feat_backups_desc' => 'Backups agendados com download direto. Retenção configurável e restauração com um clique.',
    'infra.feat_monitor' => 'Monitoramento',
    'infra.feat_monitor_desc' => 'CPU, memória e disco em tempo real. Alertas automáticos por e-mail e WhatsApp.',
    'infra.feat_email' => 'E-mails Profissionais',
    'infra.feat_email_desc' => 'Crie contas no seu próprio domínio. Integração com Mailcow e webmail incluso.',
    'infra.feat_suporte' => 'Suporte Integrado',
    'infra.feat_suporte_desc' => 'Chat ao vivo e sistema de tickets com histórico completo de atendimentos.',
    'infra.feat_planos' => 'Planos Flexíveis',
    'infra.feat_planos_desc' => 'Escolha o plano ideal para seu projeto. Upgrade ou downgrade a qualquer momento.',
    'infra.feat_2fa' => '2FA & Segurança',
    'infra.feat_2fa_desc' => 'Autenticação em dois fatores, RBAC por roles, auditoria completa e proteção CSRF.',
    'infra.steps_label' => 'Como funciona',
    'infra.steps_titulo' => 'Do zero ao ar em minutos',
    'infra.steps_sub' => 'Sem configurações complexas. Sua infraestrutura pronta para produção em 4 passos.',
    'infra.step1_titulo' => 'Crie sua conta',
    'infra.step1_desc' => 'Cadastro rápido, sem cartão de crédito para começar.',
    'infra.step2_titulo' => 'Escolha um plano',
    'infra.step2_desc' => 'Selecione os recursos que seu projeto precisa.',
    'infra.step3_titulo' => 'VPS provisionada',
    'infra.step3_desc' => 'Seu servidor é criado automaticamente em menos de 60 segundos.',
    'infra.step4_titulo' => 'Gerencie tudo',
    'infra.step4_desc' => 'Terminal, deploy, backups, e-mails e suporte em um único painel.',
    'infra.plans_label' => 'Planos',
    'infra.plans_titulo' => 'Preços transparentes, sem surpresas',
    'infra.plans_sub' => 'Escolha o plano ideal para o seu projeto. Todos incluem suporte, backups e monitoramento.',
    'infra.plans_mensal' => 'Cobrado mensalmente',
    'infra.plans_anual' => 'Cobrado anualmente',
    'infra.plans_backups' => 'Backups automáticos',
    'infra.plans_monitor' => 'Monitoramento 24/7',
    'infra.plans_suporte' => 'Suporte via chat e tickets',
    'infra.plans_comecar' => 'Começar agora',
    'infra.plans_empty' => 'Planos em breve.',
    'infra.plans_contato' => 'Entre em contato',
    'infra.plans_saber_mais' => 'para saber mais.',
    'infra.plans_custom' => 'Precisa de algo personalizado?',
    'infra.plans_fale' => 'Fale com a equipe',
    'infra.plans_popular' => 'Mais popular',
    'infra.plans_mes' => '/mês',
    'infra.plans_ano' => '/ano',
    'infra.plans_moeda' => 'R$',
    'infra.tech_label' => 'Tecnologia',
    'infra.tech_titulo' => 'Stack moderno e confiável',
    'infra.tech_sub' => 'Construído com as melhores tecnologias para garantir performance, segurança e escalabilidade.',
    'infra.tech_php' => 'PHP 8.3 + MVC próprio',
    'infra.tech_php_desc' => 'Framework MVC customizado, sem overhead de dependências externas. Rápido e previsível.',
    'infra.tech_mysql' => 'MySQL com prepared statements',
    'infra.tech_mysql_desc' => 'Todas as queries usam prepared statements. Zero ORM, controle total sobre o banco.',
    'infra.tech_docker' => 'Docker & SSH remoto',
    'infra.tech_docker_desc' => 'Provisionamento e deploy via SSH. Containers Docker gerenciados diretamente pelo painel.',
    'infra.tech_ws' => 'WebSocket em tempo real',
    'infra.tech_ws_desc' => 'Terminal web e chat ao vivo via WebSocket. Latência mínima, experiência fluida.',
    'infra.tech_sec' => 'Segurança em camadas',
    'infra.tech_sec_desc' => 'CSRF, RBAC, 2FA TOTP, rate limiting, replay attack protection e auditoria completa.',
    'infra.tech_mail' => 'Mailcow integrado',
    'infra.tech_mail_desc' => 'Gerenciamento de e-mails via API Mailcow. Domínios próprios, webmail e DNS automático.',
    'infra.sec_label' => 'Segurança',
    'infra.sec_titulo' => 'Sua infraestrutura protegida',
    'infra.sec_sub' => 'Múltiplas camadas de segurança para proteger seus dados e operações.',
    'infra.sec_2fa' => 'Autenticação 2FA (TOTP)',
    'infra.sec_2fa_desc' => 'Proteção extra com autenticação em dois fatores via Google Authenticator ou similar.',
    'infra.sec_rbac' => 'RBAC por roles',
    'infra.sec_rbac_desc' => 'Controle granular de permissões por papel: superadmin, admin, devops, dev e suporte.',
    'infra.sec_csrf' => 'Proteção CSRF & Rate Limit',
    'infra.sec_csrf_desc' => 'Tokens CSRF em todos os formulários e rate limiting por IP para prevenir abusos.',
    'infra.sec_audit' => 'Auditoria completa',
    'infra.sec_audit_desc' => 'Log de todas as ações da equipe e clientes. Rastreabilidade total para compliance.',
    'infra.faq_label' => 'FAQ',
    'infra.faq_titulo' => 'Perguntas frequentes',
    'infra.faq_sub' => 'Tire suas dúvidas sobre a plataforma.',
    'infra.faq1_q' => 'Preciso de cartão de crédito para começar?',
    'infra.faq1_a' => 'Não. Você pode criar sua conta e explorar o painel gratuitamente. O cartão só é necessário ao assinar um plano pago.',
    'infra.faq2_q' => 'Em quanto tempo minha VPS fica pronta?',
    'infra.faq2_a' => 'O provisionamento é automático e leva menos de 60 segundos após a confirmação do pagamento.',
    'infra.faq3_q' => 'Posso fazer upgrade ou downgrade do plano?',
    'infra.faq3_a' => 'Sim. Você pode alterar seu plano a qualquer momento pelo painel. A mudança é aplicada imediatamente.',
    'infra.faq4_q' => 'Os backups são automáticos?',
    'infra.faq4_a' => 'Sim. Backups são agendados automaticamente conforme o plano. Você também pode criar backups manuais e fazer download a qualquer momento.',
    'infra.faq5_q' => 'Como funciona o suporte?',
    'infra.faq5_a' => 'O suporte é feito via chat ao vivo e sistema de tickets diretamente no painel. Nossa equipe responde em horário comercial.',
    'infra.access_label' => 'Acesso',
    'infra.access_titulo' => 'Escolha seu perfil',
    'infra.access_sub' => 'Área do cliente ou painel administrativo — cada um com seu espaço.',
    'infra.access_cliente' => 'Área do cliente',
    'infra.access_cliente_desc' => 'Acesse suas VPS, aplicações, e-mails, backups, monitoramento e suporte.',
    'infra.access_admin' => 'Painel administrativo',
    'infra.access_admin_desc' => 'Gerencie clientes, servidores, cobranças, tickets e toda a infraestrutura.',
    'infra.access_entrar_equipe' => 'Entrar como equipe',
    'infra.cta_trial' => 'Comece seu teste grátis agora',
    'infra.cta_pronto' => 'Pronto para começar?',
    'infra.cta_sub' => 'Crie sua conta agora e tenha sua infraestrutura funcionando em minutos.',
    'infra.cta_falar' => 'Falar com a equipe',
    'infra.footer_desc' => 'Plataforma cloud SaaS para gerenciamento de VPS, aplicações, e-mails e suporte.',
    'infra.footer_col_produto' => 'Produto',
    'infra.footer_col_suporte' => 'Suporte',
    'infra.footer_col_legal' => 'Legal',
    'infra.footer_funcionalidades' => 'Funcionalidades',
    'infra.footer_planos' => 'Planos',
    'infra.footer_tecnologia' => 'Tecnologia',
    'infra.footer_contato' => 'Contato',
    'infra.footer_status' => 'Status do sistema',
    'infra.footer_tickets' => 'Tickets',
    'infra.footer_termos' => 'Termos de uso',
    'infra.footer_privacidade' => 'Privacidade',
    'infra.footer_sistema_op' => 'Sistema operacional',
    'infra.cta_criar_conta' => 'Criar conta grátis',
    'infra.access_entrar' => 'Entrar',

    // ── Licença (página pública) ──
    'licenca.label' => 'Legal',
    'licenca.titulo' => 'Licença de Uso Proprietária',
    'licenca.subtitulo' => 'Este documento estabelece os termos e condições de uso do software LRV Cloud Manager.',
    'licenca.nav_termos' => 'Termos',
    'licenca.nav_privacidade' => 'Privacidade',
    'licenca.nav_contato' => 'Contato',

    // ── Changelog ──
    'changelog.label' => 'Histórico de versões',
    'changelog.titulo' => 'Changelog',
    'changelog.sub' => 'Acompanhe todas as novidades, melhorias e correções do sistema.',

    // ── Contato ──
    'contato.label' => 'Fale conosco',
    'contato.titulo' => 'Contato',
    'contato.sub' => 'Tem alguma dúvida ou precisa de ajuda? Envie uma mensagem e retornaremos em breve.',
    'contato.nome' => 'Nome',
    'contato.email' => 'E-mail',
    'contato.assunto' => 'Assunto',
    'contato.mensagem' => 'Mensagem',
    'contato.enviar' => 'Enviar mensagem',
    'contato.ph_nome' => 'Seu nome',
    'contato.ph_email' => 'seu@email.com',
    'contato.ph_assunto' => 'Como podemos ajudar?',
    'contato.ph_mensagem' => 'Descreva sua dúvida ou solicitação...',

    // ── Status ──
    'status_page.label' => 'Transparência operacional',
    'status_page.titulo' => 'Status do sistema',
    'status_page.servicos' => 'Serviços',
    'status_page.auto_refresh' => 'Atualização automática a cada 30s',
    'status_page.th_servico' => 'Serviço',
    'status_page.th_status' => 'Status',
    'status_page.th_uptime' => 'Uptime 24h',
    'status_page.th_historico' => 'Histórico',
    'status_page.th_checagem' => 'Última checagem',
    'status_page.nenhum_servico' => 'Nenhum serviço configurado ainda.',
    'status_page.incidentes' => 'Incidentes recentes',
    'status_page.nenhum_incidente' => 'Nenhum incidente recente. Tudo operando normalmente.',
    'status_page.inicio' => 'Início:',
    'status_page.resolvido' => 'Resolvido:',
    'status_page.operacional' => 'Operacional',
    'status_page.degradado' => 'Degradado',
    'status_page.indisponivel' => 'Indisponível',
    'status_page.desconhecido' => 'Desconhecido',
    'status_page.resolvido_badge' => 'Resolvido',
    'status_page.monitorando' => 'Monitorando',
    'status_page.identificado' => 'Identificado',
    'status_page.investigando' => 'Investigando',
    'status_page.critico' => 'Crítico',
    'status_page.alto' => 'Alto',
    'status_page.baixo' => 'Baixo',

    // ── Status Incidentes ──
    'status_inc.nenhum' => 'Nenhum incidente registrado.',
    'status_inc.anterior' => '← Anterior',
    'status_inc.proxima' => 'Próxima →',
    'status_inc.pagina' => 'Página %d de %d',
    'status_inc.titulo' => 'Histórico de incidentes',
    'status_inc.sub' => 'Veja o histórico completo de incidentes e manutenções.',

    // ── Termos ──
    'termos.label' => 'Legal',
    'termos.titulo' => 'Termos de Uso',
    'termos.sub' => 'Leia com atenção os termos que regem o uso da plataforma.',
    'termos.vazio' => 'Os termos de uso ainda não foram configurados. Entre em contato com o administrador.',

    // ── Privacidade ──
    'privacidade.label' => 'Legal',
    'privacidade.titulo' => 'Política de Privacidade',
    'privacidade.sub' => 'Saiba como coletamos, usamos e protegemos seus dados.',
    'privacidade.vazio' => 'A política de privacidade ainda não foi configurada. Entre em contato com o administrador.',

    // ── Stripe Checkout ──
    'stripe.sucesso_titulo' => 'Pagamento confirmado',
    'stripe.sucesso_sub' => 'Sua assinatura foi ativada com sucesso.',
    'stripe.erro_tentar' => 'Tentar novamente',
    'stripe.detalhes' => 'Detalhes da assinatura',
    'stripe.plano' => 'Plano',
    'stripe.valor' => 'Valor',
    'stripe.prox_cobranca' => 'Próx. cobrança',
    'stripe.status' => 'Status',
    'stripe.ativa' => 'Ativa',
    'stripe.vps_vinculada' => 'VPS vinculada',
    'stripe.proximos_passos' => 'Próximos passos:',
    'stripe.passo_1' => 'Sua VPS será provisionada automaticamente em alguns minutos.',
    'stripe.passo_2' => 'Você receberá as credenciais de acesso no painel.',
    'stripe.passo_3' => 'Em caso de dúvidas, abra um ticket de suporte.',
    'stripe.ver_vps' => 'Ver minhas VPS',
    'stripe.ver_assinaturas' => 'Ver assinaturas',
    'stripe.cancelado_titulo' => 'Checkout cancelado',
    'stripe.cancelado_sub' => 'Você cancelou o checkout. Nenhuma cobrança foi gerada.',
    'stripe.escolher_plano' => 'Escolher outro plano',
    'stripe.voltar_planos' => 'Ver planos',

    // ── Checkout ──
    'checkout.forma_pagamento' => 'Forma de pagamento',
    'checkout.cartao' => 'Cartão',
    'checkout.cpf_cnpj' => 'CPF ou CNPJ',
    'checkout.cpf_obrigatorio' => 'Obrigatório para emissão da cobrança.',

    // ── Pagamento ──
    'pagamento.titulo' => 'Pagamento',
    'pagamento.confirmado_titulo' => 'Pagamento confirmado',
    'pagamento.confirmado_sub' => 'Sua VPS será provisionada automaticamente.',
    'pagamento.ver_assinaturas' => 'Ver assinaturas',
    'pagamento.aguardando_pix' => 'Aguardando pagamento via PIX',
    'pagamento.pix_copia_cola' => 'PIX Copia e Cola',
    'pagamento.copiar' => 'Copiar',
    'pagamento.copiado' => 'Copiado!',
    'pagamento.pix_expira' => 'Expira em',
    'pagamento.pix_instrucao' => 'Escaneie o QR Code ou copie o código acima e cole no app do seu banco. O pagamento será confirmado automaticamente.',
    'pagamento.boleto_titulo' => 'Boleto gerado',
    'pagamento.boleto_aviso' => 'O boleto pode levar até 3 dias úteis para compensar.',
    'pagamento.boleto_linha' => 'Linha digitável',
    'pagamento.boleto_baixar' => 'Baixar boleto',
    'pagamento.boleto_instrucao' => 'Após o pagamento, a confirmação será automática. Você pode acompanhar em Assinaturas.',
    'pagamento.cartao_titulo' => 'Pagamento com cartão',
    'pagamento.dados_cartao' => 'Dados do cartão',
    'pagamento.nome_cartao' => 'Nome impresso no cartão',
    'pagamento.numero_cartao' => 'Número do cartão',
    'pagamento.dados_titular' => 'Dados do titular',
    'pagamento.telefone' => 'Telefone',
    'pagamento.numero_endereco' => 'Número do endereço',
    'pagamento.pagar' => 'Pagar',
    'pagamento.processando' => 'Processando...',
    'pagamento.cartao_sucesso' => 'Pagamento aprovado! Redirecionando...',
    'pagamento.cartao_analise' => 'Pagamento em análise. Aguarde a confirmação.',
    'pagamento.erro_generico' => 'Erro ao processar pagamento. Tente novamente.',
    'pagamento.erro_tipo' => 'Tipo de pagamento não identificado.',
    'pagamento.voltar_planos' => 'Voltar aos planos',

    // ── Chat Flows ──
    'chat_flows.titulo' => 'Fluxos de Chat',
    'chat_flows.subtitulo' => 'Gerencie sequências automatizadas de mensagens',
    'chat_flows.novo_fluxo' => 'Novo Fluxo',
    'chat_flows.editar_fluxo' => 'Editar Fluxo',
    'chat_flows.dados_fluxo' => 'Dados do Fluxo',
    'chat_flows.nome' => 'Nome',
    'chat_flows.descricao' => 'Descrição',
    'chat_flows.gatilho' => 'Gatilho',
    'chat_flows.trigger_inatividade' => 'Inatividade do cliente',
    'chat_flows.trigger_encerramento' => 'Encerramento do chat',
    'chat_flows.trigger_manual' => 'Manual',
    'chat_flows.passos' => 'Passos',
    'chat_flows.tipo' => 'Tipo',
    'chat_flows.conteudo' => 'Conteúdo',
    'chat_flows.tipo_mensagem' => 'Mensagem',
    'chat_flows.tipo_atraso' => 'Atraso',
    'chat_flows.tipo_acao' => 'Ação',
    'chat_flows.segundos' => 'Segundos',
    'chat_flows.acao_fechar_chat' => 'Fechar chat',
    'chat_flows.acao_enviar_satisfacao' => 'Enviar link de satisfação',
    'chat_flows.adicionar_passo' => 'Adicionar Passo',
    'chat_flows.adicionar' => 'Adicionar',
    'chat_flows.confirmar_excluir' => 'Tem certeza que deseja excluir este fluxo?',
    'chat_flows.confirmar_remover_passo' => 'Tem certeza que deseja remover este passo?',
    'chat_flows.nenhum_passo' => 'Nenhum passo cadastrado.',
    'chat_flows.historico_execucoes' => 'Histórico de Execuções',
    'chat_flows.nenhuma_execucao' => 'Nenhuma execução registrada.',
    'chat_flows.sala' => 'Sala',
    'chat_flows.origem' => 'Origem',
    'chat_flows.iniciado_em' => 'Iniciado em',
    'chat_flows.concluido_em' => 'Concluído em',
    'chat_flows.timeout_inatividade' => 'Timeout de inatividade',
    'chat_flows.minutos' => 'minutos',
    'chat_flows.fluxos' => 'Fluxos',
    'chat_flows.disparar_fluxo' => 'Disparar fluxo manual',
    'chat_flows.sistema' => 'Sistema',
];
