CREATE TABLE IF NOT EXISTS plans (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(190) NOT NULL,
  description VARCHAR(255) NULL,
  cpu INT UNSIGNED NOT NULL,
  ram BIGINT UNSIGNED NOT NULL,
  storage BIGINT UNSIGNED NOT NULL,
  price_monthly DECIMAL(10,2) NOT NULL,
  specs_json LONGTEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE vps
  ADD COLUMN plan_id INT UNSIGNED NULL;

ALTER TABLE vps
  ADD CONSTRAINT fk_vps_plan FOREIGN KEY (plan_id) REFERENCES plans(id);
