<?php

declare(strict_types=1);

namespace LRV\App\Controllers;

use LRV\Core\BancoDeDados;
use LRV\Core\Http\Requisicao;
use LRV\Core\Http\Resposta;
use LRV\Core\View;

final class StatusController
{
    public function index(Requisicao $req): Resposta
    {
        $pdo = BancoDeDados::pdo();

        $stmt = $pdo->query("SELECT id, `key`, name, description, status, last_check_at, last_ok_at, last_error, meta_json FROM status_services WHERE scope = 'public' ORDER BY name ASC");
        $services = $stmt->fetchAll();
        $services = is_array($services) ? $services : [];

        // Se não tem serviços públicos cadastrados, gerar automaticamente a partir dos servidores ativos
        if (empty($services)) {
            $srvStmt = $pdo->query("SELECT id, hostname, ip_address, status, is_managed_server FROM servers WHERE status = 'active' ORDER BY hostname ASC");
            $servers = $srvStmt->fetchAll();
            if (is_array($servers)) {
                foreach ($servers as $srv) {
                    if (!is_array($srv)) continue;
                    $srvId = (int)($srv['id'] ?? 0);
                    $hostname = trim((string)($srv['hostname'] ?? ''));
                    $isManaged = (int)($srv['is_managed_server'] ?? 0);
                    $srvStatus = (string)($srv['status'] ?? 'active');

                    // Buscar última métrica pra determinar se está online
                    $metricStmt = $pdo->prepare("SELECT cpu_usage, ram_usage, disk_usage, timestamp FROM server_metrics WHERE server_id = :sid ORDER BY id DESC LIMIT 1");
                    $metricStmt->execute([':sid' => $srvId]);
                    $metric = $metricStmt->fetch();

                    $lastCheck = null;
                    $status = 'operational';
                    if (is_array($metric)) {
                        $lastCheck = (string)($metric['timestamp'] ?? '');
                        // Se última métrica é de mais de 10 minutos atrás, considerar degradado
                        $metricTime = strtotime($lastCheck);
                        if ($metricTime > 0 && (time() - $metricTime) > 600) {
                            $status = 'degraded';
                        }
                        if ($metricTime > 0 && (time() - $metricTime) > 1800) {
                            $status = 'major_outage';
                        }
                    } else {
                        $status = 'unknown';
                    }

                    // Nome genérico: Servidor 1, Servidor 2, etc (não expor hostname/IP)
                    $serverNum = count($services) + 1;
                    $displayName = 'Servidor ' . $serverNum;

                    $services[] = [
                        'id' => $srvId,
                        'key' => 'server_' . $srvId,
                        'name' => $displayName,
                        'description' => '',
                        'status' => $status,
                        'last_check_at' => $lastCheck,
                        'last_ok_at' => $lastCheck,
                        'last_error' => null,
                        'meta_json' => null,
                    ];
                }
            }
        }

        $serviceIds = [];
        foreach ($services as $s) {
            if (!is_array($s)) {
                continue;
            }
            $id = (int) ($s['id'] ?? 0);
            if ($id > 0) {
                $serviceIds[] = $id;
            }
        }

        // Flag para indicar se os serviços foram auto-gerados (não vêm da status_logs)
        $autoGenerated = empty($serviceIds) || !$pdo->query("SELECT 1 FROM status_logs WHERE service_id IN (" . implode(',', array_map('intval', $serviceIds)) . ") LIMIT 1")->fetch();

        $uptime24 = [];
        if (!empty($serviceIds) && !$autoGenerated) {
            $in = [];
            $params = [];
            foreach ($serviceIds as $i => $sid) {
                $ph = ':s' . $i;
                $in[] = $ph;
                $params[$ph] = $sid;
            }

            $sql = 'SELECT service_id, SUM(CASE WHEN status = \'operational\' THEN 1 ELSE 0 END) AS ok_total, COUNT(*) AS total FROM status_logs WHERE checked_at >= (NOW() - INTERVAL 24 HOUR) AND service_id IN (' . implode(',', $in) . ') GROUP BY service_id';
            $st = $pdo->prepare($sql);
            $st->execute($params);
            $rows = $st->fetchAll();
            if (is_array($rows)) {
                foreach ($rows as $r) {
                    if (!is_array($r)) {
                        continue;
                    }
                    $sid = (int) ($r['service_id'] ?? 0);
                    $ok = (int) ($r['ok_total'] ?? 0);
                    $tot = (int) ($r['total'] ?? 0);
                    $uptime24[$sid] = $tot > 0 ? (($ok / $tot) * 100.0) : null;
                }
            }
        }

        $bars = [];
        if (!empty($serviceIds)) {
            $in = [];
            $params = [];
            foreach ($serviceIds as $i => $sid) {
                $ph = ':b' . $i;
                $in[] = $ph;
                $params[$ph] = $sid;
            }

            $sql = 'SELECT service_id, status FROM status_logs WHERE checked_at >= (NOW() - INTERVAL 24 HOUR) AND service_id IN (' . implode(',', $in) . ') ORDER BY service_id ASC, checked_at DESC, id DESC';
            $st = $pdo->prepare($sql);
            $st->execute($params);
            $rows = $st->fetchAll();
            if (is_array($rows)) {
                $limite = 24;
                foreach ($rows as $r) {
                    if (!is_array($r)) {
                        continue;
                    }
                    $sid = (int) ($r['service_id'] ?? 0);
                    if ($sid <= 0) {
                        continue;
                    }
                    if (!isset($bars[$sid])) {
                        $bars[$sid] = [];
                    }
                    if (count($bars[$sid]) >= $limite) {
                        continue;
                    }
                    $bars[$sid][] = (string) ($r['status'] ?? 'unknown');
                }
            }

            foreach ($bars as $sid => $arr) {
                $bars[$sid] = array_reverse($arr);
            }
        }

        // Se auto-gerado, calcular uptime a partir de server_metrics
        if ($autoGenerated && !empty($serviceIds)) {
            foreach ($serviceIds as $sid) {
                // Contar métricas das últimas 24h como proxy de uptime
                $mStmt = $pdo->prepare("SELECT COUNT(*) AS total FROM server_metrics WHERE server_id = :sid AND timestamp >= (NOW() - INTERVAL 24 HOUR)");
                $mStmt->execute([':sid' => $sid]);
                $mRow = $mStmt->fetch();
                $totalMetrics = is_array($mRow) ? (int)($mRow['total'] ?? 0) : 0;

                if ($totalMetrics > 0) {
                    // Se tem métricas, considerar 100% uptime (servidor respondeu em todas as coletas)
                    $uptime24[$sid] = 100.0;

                    // Gerar barras verdes (24 pontos = últimas 24h em intervalos de 1h)
                    $bars[$sid] = array_fill(0, min($totalMetrics, 24), 'operational');
                }
            }
        }

        $stmt = $pdo->query("SELECT id, title, status, impact, scope, message, started_at, resolved_at, created_at, updated_at FROM status_incidents WHERE scope = 'public' ORDER BY started_at DESC, id DESC LIMIT 20");
        $incidents = $stmt->fetchAll();
        $incidents = is_array($incidents) ? $incidents : [];

        $incidentIds = [];
        foreach ($incidents as $inc) {
            if (!is_array($inc)) {
                continue;
            }
            $id = (int) ($inc['id'] ?? 0);
            if ($id > 0) {
                $incidentIds[] = $id;
            }
        }

        $updates = [];
        if (!empty($incidentIds)) {
            $in = [];
            $params = [];
            foreach ($incidentIds as $i => $iid) {
                $ph = ':i' . $i;
                $in[] = $ph;
                $params[$ph] = $iid;
            }

            $sql = 'SELECT incident_id, status, message, created_at FROM status_incident_updates WHERE incident_id IN (' . implode(',', $in) . ') ORDER BY incident_id ASC, created_at DESC, id DESC';
            $st = $pdo->prepare($sql);
            $st->execute($params);
            $rows = $st->fetchAll();
            if (is_array($rows)) {
                foreach ($rows as $r) {
                    if (!is_array($r)) {
                        continue;
                    }
                    $iid = (int) ($r['incident_id'] ?? 0);
                    if ($iid <= 0) {
                        continue;
                    }
                    if (!isset($updates[$iid])) {
                        $updates[$iid] = [];
                    }
                    if (count($updates[$iid]) >= 5) {
                        continue;
                    }
                    $updates[$iid][] = $r;
                }
            }
        }

        $incidentServices = [];
        if (!empty($incidentIds)) {
            $in = [];
            $params = [];
            foreach ($incidentIds as $i => $iid) {
                $ph = ':is' . $i;
                $in[] = $ph;
                $params[$ph] = $iid;
            }

            $sql = 'SELECT x.incident_id, s.id AS service_id, s.name, s.`key`'
                . ' FROM status_incident_services x'
                . ' INNER JOIN status_services s ON s.id = x.service_id'
                . " WHERE s.scope = 'public' AND x.incident_id IN (" . implode(',', $in) . ')'
                . ' ORDER BY x.incident_id ASC, s.id ASC';
            $st = $pdo->prepare($sql);
            $st->execute($params);
            $rows = $st->fetchAll();
            if (is_array($rows)) {
                foreach ($rows as $r) {
                    if (!is_array($r)) {
                        continue;
                    }
                    $iid = (int) ($r['incident_id'] ?? 0);
                    if ($iid <= 0) {
                        continue;
                    }
                    if (!isset($incidentServices[$iid])) {
                        $incidentServices[$iid] = [];
                    }
                    $incidentServices[$iid][] = $r;
                }
            }
        }

        $html = View::renderizar(__DIR__ . '/../Views/status.php', [
            'services' => $services,
            'uptime24' => $uptime24,
            'bars' => $bars,
            'incidents' => $incidents,
            'updates' => $updates,
            'incidentServices' => $incidentServices,
        ]);

        return Resposta::html($html);
    }

    public function incidentes(Requisicao $req): Resposta
    {
        $pdo = BancoDeDados::pdo();
        $pagina = max(1, (int) ($req->query['pagina'] ?? 1));
        $porPagina = 20;
        $offset = ($pagina - 1) * $porPagina;

        $total = 0;
        $stmtTotal = $pdo->query("SELECT COUNT(*) AS total FROM status_incidents WHERE scope = 'public'");
        $rowTotal = $stmtTotal->fetch();
        if (is_array($rowTotal)) {
            $total = (int) ($rowTotal['total'] ?? 0);
        }

        $stmt = $pdo->prepare("SELECT id, title, status, impact, message, started_at, resolved_at, created_at FROM status_incidents WHERE scope = 'public' ORDER BY started_at DESC, id DESC LIMIT :lim OFFSET :off");
        $stmt->bindValue(':lim', $porPagina, \PDO::PARAM_INT);
        $stmt->bindValue(':off', $offset, \PDO::PARAM_INT);
        $stmt->execute();
        $incidents = $stmt->fetchAll();
        $incidents = is_array($incidents) ? $incidents : [];

        $incidentIds = array_filter(array_map(fn ($i) => is_array($i) ? (int) ($i['id'] ?? 0) : 0, $incidents));

        $updates = [];
        if (!empty($incidentIds)) {
            $in = implode(',', array_map('intval', $incidentIds));
            $st = $pdo->query("SELECT incident_id, status, message, created_at FROM status_incident_updates WHERE incident_id IN ({$in}) ORDER BY incident_id ASC, created_at ASC");
            $rows = $st->fetchAll();
            if (is_array($rows)) {
                foreach ($rows as $r) {
                    if (!is_array($r)) {
                        continue;
                    }
                    $iid = (int) ($r['incident_id'] ?? 0);
                    if ($iid > 0) {
                        $updates[$iid][] = $r;
                    }
                }
            }
        }

        $totalPaginas = (int) ceil($total / $porPagina);

        $html = View::renderizar(__DIR__ . '/../Views/status-incidentes.php', [
            'incidents' => $incidents,
            'updates' => $updates,
            'pagina' => $pagina,
            'totalPaginas' => $totalPaginas,
            'total' => $total,
        ]);

        return Resposta::html($html);
    }
}
